import type { CalculationResult } from "./calculations.ts";

export const calculusApplicationModels = ["calc-jacobian-error", "calc-hessian-spectrum", "calc-integral-region", "calc-ode-euler", "calc-lagrange", "calc-kkt"] as const;
export type CalculusApplicationModel = typeof calculusApplicationModels[number];
export const isCalculusApplicationModel = (model: string): model is CalculusApplicationModel => (calculusApplicationModels as readonly string[]).includes(model);
type Point = [number, number];
const value = (label: string, value: number, unit = "") => ({ label, value, unit });
const fmt = (n: number) => Number(n.toFixed(6));
const curve = (lo: number, hi: number, fn: (x: number) => number): Point[] => Array.from({ length: 181 }, (_, i) => { const x = lo + (hi - lo) * i / 180; return [x, fn(x)]; });

export function calculateCalculusApplication(model: CalculusApplicationModel, input: number): CalculationResult {
  const bounds: Record<CalculusApplicationModel, [number, number]> = { "calc-jacobian-error": [0, 1], "calc-hessian-spectrum": [-2, 2], "calc-integral-region": [0, 1], "calc-ode-euler": [2, 60], "calc-lagrange": [-4, 4], "calc-kkt": [0.25, 4] };
  const [lo, hi] = bounds[model];
  if (!Number.isFinite(input) || input < lo || input > hi || (model === "calc-ode-euler" && !Number.isInteger(input))) throw new Error(`Invalid ${model} input`);
  const base: CalculationResult = { kind: "lines", series: [], xDomain: [-0.5, 3.5], yDomain: [-0.5, 3.5], xLabel: "Output change ΔF₁", yLabel: "Output change ΔF₂", summary: "", values: [] };
  if (model === "calc-jacobian-error") {
    const predicted: Point = [0.4 * input, 2.2 * input];
    const actual: Point = [predicted[0] - 0.28 * input ** 2, predicted[1] + 0.96 * input ** 2];
    return { ...base, equalAspect: true, series: [{ label: "Linear prediction Jδ", points: [[0, 0], predicted] }, { label: "Actual nonlinear change", points: [[0, 0], actual] }, { label: "Remainder (endpoint gap)", points: [predicted, actual] }], summary: `At step length h=${input}, Jδ=(${fmt(predicted[0])}, ${fmt(predicted[1])}) and the actual change is (${fmt(actual[0])}, ${fmt(actual[1])}). The Euclidean error is h²=${fmt(input ** 2)}. ${input === 0 ? "Both changes vanish at zero step." : `Error divided by step length is h=${input}; it tends to zero as the step shrinks.`}`, matrices: [{ label: "J at (1, 0.5): output rows, input columns", entries: [[2, -1], [1, 2]], rowLabels: ["F₁", "F₂"], columnLabels: ["x", "y"] }], values: [value("Step length h", input), value("Input change δx", 0.6 * input), value("Input change δy", 0.8 * input), value("Predicted ΔF₁", predicted[0]), value("Predicted ΔF₂", predicted[1]), value("Actual ΔF₁", actual[0]), value("Actual ΔF₂", actual[1]), value("Absolute error norm", input ** 2)] };
  }
  if (model === "calc-hessian-spectrum") {
    const min = 1 - Math.abs(input), max = 1 + Math.abs(input);
    const classification = min > 0 ? "a unique global minimum" : min === 0 ? "a non-strict global minimum with an entire line of minimizers" : "a saddle point with unbounded descent directions";
    return { ...base, xDomain: [0, 360], yDomain: [-1.2, 3.2], xLabel: "Unit-direction angle θ (degrees)", yLabel: "Directional curvature uᵀHu", series: [{ label: "Curvature 1+a sin(2θ)", points: curve(0, 360, degrees => 1 + input * Math.sin(2 * degrees * Math.PI / 180)) }, { label: "Smallest eigenvalue", points: [[0, min], [360, min]] }, { label: "Largest eigenvalue", points: [[0, max], [360, max]] }], summary: `With coupling a=${input}, the Hessian eigenvalues are ${fmt(min)} and ${fmt(max)}. The origin is ${classification}. The diagonal entries are both 1 even when an off-axis direction has negative curvature. Classification is exact for this quadratic; semidefinite curvature alone is not enough for a general nonlinear function.`, matrices: [{ label: "Constant Hessian H", entries: [[1, input], [input, 1]], rowLabels: ["∂/∂x", "∂/∂y"], columnLabels: ["∂/∂x", "∂/∂y"] }], values: [value("Coupling a", input), value("Smallest eigenvalue", min), value("Largest eigenvalue", max), value("Curvature along x", 1), value("Curvature at 45°", 1 + input), value("Curvature at 135°", 1 - input), value("Hessian determinant", 1 - input * input)] };
  }
  if (model === "calc-integral-region") {
    const area = input - input ** 2 / 2, mass = input / 2 - input ** 3 / 6;
    return { ...base, equalAspect: true, xDomain: [-0.1, 1.1], yDomain: [-0.1, 1.1], xLabel: "x (length units)", yLabel: "y (length units)", shaded: [[0, 0], [input, 0], [input, 1 - input], [0, 1]], series: [{ label: "Full triangular boundary x+y≤1", points: [[0, 0], [1, 0], [0, 1], [0, 0]] }, { label: "Current slice x=t", points: [[input, 0], [input, 1 - input]] }], summary: `Accumulating from x=0 to t=${input} covers area ${fmt(area)} and integrates ρ(x,y)=x+y to mass ${fmt(mass)}. The slice contributes dM/dt=(1−t²)/2=${fmt((1 - input ** 2) / 2)}. Shading represents the included region, not density height. Full-region mass is 1/3, not its area 1/2.`, values: [value("Slice position t", input, "length units"), value("Slice height 1−t", 1 - input, "length units"), value("Included area", area, "area units"), value("Accumulated mass", mass, "mass units"), value("Mass per unit x at slice", (1 - input ** 2) / 2, "mass / length"), value("Full-region mass", 1 / 3, "mass units"), value("Fraction of total mass included", 3 * mass)] };
  }
  if (model === "calc-lagrange") {
    const x = input / 5, y = 2 * input / 5, lambda = -input / 5, radius = Math.abs(input) / Math.sqrt(5);
    const circle: Point[] = Array.from({ length: 181 }, (_, i) => { const angle = i * Math.PI / 90; return [radius * Math.cos(angle), radius * Math.sin(angle)]; });
    return { ...base, equalAspect: true, xDomain: [-4, 4], yDomain: [-4, 4], xLabel: "Decision x", yLabel: "Decision y", series: [{ label: "Feasible line x+2y=b (visible segment)", points: [[-4, (input + 4) / 2], [4, (input - 4) / 2]] }, { label: "Objective contour through optimum", points: circle }, { label: "Shortest segment from origin", points: [[0, 0], [x, y]] }], markers: [{ label: "Constrained minimizer", point: [x, y] }], summary: `For b=${input}, the nearest feasible point is (${fmt(x)}, ${fmt(y)}), with objective b²/10=${fmt(input ** 2 / 10)}. Using L=½(x²+y²)+λ(x+2y−b), λ=${fmt(lambda)} and dV/db=−λ=${fmt(-lambda)}. Equality multipliers may have either sign.`, values: [value("Constraint target b", input), value("Optimal x", x), value("Optimal y", y), value("Multiplier λ", lambda), value("Optimal objective V(b)", input ** 2 / 10), value("Sensitivity dV/db", -lambda), value("Constraint residual x+2y−b", x + 2 * y - input), value("Stationarity in x: x+λ", x + lambda), value("Stationarity in y: y+2λ", y + 2 * lambda)] };
  }
  if (model === "calc-kkt") {
    const b = input, x = b < 1 ? b : b < 3 ? (b + 1) / 2 : 2, y = b <= 1 ? 0 : b < 3 ? (b - 1) / 2 : 1;
    const lambda = b < 1 ? 2 - b : b < 3 ? (3 - b) / 2 : 0, mux = 0, muy = Math.max(0, 1 - b);
    const slacks = [b - x - y, x, y];
    return { ...base, equalAspect: true, xDomain: [-0.2, 4.2], yDomain: [-0.2, 4.2], xLabel: "Decision x", yLabel: "Decision y", shaded: [[0, 0], [b, 0], [0, b]], series: [{ label: "Feasible triangle x≥0, y≥0, x+y≤b", points: [[0, 0], [b, 0], [0, b], [0, 0]] }, { label: "Distance from unconstrained target", points: [[2, 1], [x, y]] }], markers: [{ label: "Unconstrained target (2,1)", point: [2, 1], hollow: true }, { label: "Constrained optimum", point: [x, y] }], summary: `Budget b=${b} gives optimum (${fmt(x)}, ${fmt(y)}). Multipliers (budget, x-floor, y-floor)=(${fmt(lambda)}, 0, ${fmt(muy)}). ${b < 1 ? "The budget and y=0 are both binding with positive multipliers." : b === 1 ? "The y-floor is still active but its multiplier is zero." : b < 3 ? "Only the budget is active; both decisions are positive." : b === 3 ? "The budget is active with zero multiplier at the unconstrained optimum." : "All three inequalities are strictly slack at the unconstrained optimum."} KKT residuals are shown numerically below.`, matrices: [{ label: "Constraint certificate (nonnegative slack and multiplier)", entries: [[slacks[0], lambda, lambda * slacks[0]], [slacks[1], mux, mux * slacks[1]], [slacks[2], muy, muy * slacks[2]]], rowLabels: ["budget", "x≥0", "y≥0"], columnLabels: ["Slack", "Dual", "Product"] }], values: [value("Optimal x", x), value("Optimal y", y), value("Optimal objective", ((x - 2) ** 2 + (y - 1) ** 2) / 2), value("Budget multiplier", lambda), value("x-floor multiplier", mux), value("y-floor multiplier", muy), value("x stationarity: x−2+λ−μx", x - 2 + lambda - mux), value("y stationarity: y−1+λ−μy", y - 1 + lambda - muy), value("Maximum primal violation", Math.max(0, -slacks[0], -slacks[1], -slacks[2])), value("Maximum complementary product", Math.max(Math.abs(lambda * slacks[0]), Math.abs(mux * slacks[1]), Math.abs(muy * slacks[2])))] };
  }
  const n = input, h = 3 / n, factor = 1 - 2 * h;
  const points: Point[] = [[0, 1]];
  let current = 1;
  for (let k = 1; k <= n; k++) { current *= factor; points.push([k * h, current]); }
  const error = Math.abs(current - Math.exp(-6));
  const minY = Math.min(0, ...points.map(([, y]) => y)), maxY = Math.max(1, ...points.map(([, y]) => y));
  return { ...base, xDomain: [0, 3], yDomain: [minY - 0.1 * (maxY - minY), maxY + 0.1 * (maxY - minY)], xLabel: "Time t (seconds)", yLabel: "State y (normalized)", series: [{ label: "Exact y(t)=exp(−2t)", points: curve(0, 3, t => Math.exp(-2 * t)) }, { label: "Explicit Euler grid values (joined)", points }], summary: `N=${n} steps gives h=${fmt(h)} seconds and Euler factor 1−2h=${fmt(factor)}. At t=3, Euler gives ${fmt(current)} versus exp(−6)=${fmt(Math.exp(-6))}; endpoint absolute error=${fmt(error)}. ${Math.abs(factor) > 1 ? "The numerical mode grows although the true state decays." : Math.abs(factor) === 1 ? "This boundary setting oscillates without decay." : factor < 0 ? "Grid values alternate sign while decaying: stable does not mean physically faithful." : "Grid values are nonnegative and decay, but time-discretization error remains."}`, values: [value("Number of steps N", n), value("Time step h", h, "seconds"), value("Euler amplification factor", factor), value("Euler endpoint y(3)", current), value("Exact endpoint y(3)", Math.exp(-6)), value("Endpoint absolute error", error), ...points.map(([t, y], i) => value(`Grid ${i}: t=${fmt(t)} s`, y))] };
}
