import type { CalculationResult } from "./calculations.ts";

export const informationModels = ["info-conditional", "info-mutual", "info-js", "info-rate", "info-bottleneck", "info-coding", "info-mdl"] as const;
export type InformationModel = typeof informationModels[number];
export const isInformationModel = (model: string): model is InformationModel => (informationModels as readonly string[]).includes(model);
type Point = [number, number];
const entropy = (p: number) => p === 0 || p === 1 ? 0 : -p * Math.log2(p) - (1 - p) * Math.log2(1 - p);
const value = (label: string, value: number, unit = "bits") => ({ label, value, unit });
const fmt = (n: number) => Number(n.toFixed(6));
const curve = (lo: number, hi: number, fn: (x: number) => number): Point[] => Array.from({ length: 201 }, (_, i) => { const x = lo + (hi - lo) * i / 200; return [x, fn(x)]; });
const grid = [0.1, 0.3, 0.5, 0.7, 0.9];
const mdlCandidates = (heads: number) => grid.map(q => ({ q, data: -heads * Math.log2(q) - (20 - heads) * Math.log2(1 - q) }));
const mdlBest = (heads: number) => mdlCandidates(heads).reduce((a, b) => b.data < a.data ? b : a);

export function calculateInformation(model: InformationModel, input: number): CalculationResult {
  const bounds: Record<InformationModel, [number, number]> = { "info-conditional": [0.01, 0.99], "info-mutual": [0, 0.5], "info-js": [0, 1], "info-rate": [0, 1], "info-bottleneck": [0, 4], "info-coding": [0, 0.5], "info-mdl": [0, 20] };
  const [lo, hi] = bounds[model];
  if (!Number.isFinite(input) || input < lo || input > hi || (model === "info-mdl" && !Number.isInteger(input))) throw new Error(`Invalid ${model} input`);
  const base: CalculationResult = { kind: "lines", series: [], xDomain: [lo, hi], yDomain: [0, 1.05], xLabel: "Control setting", yLabel: "Information (bits)", selectedX: input, summary: "", values: [] };
  if (model === "info-conditional") {
    const r = input, marginal = 0.05 + 0.45 * r, conditional = (1 - r) * entropy(0.05) + r;
    return { ...base, xLabel: "Frequency r of group Y=1", series: [{ label: "Before group is known: H(X)", points: curve(lo, hi, t => entropy(0.05 + 0.45 * t)) }, { label: "Average after: H(X|Y)", points: curve(lo, hi, t => (1 - t) * entropy(0.05) + t) }, { label: "Specific group Y=1: 1 bit", points: [[lo, 1], [hi, 1]] }], summary: `With P(Y=1)=${r}, P(X=1)=${fmt(marginal)}. H(X)=${fmt(entropy(marginal))} bits and H(X|Y)=${fmt(conditional)} bits. The specific group Y=1 has 1 bit of uncertainty, larger than H(X); the weighted average is smaller. Conditioning reduces entropy on average, not necessarily for each observation.`, matrices: [{ label: "Joint probability P(Y,X)", rowLabels: ["Y=0", "Y=1"], columnLabels: ["X=0", "X=1"], entries: [[0.95 * (1 - r), 0.05 * (1 - r)], [0.5 * r, 0.5 * r]] }], values: [value("P(Y=1)", r, "probability"), value("H(X)", entropy(marginal)), value("H(X|Y=0)", entropy(0.05)), value("H(X|Y=1)", 1), value("H(X|Y)", conditional), value("H(X)−H(X|Y)", entropy(marginal) - conditional)] };
  }
  if (model === "info-mutual") {
    const p = input, q = (2 - p) / 3, mi = entropy(q) - entropy(p);
    return { ...base, xLabel: "Independent output-flip probability ε", series: [{ label: "Mutual information I(X;Y), bits", points: curve(lo, hi, t => entropy((2 - t) / 3) - entropy(t)) }, { label: "Pearson correlation (dimensionless)", points: [[0, 0], [0.5, 0]] }], yLabel: "MI (bits) / correlation (unitless)", summary: `For X uniform on {−1,0,1} and Y=X² flipped with probability ε=${p}, I(X;Y)=${fmt(mi)} bits while Pearson correlation is exactly 0. ${p === 0.5 ? "At ε=0.5, the joint distribution factors and X,Y are independent." : "Y still gives information about whether X is zero, even though the positive and negative X contributions cancel in covariance."}`, matrices: [{ label: "Joint probability P(X,Y)", rowLabels: ["X=−1", "X=0", "X=1"], columnLabels: ["Y=0", "Y=1"], entries: [[p / 3, (1 - p) / 3], [(1 - p) / 3, p / 3], [p / 3, (1 - p) / 3]] }], values: [value("P(Y=1)", q, "probability"), value("H(Y)", entropy(q)), value("H(Y|X)", entropy(p)), value("I(X;Y)", mi), value("H(X)", Math.log2(3)), value("H(X|Y)", Math.log2(3) - mi), value("Covariance", 0, "X·Y units"), value("Pearson correlation", 0, "dimensionless")] };
  }
  if (model === "info-js") {
    const q = input, mix = q / 2, js = Math.max(0, entropy(mix) - entropy(q) / 2);
    const klP = -Math.log2(1 - mix), klQ = (q === 1 ? 0 : (1 - q) * Math.log2((1 - q) / (1 - mix))) + (q === 0 ? 0 : q);
    return { ...base, kind: "bars", selectedX: undefined, xDomain: [-0.5, 1.5], xLabel: "Outcome (0 or 1)", yLabel: "Probability mass", series: [{ label: "P=(1,0)", points: [[0, 1], [1, 0]] }, { label: `Q=(1−q,q), q=${q}`, points: [[0, 1 - q], [1, q]] }, { label: "Mixture M=(P+Q)/2", points: [[0, 1 - mix], [1, mix]] }], summary: `Equal-weight JS(P,Q)=${fmt(js)} bits; its square-root distance is ${fmt(Math.sqrt(js))}. The two KL-to-mixture terms are ${fmt(klP)} and ${fmt(klQ)} bits. ${q === 1 ? "Disjoint point masses reach the 1-bit upper bound; JS remains finite." : q === 0 ? "P and Q are identical, so both divergence and distance are zero." : "The mixture gives positive mass wherever either input does, keeping both KL terms finite."}`, values: [value("JS divergence", js), value("Square-root JS distance", Math.sqrt(js), "square-root bits"), value("KL(P‖M)", klP), value("KL(Q‖M)", klQ), value("H(M)", entropy(mix)), value("H(Q)", entropy(q))] };
  }
  if (model === "info-rate") {
    const rate = (d: number) => d < 0.5 ? 1 - entropy(d) : 0, r = rate(input);
    return { ...base, xLabel: "Allowed average Hamming distortion D", yLabel: "Minimum rate (bits/source symbol)", series: [{ label: "R(D): fair IID binary source", points: curve(0, 1, rate) }], markers: [{ label: "Selected distortion budget and minimum rate", point: [input, r] }], summary: `With average distortion at most D=${input}, R(D)=${fmt(r)} bits per source symbol in the asymptotic IID setting. ${input >= 0.5 ? "A fixed reconstruction already incurs distortion 0.5 and needs no transmitted bits. Allowing still more error cannot increase the minimum rate." : "The value is a theoretical block-coding limit, not the size of a finite file or the rate of a single-bit flipping algorithm."}`, values: [value("Allowed distortion D", input, "errors/source symbol"), value("R(D)", r, "bits/source symbol"), value("Lossless source entropy", 1, "bits/source symbol"), value("No-message constant reconstruction distortion", 0.5, "errors/source symbol"), value("Information-minimizing test-channel distortion", Math.min(input, 0.5), "errors/source symbol")] };
  }
  if (model === "info-bottleneck") {
    const candidates = [{ label: "Constant T", compression: 0, relevance: 0 }, { label: "Relevant bit T=Y", compression: 1, relevance: 1 }, { label: "Nuisance bit T=N", compression: 1, relevance: 0 }, { label: "Both bits T=X", compression: 2, relevance: 1 }];
    return { ...base, yDomain: [-3.3, 2.3], xLabel: "Relevance weight β", yLabel: "IB objective (bits)", series: candidates.map(c => ({ label: c.label, points: [[0, c.compression], [4, c.compression - 4 * c.relevance]] })), matrices: [{ label: "Four deterministic representation candidates", rowLabels: ["constant", "Y", "N", "(Y,N)"], columnLabels: ["I(X;T)", "I(T;Y)", "Objective"], entries: candidates.map(c => [c.compression, c.relevance, c.compression - input * c.relevance]) }], summary: `At β=${input}, the lowest displayed objective is ${fmt(Math.min(0, 1 - input))} bits. ${input < 1 ? "The constant representation wins: relevance is not weighted enough to pay for retaining a bit." : input === 1 ? "Constant T and T=Y tie; this objective is indifferent between them at the boundary." : "T=Y wins: retain the relevant bit and discard the independent nuisance bit."} Keeping both input bits costs one extra bit without adding target information.`, values: candidates.flatMap(c => [value(`${c.label}: I(X;T)`, c.compression), value(`${c.label}: I(T;Y)`, c.relevance), value(`${c.label}: objective`, c.compression - input * c.relevance)]) };
  }
  if (model === "info-coding") {
    const p = input, failure = 3 * p * p - 2 * p ** 3;
    return { ...base, yDomain: [0, 0.55], xLabel: "Independent channel bit-flip probability p", yLabel: "Decoded source-bit error probability", series: [{ label: "Uncoded: p", points: curve(0, 0.5, t => t) }, { label: "Repeat three times, majority decode", points: curve(0, 0.5, t => 3 * t * t - 2 * t ** 3) }], matrices: [{ label: "Number of flips in a three-use repetition block", rowLabels: ["0 flips", "1 flip", "2 flips", "3 flips"], columnLabels: ["Probability", "Decode fails"], entries: [[(1 - p) ** 3, 0], [3 * p * (1 - p) ** 2, 0], [3 * p * p * (1 - p), 1], [p ** 3, 1]] }], summary: `At channel error p=${p}, one uncoded use fails with probability ${p}; majority decoding of three independent copies fails with probability ${fmt(failure)}. Its rate is 1/3 source bit per channel use. This comparison spends three channel uses instead of one—it is not a free reliability gain at equal throughput or energy.`, values: [value("Uncoded error probability", p, "probability"), value("Repetition decoded error probability", failure, "probability"), value("Repetition rate", 1 / 3, "source bits/channel use"), value("Repetition block length", 3, "channel uses"), value("Minimum Hamming distance", 3, "bits"), value("Worst-case correctable flips per block", 1, "bit")] };
  }
  const k = input, best = mdlBest(k), familyLength = 4 + Math.ceil(best.data), baseline = 21;
  return { ...base, xDomain: [0, 20], yDomain: [0, 25], xLabel: "Heads k in a known-length 20-bit sequence", yLabel: "Total prefix-code length (bits)", series: [{ label: "Fair model: 1 header + 20 data bits", points: [[0, baseline], [20, baseline]] }, { label: "Best grid model: 1+3 header bits + rounded data length", points: Array.from({ length: 21 }, (_, heads) => [heads, 4 + Math.ceil(mdlBest(heads).data)] as Point) }], matrices: [{ label: "Parameter candidates including the model description", rowLabels: grid.map(q => `q=${q}`), columnLabels: ["Ideal data", "Rounded data", "Total"], entries: mdlCandidates(k).map(c => [c.data, Math.ceil(c.data), 4 + Math.ceil(c.data)]) }], summary: `For k=${k} heads out of 20, the shortest grid code selects q=${best.q} and uses 4+${Math.ceil(best.data)}=${familyLength} bits. The fair-model code uses ${baseline} bits. ${familyLength < baseline ? "The data saving pays for the extra parameter description." : familyLength === baseline ? "The two total descriptions tie." : "The fair model wins after counting parameter overhead."} These are valid length budgets for a specified two-part code, not a claim about every compressor.`, values: [value("Heads k", k, "heads"), value("Best grid parameter q", best.q, "probability"), value("Best ideal data information", best.data), value("Rounded data code length", Math.ceil(best.data)), value("Grid-model header", 4), value("Best grid total", familyLength), value("Fair-model total", baseline), value("Fair minus grid total", baseline - familyLength)] };
}
