import type { CalculationResult } from "./calculations.ts";
export const kalmanModels = ["filter-linear", "filter-extended", "filter-unscented"] as const;
export type KalmanModel = typeof kalmanModels[number];
export const isKalmanModel = (model: string): model is KalmanModel => (kalmanModels as readonly string[]).includes(model);
type Point = [number, number];
const curve = (lo: number, hi: number, f: (x: number) => number): Point[] => Array.from({ length: 241 }, (_, i) => { const x = lo + (hi - lo) * i / 240; return [x, f(x)]; });
const value = (label: string, value: number, unit = "") => ({ label, value, unit });
const fmt = (n: number) => Number(n.toFixed(6));
const normal = (x: number, mean: number, variance: number) => Math.exp(-((x - mean) ** 2) / (2 * variance)) / Math.sqrt(2 * Math.PI * variance);

export function calculateKalman(model: KalmanModel, input: number): CalculationResult {
  const bounds: Record<KalmanModel, [number, number]> = { "filter-linear": [0.25, 9], "filter-extended": [0, 2], "filter-unscented": [0.1, 2] };
  if (!Number.isFinite(input) || input < bounds[model][0] || input > bounds[model][1]) throw new Error(`Invalid ${model} input`);
  const base: CalculationResult = { kind: "lines", series: [], xDomain: [-3, 3], yDomain: [-18, 10], xLabel: "Normalized state x", yLabel: "Measurement function value", summary: "", values: [] };
  if (model === "filter-linear") {
    const r = input, gain = 4 / (4 + r), mean = 2 + 3 * gain, variance = (1 - gain) ** 2 * 4 + gain * gain * r;
    return { ...base, xDomain: [-6, 13], yDomain: [0, 0.9], xLabel: "Position x (metres)", yLabel: "Density / likelihood (per metre)", series: [{ label: "Predicted prior N(2,4)", points: curve(-6, 13, x => normal(x, 2, 4)) }, { label: `Measurement likelihood p(z=5|x), R=${fmt(r)}`, points: curve(-6, 13, x => normal(5, x, r)) }, { label: `Posterior N(${fmt(mean)},${fmt(variance)})`, points: curve(-6, 13, x => normal(x, mean, variance)) }], markers: [{ label: "Posterior mean and density peak", point: [mean, normal(mean, mean, variance)] }], summary: `Measurement noise variance R=${fmt(r)} m² gives gain K=${fmt(gain)}. The estimate moves from predicted 2 m toward measured 5 m, ending at ${fmt(mean)} m with variance ${fmt(variance)} m². These are exact conditional Gaussian moments under the stated linear model; R is a variance, not a standard deviation.`, values: [value("Previous mean", 1, "m"), value("Previous variance", 1, "m²"), value("Known motion", 1, "m"), value("Process noise variance Q", 3, "m²"), value("Predicted mean", 2, "m"), value("Predicted variance", 4, "m²"), value("Measurement noise variance R", r, "m²"), value("Innovation z−μ⁻", 3, "m"), value("Innovation variance", 4 + r, "m²"), value("Kalman gain", gain), value("Posterior mean", mean, "m"), value("Posterior variance", variance, "m²")] };
  }
  if (model === "filter-extended") {
    const mu = input, derivative = 2 * mu, predicted = mu * mu, innovationVariance = derivative ** 2 + 1, gain = derivative / innovationVariance, updated = mu + gain * (4 - predicted), variance = (1 - gain * derivative) ** 2 + gain * gain;
    return { ...base, series: [{ label: "True sensor h(x)=x²", points: curve(-3, 3, x => x * x) }, { label: `Tangent h(μ)+2μ(x−μ), μ=${fmt(mu)}`, points: curve(-3, 3, x => predicted + derivative * (x - mu)) }, { label: "Observed sensor value z=4", points: [[-3, 4], [3, 4]] }], markers: [{ label: "Linearization point", point: [mu, predicted] }], summary: `At prior mean μ=${fmt(mu)}, the sensor Jacobian is H=${fmt(derivative)}. EKF predicts measurement mean ${fmt(predicted)}, but the Gaussian prior's exact E[X²] is ${fmt(predicted + 1)}. For z=4 and R=1, its approximate update is μ⁺=${fmt(updated)}, P⁺=${fmt(variance)}. ${mu === 0 ? "The flat tangent makes K=0: the update ignores informative magnitude evidence." : "These are EKF approximation values, not exact nonlinear posterior moments."}`, values: [value("Prior mean μ", mu), value("Prior variance P", 1), value("Sensor Jacobian H", derivative), value("EKF predicted measurement mean", predicted), value("Exact predicted measurement mean", predicted + 1), value("EKF innovation variance H²P+R", innovationVariance), value("Exact measurement variance Var(X²)+R", 4 * mu * mu + 3), value("EKF gain", gain), value("EKF updated mean", updated), value("EKF updated variance", variance)] };
  }
  const sigma = input, variance = sigma * sigma, points = [1, 1 + sigma, 1 - sigma], wm = [0, 0.5, 0.5], wc = [2, 0.5, 0.5], transformed = points.map(x => x * x);
  const meanY = transformed.reduce((s, y, i) => s + wm[i] * y, 0), varY = transformed.reduce((s, y, i) => s + wc[i] * (y - meanY) ** 2, 0), cross = transformed.reduce((s, y, i) => s + wc[i] * (points[i] - 1) * (y - meanY), 0), gain = cross / (varY + 1);
  const updated = 1 + gain * (4 - meanY), updatedVariance = variance - gain * gain * (varY + 1);
  return { ...base, xDomain: [-1.5, 3.5], yDomain: [0, 16], xLabel: "Sigma-point state x (normalized)", yLabel: "Transformed value h(x)=x²", series: [{ label: "True sensor h(x)=x²", points: curve(-1.5, 3.5, x => x * x) }, { label: "Three transformed sigma points", points: points.map((x, i) => [x, transformed[i]]), style: "points" }, { label: `Weighted transformed mean ${fmt(meanY)}`, points: [[-1.5, meanY], [3.5, meanY]] }], matrices: [{ label: "Sigma-point rule (weights are not sample frequencies)", rowLabels: ["centre", "+σ", "−σ"], columnLabels: ["x", "h(x)", "w mean", "w cov"], entries: points.map((x, i) => [x, transformed[i], wm[i], wc[i]]) }], summary: `With prior N(1,${fmt(variance)}), the sigma-point transform gives mean ${fmt(meanY)} and variance ${fmt(varY)} for X², matching the exact Gaussian moments 1+P and 4P+2P². Adding R=1 gives gain ${fmt(gain)} and UKF update μ⁺=${fmt(updated)}, P⁺=${fmt(updatedVariance)} for z=4. Exact transformed moments do not make this nonlinear posterior Gaussian.`, values: [value("Prior standard deviation σ", sigma), value("Prior variance P", variance), value("UT transformed mean", meanY), value("Exact transformed mean 1+P", 1 + variance), value("UT transformed variance", varY), value("Exact transformed variance 4P+2P²", 4 * variance + 2 * variance * variance), value("State/measurement cross covariance", cross), value("Innovation variance including R=1", varY + 1), value("UKF gain", gain), value("UKF updated mean (approximation)", updated), value("UKF updated variance (approximation)", updatedVariance)] };
}
