import type { CalculationResult } from "./calculations.ts";
export const searchGuaranteeModels=["search-completeness","search-optimality","search-resources"] as const;
export type SearchGuaranteeModel=typeof searchGuaranteeModels[number];
export const isSearchGuaranteeModel=(model:string):model is SearchGuaranteeModel=>(searchGuaranteeModels as readonly string[]).includes(model);
const value=(label:string,value:number,unit="")=>({label,value,unit});
export function calculateSearchGuarantee(model:SearchGuaranteeModel,input:number):CalculationResult{
  if(!Number.isFinite(input)||input<(model==="search-completeness"?1:0)||input>(model==="search-completeness"?12:model==="search-resources"?10:9)||(model!=="search-optimality"&&!Number.isInteger(input)))throw new Error(`Invalid ${model} input`);
  if(model==="search-completeness"){
    const dfs=Array.from({length:input},(_,i)=>i===0?"S":`A${i-1}`),bfs=["S","A0","G"].slice(0,input),found=input>=3;
    return {kind:"matrix",series:[],xLabel:"Removal",yLabel:"Depth",xDomain:[0,12],yDomain:[0,12],controlValue:`Budget: ${input} ${input===1?"removal":"removals"}`,
      graph:{title:"A one-edge goal beside an infinite acyclic branch",height:420,maxWidth:370,summary:"S has children A0 then G. Each Ai has the single successor A(i+1), forever; no Ai is a goal. The drawing shows only the first three A states. The final label denotes an unbounded continuation, not a terminal leaf. All edges cost one. Dashed coral marks the goal edge once BFS returns G.",nodes:[{id:"S",label:"S",x:160,y:40,observed:false,state:""},{id:"A0",label:"A0",x:65,y:140,observed:false,state:""},{id:"G",label:"G",x:255,y:140,observed:false,state:""},{id:"A1",label:"A1",x:65,y:240,observed:false,state:""},{id:"A2",label:"A2",x:65,y:340,observed:false,state:"A3, A4, …"}],edges:[{from:"S",to:"A0",directed:true},{from:"S",to:"G",directed:true,accent:found},{from:"A0",to:"A1",directed:true},{from:"A1",to:"A2",directed:true}]},
      matrices:[{label:"DFS prefix under the selected budget",rowLabels:dfs.map((n,i)=>`${i+1}. ${n}`),columnLabels:["depth","goal (1=yes)"],entries:dfs.map((_,i)=>[i,0])},{label:"BFS stops as soon as G is removed",rowLabels:bfs.map((n,i)=>`${i+1}. ${n}`),columnLabels:["depth","goal (1=yes)"],entries:bfs.map((n,i)=>[i===0?0:1,Number(n==='G')])}],
      summary:`DFS removal prefix: ${dfs.join(' → ')}. Its budget ends without a goal; this finite observation alone does not prove nontermination. BFS removal prefix: ${bfs.join(' → ')}. ${found?'BFS returns S→G, a one-edge solution, after three removals.':'BFS has not yet removed G; the current budget is too small.'} Separately, the infinite transition rule proves DFS never returns to G: after each Ai it chooses the fresh child A(i+1), so the left branch never exhausts. Duplicate detection cannot help because these states are all distinct.`,
      values:[value("DFS removals",dfs.length),value("BFS removals",bfs.length),value("BFS found goal (1=yes)",Number(found)),value("DFS found goal (1=yes)",0),value("Depth of existing goal",1,"edge")]};
  }
  if(model==="search-optimality"){
    const short=1+input,long=4,optimum=Math.min(short,long),weights=Array.from({length:37},(_,i)=>i/4);
    return {kind:"lines",controlValue:`B→G cost w=${input} · optimal cost ${optimum}`,series:[{label:"Two-edge route S→B→G",points:weights.map(w=>[w,1+w])},{label:"Four-edge route S→A→C→D→G",points:weights.map(w=>[w,4])},{label:"True optimal-cost envelope",points:weights.map(w=>[w,Math.min(1+w,4)])}],xLabel:"Cost w of B→G (credits)",yLabel:"Complete route cost (credits)",xDomain:[0,9],yDomain:[0,10],selectedX:input,markers:[{label:"Routes tie at w=3",point:[3,4],hollow:true}],
      matrices:[{label:"Returned route costs under fixed policies",rowLabels:["BFS (fewest edges)","DFS (A branch first)","UCS (lowest g)"],columnLabels:["cost","gap to optimum"],entries:[[short,short-optimum],[long,long-optimum],[optimum,0]]}],
      summary:`The two-edge route costs 1+w=${short}; the four-edge route costs 4. Thus C*=${optimum}. ${input<3?'BFS is optimal on this instance and A-first DFS is not.':input===3?'Both routes are optimal: different edge counts can tie on the objective.':'A-first DFS happens to be optimal on this instance and BFS is not.'} BFS has additive gap ${short-optimum} and ratio ${Number((short/optimum).toFixed(4))}; DFS has additive gap ${long-optimum}. Finite-graph UCS with nonnegative weights, strict best-g updates and goal-on-removal returns C* throughout this family. Success on one slider setting is not a universal algorithm guarantee.`,
      values:[value("Optimal cost C*",optimum,"credits"),value("BFS cost",short,"credits"),value("DFS cost",long,"credits"),value("BFS optimality gap",short-optimum,"credits"),value("DFS optimality gap",long-optimum,"credits"),value("BFS approximation ratio",short/optimum)]};
  }
  const b=3,total=(d:number)=>(3**(d+1)-1)/2,front=(d:number)=>3**d,stack=(d:number)=>1+2*d,depths=Array.from({length:11},(_,i)=>i);
  return {kind:"lines",controlValue:`Full ternary tree through depth ${input}`,series:[{label:"Total node visits",style:"points",points:depths.map(d=>[d,Math.log10(total(d))])},{label:"Peak BFS frontier",style:"points",points:depths.map(d=>[d,Math.log10(front(d))])},{label:"Peak eager DFS stack",style:"points",points:depths.map(d=>[d,Math.log10(stack(d))])}],xLabel:"Maximum edge depth d",yLabel:"log₁₀(count of records or visits)",xDomain:[0,10],yDomain:[0,5],xTicks:[0,2,4,6,8,10],selectedX:input,
    matrices:[{label:"Exact counts for the selected bounded tree",rowLabels:["Total visits (BFS or DFS)","Internal nodes expanded","Peak BFS frontier","Peak eager DFS stack","Peak lazy recursive frames"],columnLabels:["count"],entries:[[total(input)],[(3**input-1)/2],[front(input)],[stack(input)],[input+1]]},{label:"Counts by depth (raw values, not logarithms)",rowLabels:depths.map(d=>`d=${d}`),columnLabels:["visits","BFS frontier","DFS stack"],entries:depths.map(d=>[total(d),front(d),stack(d)])}],
    summary:`For branching b=${b} and depth d=${input}, the bounded tree contains ${total(input)} ${input===0?"node":"nodes"} and ${front(input)} ${input===0?"leaf":"leaves"}. A full traversal visits every node; only ${(3**input-1)/2} internal nodes generate children. BFS's pending-node queue peaks at ${front(input)} ${input===0?"entry":"entries"}. Eager DFS, which replaces a popped internal node with all three children, peaks at 1+2d=${stack(input)} ${input===0?"entry":"entries"}; lazy recursive DFS needs ${input+1} active ${input===0?"frame":"frames"}. At a hypothetical 256 bytes per pending record, the BFS frontier alone uses ${Number((front(input)*256/1048576).toFixed(4))} MiB. This excludes graph storage, parents, closed sets, allocator overhead and tracing. Vertical plot positions are base-ten logarithms: a rise of one means ten times the count.`,
    values:[value("Total nodes visited",total(input)),value("BFS peak pending records",front(input)),value("DFS peak pending records",stack(input)),value("Lazy DFS peak frames",input+1),value("BFS frontier at 256 bytes/record",front(input)*256/1048576,"MiB")]};
}
