(function () {
  window.lessonData = {
    phaseCards: [
      {
        href: "mathematical-foundations/index.html",
        tag: "Phase 1",
        title: "Mathematical Foundations",
        summary: "Linear algebra, discrete math, proofs, graphs, and other math tools for AI.",
      },
      {
        href: "programming-and-systems-foundations/index.html",
        tag: "Phase 2",
        title: "Programming And Systems Foundations",
        summary: "Python, tensor programming, systems tools, hardware basics, precision, profiling, and reproducibility.",
      },
      {
        href: "classical-artificial-intelligence/index.html",
        tag: "Phase 3",
        title: "Classical Artificial Intelligence",
        summary: "Search, heuristics, state spaces, completeness, optimality, and planning foundations.",
      },
      {
        href: "probabilistic-ai/index.html",
        tag: "Phase 4",
        title: "Probabilistic AI",
        summary: "Graphical models, inference algorithms, sequential models, HMMs, and state estimation.",
      },
      {
        href: "foundations/index.html",
        tag: "Basics",
        title: "Foundations",
        summary: "Plain-language starting points for core AI ideas.",
      },
      {
        href: "machine-learning/index.html",
        tag: "Phase 5",
        title: "Classical Machine Learning",
        summary: "Regression, classification, linear models, SVMs, trees, ensembles, calibration, and losses.",
      },
      {
        href: "deep-learning/index.html",
        tag: "Phase 6",
        title: "Deep Learning Foundations",
        summary: "Neural networks, activations, normalization, CNNs, RNNs, sequence models, and architectures.",
      },
      {
        href: "generative-ai/index.html",
        tag: "Phase 7",
        title: "Transformers And Foundation Models",
        summary: "Transformer blocks, tokenization, efficient attention, pretraining, post-training, LoRA, and decoding.",
      },
      {
        href: "retrieval-search-and-rag/index.html",
        tag: "Phase 8",
        title: "Retrieval, Search And RAG",
        summary: "Classical retrieval, dense search, ANN indexes, reranking, and RAG architecture.",
      },
      {
        href: "reasoning-models-and-inference-time-computation/index.html",
        tag: "Phase 9",
        title: "Reasoning Models And Inference-Time Computation",
        summary: "Reasoning traces, self-consistency, verifier-guided search, tool use, and test-time scaling.",
      },
      {
        href: "ai-systems/index.html",
        tag: "Phase 10",
        title: "Agents And Tool-Using Systems",
        summary: "Agent patterns, tool routing, structured output, recovery policies, permissions, and production safety.",
      },
      {
        href: "representation-learning-and-self-supervision/index.html",
        tag: "Phase 11",
        title: "Representation Learning And Self-Supervision",
        summary: "Word embeddings, metric learning, contrastive objectives, CLIP, masked autoencoders, DINO, and JEPA-style methods.",
      },
      {
        href: "generative-modelling/index.html",
        tag: "Phase 12",
        title: "Generative Modelling",
        summary: "Autoregressive models, VAEs, GANs, normalizing flows, diffusion models, score models, and flow matching.",
      },
      {
        href: "state-space-models-and-alternative-sequence-architectures/index.html",
        tag: "Phase 13",
        title: "State-Space Models And Alternative Sequence Architectures",
        summary: "Linear dynamical systems, structured state spaces, S4, Mamba, gated convolutions, retention, and transformer hybrids.",
      },
      {
        href: "mixture-of-experts-models/index.html",
        tag: "Phase 14",
        title: "Mixture-Of-Experts Models",
        summary: "Sparse MoE layers, expert routing, top-k gating, load balancing, capacity, expert parallelism, and specialization.",
      },
      {
        href: "computer-vision/index.html",
        tag: "Phase 15",
        title: "Computer Vision",
        summary: "Classical vision, detection, segmentation, pose, tracking, depth, vision transformers, 3D reconstruction, and neural rendering.",
      },
      {
        href: "speech-audio-and-time-series-ai/index.html",
        tag: "Phase 16",
        title: "Speech, Audio And Time-Series AI",
        summary: "Signal processing, spectral features, forecasting, speech recognition, vocoders, audio generation, and source separation.",
      },
      {
        href: "multimodal-ai/index.html",
        tag: "Phase 17",
        title: "Multimodal AI",
        summary: "Vision-language learning, multimodal tokenization, fusion, VQA, captioning, document understanding, retrieval, and multimodal agents.",
      },
      {
        href: "reinforcement-learning/index.html",
        tag: "Phase 18",
        title: "Reinforcement Learning",
        summary: "Bandits, MDPs, Bellman equations, tabular RL, DQN, policy gradients, actor-critic methods, offline RL, imitation, and multi-agent RL.",
      },
      {
        href: "portfolio/index.html",
        tag: "Phase 19",
        title: "Portfolio",
        summary: "Projects and notes that show applied skill.",
      },
      {
        href: "graph-machine-learning/index.html",
        tag: "Phase 20",
        title: "Graph Machine Learning",
        summary: "Graph terminology, spectral methods, random walks, PageRank, embeddings, GNNs, knowledge graphs, and graph retrieval.",
      },
      {
        href: "causal-inference/index.html",
        tag: "Phase 21",
        title: "Causal Inference",
        summary: "DAGs, structural causal models, confounding, interventions, do-calculus, treatment effects, and causal discovery.",
      },
      {
        href: "interpretability-and-mechanistic-understanding/index.html",
        tag: "Phase 22",
        title: "Interpretability And Mechanistic Understanding",
        summary: "Model-agnostic explanations, neural attribution, representation probes, circuits, sparse autoencoders, and model editing.",
      },
      {
        href: "ai-safety-security-privacy-and-governance/index.html",
        tag: "Phase 23",
        title: "AI Safety, Security, Privacy And Governance",
        summary: "Robustness, uncertainty, adversarial ML, language-model security, privacy, fairness, governance, and risk management.",
      },
      {
        href: "ai-systems-and-infrastructure/index.html",
        tag: "Phase 24",
        title: "AI Systems And Infrastructure",
        summary: "Distributed training, efficient inference, batching, KV caching, quantization, serving, monitoring, deployment, and LLMOps.",
      },
      {
        href: "research-methodology/index.html",
        tag: "Phase 25",
        title: "Research Methodology",
        summary: "Literature search, equations, assumptions, contributions, baselines, ablations, seeds, uncertainty, and reproducibility.",
      },
      {
        href: "logical-and-problem-solving-patterns/index.html",
        tag: "Phase 26",
        title: "Logical And Problem-Solving Patterns To Recognize",
        summary: "Reasoning, algorithmic, foundation-model, and scientific patterns that recur across AI.",
      },
      {
        href: "representative-research-paper-sequence/index.html",
        tag: "Phase 27",
        title: "Representative Research-Paper Sequence",
        summary: "A curated backbone of papers across foundations, language models, vision, generation, RL, graphs, sequence models, and interpretability.",
      },
    ],
    topicCards: [
      {
        href: "mathematical-foundations/linear-algebra/index.html",
        tag: "Mathematical Foundations",
        title: "Linear Algebra",
        summary: "Learn vectors, matrices, norms, eigendecomposition, SVD, and the math behind AI models.",
      },
      {
        href: "mathematical-foundations/calculus-and-matrix-calculus/index.html",
        tag: "Mathematical Foundations",
        title: "Calculus And Matrix Calculus",
        summary: "Learn derivatives, gradients, Jacobians, Hessians, Taylor approximations, and automatic differentiation.",
      },
      {
        href: "mathematical-foundations/probability/index.html",
        tag: "Mathematical Foundations",
        title: "Probability",
        summary: "Understand uncertainty, Bayes' theorem, expectation, variance, common distributions, and sampling.",
      },
      {
        href: "mathematical-foundations/statistics/index.html",
        tag: "Mathematical Foundations",
        title: "Statistics",
        summary: "Learn estimation, hypothesis testing, confidence intervals, calibration, and distribution shift.",
      },
      {
        href: "mathematical-foundations/optimization/index.html",
        tag: "Mathematical Foundations",
        title: "Optimization",
        summary: "Learn objectives, losses, gradient descent, stochastic optimization, regularization, and constraints.",
      },
      {
        href: "mathematical-foundations/information-theory/index.html",
        tag: "Mathematical Foundations",
        title: "Information Theory",
        summary: "Learn entropy, cross-entropy, KL divergence, mutual information, perplexity, and information bottlenecks.",
      },
      {
        href: "mathematical-foundations/discrete-mathematics-theoretical-computer-science/index.html",
        tag: "Mathematical Foundations",
        title: "Discrete Mathematics And Theoretical Computer Science",
        summary: "Study sets, graphs, proofs, automata, computability, complexity, and algorithms for AI systems.",
      },
      {
        href: "programming-and-systems-foundations/index.html",
        tag: "Phase 2",
        title: "Programming And Systems Foundations",
        summary: "Learn the implementation layer behind reliable, efficient AI model code.",
      },
      {
        href: "classical-artificial-intelligence/index.html",
        tag: "Phase 3",
        title: "Classical Artificial Intelligence",
        summary: "Learn search algorithms, heuristics, state-space reasoning, completeness, and optimality.",
      },
      {
        href: "probabilistic-ai/index.html",
        tag: "Phase 4",
        title: "Probabilistic AI",
        summary: "Learn probabilistic graphical models, inference, HMMs, and filtering methods.",
      },
      {
        href: "foundations/what-is-ai/index.html",
        tag: "Foundations",
        title: "What Is AI?",
        summary: "Understand AI as software that recognizes patterns, makes predictions, or generates useful outputs.",
      },
      {
        href: "machine-learning/training-a-model/index.html",
        tag: "Machine Learning",
        title: "Training A Model",
        summary: "Learn how examples, labels, loss, and feedback help a model improve.",
      },
      {
        href: "deep-learning/neural-networks/index.html",
        tag: "Deep Learning",
        title: "Neural Networks",
        summary: "See how layers transform information into predictions.",
      },
      {
        href: "generative-ai/transformers/index.html",
        tag: "Generative AI",
        title: "Transformers",
        summary: "Learn why attention makes modern language models powerful.",
      },
      {
        href: "ai-systems/agents-and-tools/index.html",
        tag: "AI Systems",
        title: "Agents And Tools",
        summary: "Connect model output to actions, APIs, files, and workflows.",
      },
      {
        href: "portfolio/ai-projects/index.html",
        tag: "Portfolio",
        title: "AI Projects",
        summary: "Turn lessons into visible work that proves understanding.",
      },
      {
        href: "graph-machine-learning/index.html",
        tag: "Phase 20",
        title: "Graph Machine Learning",
        summary: "Learn graph terminology, adjacency and Laplacian matrices, spectral graph theory, random walks, PageRank, graph embeddings, GNNs, knowledge graphs, link prediction, and graph-based retrieval.",
      },
      {
        href: "causal-inference/index.html",
        tag: "Phase 21",
        title: "Causal Inference",
        summary: "Learn DAGs, structural causal models, confounding, colliders, mediators, interventions, do-calculus, counterfactuals, treatment effects, propensity scores, doubly robust estimation, natural experiments, and causal discovery.",
      },
      {
        href: "interpretability-and-mechanistic-understanding/index.html",
        tag: "Phase 22",
        title: "Interpretability And Mechanistic Understanding",
        summary: "Learn permutation importance, PDPs, ICE, LIME, SHAP, counterfactuals, saliency maps, integrated gradients, Grad-CAM, probes, activation patching, causal tracing, circuit analysis, sparse autoencoders, and model editing.",
      },
      {
        href: "ai-safety-security-privacy-and-governance/index.html",
        tag: "Phase 23",
        title: "AI Safety, Security, Privacy And Governance",
        summary: "Learn distribution shift, uncertainty, conformal prediction, adversarial examples, data poisoning, agent security, privacy-preserving learning, fairness metrics, model cards, risk assessments, incident response, accountability, transparency, and governance workflows.",
      },
      {
        href: "ai-systems-and-infrastructure/index.html",
        tag: "Phase 24",
        title: "AI Systems And Infrastructure",
        summary: "Learn data, tensor, pipeline, sequence, context and expert parallelism, ZeRO and FSDP, collectives, GPU topology, efficient inference, KV caching, quantization, scheduling, performance metrics, MLOps, LLMOps, deployment strategies, monitoring, rollback, and incident management.",
      },
      {
        href: "research-methodology/index.html",
        tag: "Phase 25",
        title: "Research Methodology",
        summary: "Learn how to search literature, read equations, reconstruct assumptions, identify contributions, reproduce baselines, design ablations, control seeds, report uncertainty, avoid contamination, analyze errors, test significance, document negative results, and separate exploratory from confirmatory experiments.",
      },
      {
        href: "logical-and-problem-solving-patterns/index.html",
        tag: "Phase 26",
        title: "Logical And Problem-Solving Patterns To Recognize",
        summary: "Learn deduction, induction, abduction, Bayesian updating, causal and counterfactual reasoning, dynamic programming, greedy search, sampling, ensembles, retrieve-then-generate, decompose-then-solve, generate-then-verify, tool use, evidence grounding, ablations, and falsification.",
      },
      {
        href: "representative-research-paper-sequence/index.html",
        tag: "Phase 27",
        title: "Representative Research-Paper Sequence",
        summary: "Read a curated paper backbone from the Perceptron and backpropagation through SVMs, random forests, ImageNet, ResNet, word2vec, seq2seq, attention, BERT, GPT-3, Chinchilla, FlashAttention, RAG, DPO, ReAct, Toolformer, CLIP, ViT, diffusion, RL, GNNs, S4, Mamba, and mechanistic interpretability.",
      },
    ],
    phaseTopicCards: {
      "foundations": [
        {
          href: "what-is-ai/index.html",
          tag: "Foundations",
          title: "What Is AI?",
          summary: "Understand AI as software that recognizes patterns, makes predictions, or generates useful outputs.",
        },
      ],
      "mathematical-foundations": [
        {
          href: "linear-algebra/index.html",
          tag: "1.1",
          title: "Linear Algebra",
          summary: "Vectors, matrices, norms, eigendecomposition, SVD, and high-dimensional geometry.",
        },
        {
          href: "calculus-and-matrix-calculus/index.html",
          tag: "1.2",
          title: "Calculus And Matrix Calculus",
          summary: "Limits, derivatives, gradients, Jacobians, Hessians, Taylor approximations, and autodiff.",
        },
        {
          href: "probability/index.html",
          tag: "1.3",
          title: "Probability",
          summary: "Sample spaces, conditional probability, Bayes' theorem, expectation, variance, distributions, and sampling.",
        },
        {
          href: "statistics/index.html",
          tag: "1.4",
          title: "Statistics",
          summary: "Populations, samples, estimation, hypothesis testing, confidence intervals, calibration, and distribution shift.",
        },
        {
          href: "optimization/index.html",
          tag: "1.5",
          title: "Optimization",
          summary: "Objectives, losses, gradient descent, stochastic optimization, regularization, and constraints.",
        },
        {
          href: "information-theory/index.html",
          tag: "1.6",
          title: "Information Theory",
          summary: "Entropy, cross-entropy, KL divergence, mutual information, coding, perplexity, and bottlenecks.",
        },
        {
          href: "discrete-mathematics-theoretical-computer-science/index.html",
          tag: "1.7",
          title: "Discrete Mathematics And Theoretical Computer Science",
          summary: "Sets, graphs, proofs, automata, computability, complexity, and algorithms.",
        },
      ],
      "portfolio": [
        {
          href: "ai-projects/index.html",
          tag: "Portfolio",
          title: "AI Projects",
          summary: "Turn lessons into visible work that proves understanding.",
        },
      ],
    },
  };
})();
