(function () {
  const groups = {
    graphical: {
      label: "4.1 Probabilistic graphical models",
      input: "random variables, their domains, graph structure, and local probability factors",
      stages: ["Represent variables", "Factorize distribution", "Condition on evidence", "Answer query"],
      value: "Graphical models expose how a large joint distribution is assembled from local relationships.",
      pitfalls: [
        "A graph encodes particular independence assumptions; it is not merely a visualization.",
        "Check normalization, support, and conditioning events before interpreting a probability.",
      ],
    },
    algorithms: {
      label: "4.1 Inference and learning algorithms",
      input: "a probabilistic model, observed evidence, hidden variables, and a target query or objective",
      stages: ["Specify target", "Form local updates", "Run computation", "Check approximation"],
      value: "Inference algorithms convert a probability model into posterior beliefs, predictions, or learned parameters.",
      pitfalls: [
        "Convergence of an algorithm does not automatically imply an exact or well-calibrated posterior.",
        "Report approximation error, effective sample size, or another diagnostic appropriate to the method.",
      ],
    },
    sequential: {
      label: "4.2 Sequential models and state estimation",
      input: "a transition model, observation model, prior state belief, and a sequence of observations",
      stages: ["Predict state", "Observe signal", "Update belief", "Advance time"],
      value: "Sequential models maintain uncertainty about a changing hidden state behind noisy observations.",
      pitfalls: [
        "Filtering, smoothing, prediction, and most-likely-path decoding answer different questions.",
        "State estimates become overconfident when process or observation noise is underestimated.",
      ],
    },
  };

  function topic(id, group, title, summary, mechanism, tradeoff, expression, setup, result, url, question, answer, caution = "") {
    const context = groups[group];
    const nodes = context.stages.map((label, index) => ({
      label,
      detail: [context.input, mechanism, tradeoff, result][index],
    }));

    return {
      id,
      group,
      groupLabel: context.label,
      title,
      summary,
      simpleIdea: [summary, mechanism],
      diagram: { nodes, caption: `${title} turns explicit uncertainty assumptions into a checkable probabilistic result.` },
      concepts: [
        { title: "Model and assumptions", explanation: `It starts from ${context.input}.` },
        { title: "Core computation", explanation: mechanism },
        { title: "Guarantee or tradeoff", explanation: tradeoff },
      ],
      process: [
        `Write the relevant quantities explicitly using ${context.input}.`,
        `Apply the central computation: ${mechanism}`,
        "Track normalization, numerical stability, convergence, or approximation quality during the computation.",
        `Interpret the result under this limitation: ${tradeoff}`,
      ],
      formulas: [{ label: `${title} rule`, expression, meaning: tradeoff }],
      example: {
        title: `${title} in a small case`,
        setup,
        steps: [
          "List the observed variables, hidden quantities, and probability assumptions.",
          `Apply the rule: ${mechanism}`,
          "Normalize or validate the result, then compare it with the stated query.",
        ],
        result,
      },
      whyItMatters: [context.value, `${title} is useful when this tradeoff is acceptable: ${tradeoff}`],
      pitfalls: [caution || `Do not use ${title} without checking that its assumptions match the data-generating process.`, ...context.pitfalls],
      practice: { question, answer },
      takeaways: [summary, mechanism, tradeoff, result],
      resources: [{ label: `External reference: ${title}`, url }],
    };
  }

  const rawTopics = [
    topic("bayesian-networks", "graphical", "Bayesian networks", "A Bayesian network is a directed acyclic graph whose arrows encode conditional dependence and whose local tables define a joint distribution.", "Multiply one conditional probability for each node given its parents.", "The factorization is compact and supports causal interpretations only when the arrows and assumptions are causally justified.", "P(x_1,...,x_n) = product_i P(x_i | parents(x_i))", "Model rain, a sprinkler, wet grass, and slippery pavement with directed dependencies.", "Evidence that the grass is wet updates the posterior probabilities of rain and sprinkler use.", "https://en.wikipedia.org/wiki/Bayesian_network", "What mathematical object prevents directed cycles in a Bayesian network?", "The graph must be a directed acyclic graph, or DAG.", "An arrow may encode dependence without proving real-world causation."),
    topic("markov-random-fields", "graphical", "Markov random fields", "A Markov random field is an undirected graph that represents local compatibility relationships between random variables.", "Multiply nonnegative clique potentials and divide by the partition function to obtain probabilities.", "Undirected factors express symmetric relationships naturally, but computing the partition function can be intractable.", "P(x) = (1/Z) product_c psi_c(x_c)", "Represent neighboring pixels whose labels prefer to agree while each pixel also follows its observed intensity.", "The posterior balances local image evidence against smoothness between neighboring labels.", "https://en.wikipedia.org/wiki/Markov_random_field", "What does the partition function Z do?", "It normalizes the product of potentials so the probabilities sum or integrate to one.", "Potentials are compatibility scores, not probabilities unless the complete model is normalized."),
    topic("factor-graphs", "graphical", "Factor graphs", "A factor graph is a bipartite graph with variable nodes and factor nodes that makes a distribution's factorization explicit.", "Connect each factor to exactly the variables in its scope, then perform local message passing along those edges.", "The representation makes reusable inference rules clear, though cycles can make message passing approximate.", "p(x) proportional product_a f_a(x_a)", "Express an error-correcting code with bit variables and parity-check factors.", "Messages combine channel evidence with parity constraints to estimate each transmitted bit.", "https://en.wikipedia.org/wiki/Factor_graph", "Why is a factor graph bipartite?", "Edges connect variables to factors, never variable-to-variable or factor-to-factor.", "A factor graph and a Bayesian network can represent related distributions but encode structure differently."),
    topic("conditional-random-fields", "graphical", "Conditional random fields", "A conditional random field models a structured output directly conditional on observed input features.", "Score compatible output configurations with feature-weighted factors and normalize over possible output structures for the given input.", "CRFs avoid modelling the input distribution, but training and decoding can be expensive for complex output graphs.", "P(y|x) = exp(w dot F(x,y)) / Z(x)", "Label every word in a sentence as a person, organization, location, or other category.", "The model combines word features and neighboring tag compatibility to return a coherent tag sequence.", "https://en.wikipedia.org/wiki/Conditional_random_field", "What distribution does a CRF model?", "It models the conditional distribution P(y|x) of structured outputs given inputs.", "Feature weights are not independent probabilities; the conditional partition function couples them."),
    topic("conditional-independence", "graphical", "Conditional independence", "Conditional independence states that two variables provide no additional information about one another once a third set is known.", "Test whether the conditional joint factorizes into the product of conditional marginals.", "It enables compact models and efficient inference, but the statement always depends on the conditioning set.", "X independent of Y given Z iff P(X,Y|Z)=P(X|Z)P(Y|Z)", "Suppose two diagnostic tests share only an underlying disease cause.", "Once disease status is known, one test result may add no information about the other under the model.", "https://en.wikipedia.org/wiki/Conditional_independence", "Can two marginally dependent variables become independent after conditioning?", "Yes. Conditioning can explain their shared dependence, though conditioning can also create dependence in collider structures.", "Never omit the conditioning variables when stating an independence claim."),
    topic("d-separation", "graphical", "D-separation", "D-separation is a graphical criterion for deciding conditional independence in a Bayesian network.", "Inspect every path between variable sets and determine whether conditioning blocks chains and forks or opens colliders and their descendants.", "A blocked set of paths implies independence for every distribution faithful to the graph factorization; it does not measure dependence strength.", "X d-separated from Y by Z => X independent of Y given Z", "Analyze the collider Rain -> WetGrass <- Sprinkler.", "Rain and Sprinkler are independent through this path until WetGrass or its descendant is conditioned on.", "https://en.wikipedia.org/wiki/D-separation", "Why can conditioning on a collider create dependence?", "Knowing the shared effect makes one possible cause informative about the other, a pattern called explaining away.", "Path rules differ for colliders versus chains and forks; applying one blocking rule to all three is incorrect."),
    topic("exact-inference", "graphical", "Exact inference", "Exact inference computes a posterior, marginal, likelihood, or most-probable assignment without approximation error.", "Rearrange sums and products using graph structure, eliminating hidden variables while preserving the exact query.", "The answer is exact up to numeric precision, but time and memory often grow exponentially with graph treewidth.", "P(Q|e) = alpha sum_h product_a f_a(Q,h,e)", "Compute a disease posterior in a small Bayesian network after observing two symptoms.", "Summing all compatible hidden assignments yields the normalized posterior exactly.", "https://en.wikipedia.org/wiki/Exact_inference", "What structural quantity often controls exact graphical-model inference cost?", "Treewidth, together with variable domain sizes, controls the size of intermediate factors.", "Exact does not mean cheap, and floating-point underflow still needs stable implementation."),
    topic("approximate-inference", "graphical", "Approximate inference", "Approximate inference estimates a hard posterior or expectation when exact computation is too expensive.", "Use sampling, optimization, or approximate message passing to construct a tractable estimate and quantify its quality.", "It scales to larger models but introduces bias, variance, convergence questions, or all three.", "E_p[f(X)] approximately (1/N) sum_i f(x_i)", "Estimate a posterior risk probability in a dense network using Monte Carlo samples.", "The sample fraction converges toward the desired probability while retaining measurable uncertainty.", "https://en.wikipedia.org/wiki/Approximate_inference", "What two error sources commonly distinguish approximate estimators?", "Bias is systematic displacement and variance is sampling or run-to-run variability.", "A precise-looking decimal is not evidence of accuracy without convergence or error diagnostics."),

    topic("variable-elimination", "algorithms", "Variable elimination", "Variable elimination answers a query by summing out hidden variables while multiplying only the factors that currently mention them.", "Choose an elimination order, multiply factors containing the next variable, sum that variable out, and insert the resulting factor.", "It is exact, but a poor elimination order can create very large intermediate factors.", "tau_new(S) = sum_X product_{f containing X} f(X,S)", "Find P(Burglary|Alarm=true) without enumerating every full assignment separately.", "Eliminating unrelated hidden variables produces a small final factor over Burglary that is normalized into the posterior.", "https://en.wikipedia.org/wiki/Variable_elimination", "Why does elimination order matter?", "It changes the scopes of intermediate factors and therefore time and memory, even though the final exact answer is unchanged.", "Do not sum out the query variables or observed evidence."),
    topic("sum-product-algorithm", "algorithms", "Sum-product algorithm", "The sum-product algorithm passes local messages on a factor graph to compute marginal distributions.", "A variable sends products of incoming messages; a factor sends a sum over its other variables of the factor times their messages.", "It is exact on trees and often efficient, while cyclic graphs require loopy approximations.", "m_{f->x}(x)=sum_{x_f\\x} f(x_f) product_{y in N(f)\\x} m_{y->f}(y)", "Infer bit marginals in a tree-shaped parity-check factor graph.", "Multiplying incoming messages at each bit yields its normalized posterior belief.", "https://en.wikipedia.org/wiki/Sum%E2%80%93product_algorithm", "What operation distinguishes sum-product from max-product?", "Sum-product sums over eliminated states to obtain marginals; max-product maximizes to seek a most likely assignment.", "Normalize messages when useful for numerical stability, but retain their relative values."),
    topic("max-product-algorithm", "algorithms", "Max-product algorithm", "The max-product algorithm replaces summation in message passing with maximization to seek a maximum a posteriori configuration.", "Send factor messages by maximizing the factor-weighted incoming product over neighboring variables not receiving the message.", "It is exact for tree-structured MAP problems, but backpointers are needed to reconstruct a joint assignment.", "m_{f->x}(x)=max_{x_f\\x} f(x_f) product m_{y->f}(y)", "Choose the most probable hidden label sequence in a tree-structured model.", "Backtracking through stored maximizing states returns the coherent MAP assignment rather than separate marginal modes.", "https://en.wikipedia.org/wiki/Max-product_algorithm", "Why can selecting each variable's marginal mode fail to produce the joint MAP assignment?", "The individually most probable values may be mutually incompatible or have low joint probability.", "Use log space to replace unstable products with sums and retain argmax backpointers."),
    topic("belief-propagation", "algorithms", "Belief propagation", "Belief propagation is the message-passing framework that combines neighboring evidence into local beliefs.", "Alternate variable-to-factor and factor-to-variable updates until tree messages are complete or a stopping rule is reached.", "On trees it gives exact marginals; performance on general graphs depends on topology and update behavior.", "b_i(x_i) proportional product_{f in N(i)} m_{f->i}(x_i)", "Estimate component-failure probabilities in a tree-structured diagnostic network.", "Each component belief combines all evidence arriving through its incident factors without double-counting on the tree.", "https://en.wikipedia.org/wiki/Belief_propagation", "What is a belief in belief propagation?", "It is a normalized local marginal estimate formed from the product of incoming messages.", "A message should exclude information arriving from the recipient edge to avoid immediate double-counting."),
    topic("loopy-belief-propagation", "algorithms", "Loopy belief propagation", "Loopy belief propagation applies ordinary belief-propagation updates to graphs that contain cycles.", "Initialize messages, repeatedly update them around cycles, and stop by a convergence, iteration, or residual threshold.", "It can be remarkably accurate but may oscillate, fail to converge, or converge to approximate beliefs without a universal guarantee.", "m^{t+1} = BP_update(m^t)", "Estimate pixel labels on a grid-shaped image model with many four-neighbor cycles.", "Damped message updates produce smooth approximate marginals when the iteration stabilizes.", "https://en.wikipedia.org/wiki/Belief_propagation", "What does damping do in loopy belief propagation?", "It mixes a new message with its previous value to reduce oscillation and improve stability.", "Always report the update schedule, damping, stopping rule, and whether convergence occurred."),
    topic("junction-tree-algorithm", "algorithms", "Junction-tree algorithm", "The junction-tree algorithm transforms a graph into a tree of overlapping variable clusters for exact inference.", "Moralize when needed, triangulate, form maximal cliques, arrange them with the running-intersection property, then pass clique messages.", "It is exact, but the largest clique makes cost exponential in graph treewidth.", "cost approximately O(K^(treewidth+1))", "Convert a small cyclic medical network into a clique tree and condition on a test result.", "Calibrated clique potentials agree on separators and yield exact queried marginals.", "https://en.wikipedia.org/wiki/Junction_tree_algorithm", "What is the running-intersection property?", "Every cluster containing a variable must form a connected subtree of the junction tree.", "Triangulation choices change clique sizes and can determine whether the method is feasible."),
    topic("expectation-maximization", "algorithms", "Expectation-maximization", "Expectation-maximization estimates parameters when data contain latent or missing variables.", "The E-step computes an expected complete-data log likelihood under current parameters; the M-step maximizes that expectation.", "Each exact iteration does not decrease likelihood, but EM can settle at a local optimum and is sensitive to initialization.", "Q(theta|theta_old)=E_{Z|X,theta_old}[log p(X,Z|theta)]; theta_new=argmax Q", "Fit a two-component Gaussian mixture without observed component labels.", "Responsibilities from the E-step become weights for updated means, variances, and mixture proportions in the M-step.", "https://en.wikipedia.org/wiki/Expectation%E2%80%93maximization_algorithm", "Why is EM not guaranteed to find the global maximum?", "Its monotonic improvement is local, and non-convex likelihoods can contain multiple stationary points.", "Use multiple initializations and monitor likelihood rather than only parameter movement."),
    topic("variational-inference", "algorithms", "Variational inference", "Variational inference approximates an intractable posterior with a distribution from a tractable family.", "Choose q(z), optimize its parameters to maximize the evidence lower bound, and use q for posterior expectations.", "Optimization is often faster than sampling but the chosen family can introduce systematic approximation bias.", "ELBO(q)=E_q[log p(x,z)]-E_q[log q(z)] = log p(x)-KL(q||p)", "Approximate a hierarchical model posterior with a mean-field Gaussian family.", "Maximizing the ELBO returns tractable factorized posterior parameters and a lower bound on log evidence.", "https://en.wikipedia.org/wiki/Variational_Bayesian_methods", "Why is the ELBO a lower bound on log evidence?", "It equals log evidence minus KL(q||posterior), and KL divergence is nonnegative.", "A rising ELBO shows optimization progress, not that the variational family can represent the true posterior well."),
    topic("gibbs-sampling", "algorithms", "Gibbs sampling", "Gibbs sampling constructs a Markov chain by repeatedly sampling each variable from its conditional distribution given all others.", "Cycle or scan through variables, draw from each full conditional, discard warm-up, and estimate expectations from later draws.", "It avoids a rejection step, but strong posterior correlations can cause slow mixing and highly dependent samples.", "x_i^(t+1) ~ p(x_i | x_{-i})", "Sample means and variances from a Bayesian normal model using their conjugate full conditionals.", "After convergence, retained draws approximate the joint posterior despite changing one block at a time.", "https://en.wikipedia.org/wiki/Gibbs_sampling", "Why are successive Gibbs samples usually not independent?", "Each update conditions on the current values of other variables, so the chain retains temporal dependence.", "Inspect trace plots and effective sample size; sample count alone can exaggerate information."),
    topic("metropolis-hastings", "algorithms", "Metropolis-Hastings", "Metropolis-Hastings samples from a target distribution by proposing moves and probabilistically accepting or rejecting them.", "Draw y from q(y|x), accept with the target-and-proposal density ratio capped at one, otherwise repeat x.", "It needs only an unnormalized target density, but proposal scale strongly affects mixing and acceptance.", "alpha(x,y)=min(1, [pi(y)q(x|y)]/[pi(x)q(y|x)])", "Estimate a one-dimensional posterior with a Gaussian random-walk proposal.", "Accepted and repeated states form a chain whose stationary distribution is the desired posterior.", "https://en.wikipedia.org/wiki/Metropolis%E2%80%93Hastings_algorithm", "Why does the acceptance ratio include proposal probabilities?", "It corrects asymmetric proposals so detailed balance still preserves the target distribution.", "A high acceptance rate can still indicate tiny moves and poor exploration."),
    topic("hamiltonian-monte-carlo", "algorithms", "Hamiltonian Monte Carlo", "Hamiltonian Monte Carlo uses gradients and simulated dynamics to propose distant moves through continuous probability distributions.", "Add momentum, integrate approximate Hamiltonian dynamics with leapfrog steps, then apply a Metropolis correction.", "It reduces random-walk behavior in smooth high-dimensional targets but requires gradients and careful step-size and trajectory tuning.", "H(q,p)=-log pi(q) + (1/2)p^T M^(-1)p", "Sample correlated coefficients from a Bayesian logistic-regression posterior.", "Gradient-guided trajectories travel along the posterior geometry while the correction removes integration bias.", "https://en.wikipedia.org/wiki/Hamiltonian_Monte_Carlo", "What does the Metropolis correction fix?", "It corrects numerical energy error introduced by the finite-step integrator, preserving the target distribution.", "Divergent transitions often reveal poor scaling, extreme curvature, or an unsuitable step size."),
    topic("sequential-monte-carlo", "algorithms", "Sequential Monte Carlo", "Sequential Monte Carlo represents an evolving distribution with weighted particles that are propagated, reweighted, and resampled.", "Sample particles from a proposal, multiply weights by the target-to-proposal increment, normalize, and resample when weights degenerate.", "It handles nonlinear and non-Gaussian sequences, but particle requirements grow with dimension and unlikely observations can collapse weights.", "w_t^i proportional w_{t-1}^i p(y_t|x_t^i)p(x_t^i|x_{t-1}^i)/q(x_t^i|x_{t-1}^i,y_t)", "Track multiple possible robot locations as sensor readings arrive.", "The weighted particle cloud approximates the filtering distribution at each time step.", "https://en.wikipedia.org/wiki/Particle_filter", "What problem does resampling address?", "It removes many negligible-weight particles and replicates high-weight particles when effective sample size becomes small.", "Resampling too often can destroy diversity; resampling too late wastes computation on dead particles."),

    topic("markov-chains", "sequential", "Markov chains", "A Markov chain models a sequence whose next-state distribution depends only on the current state.", "Multiply an initial distribution by a transition matrix repeatedly or sample each next state from its current-state row.", "The Markov property makes analysis tractable, but real histories may contain information that the selected state omits.", "P(X_(t+1)=j | X_t=i, history)=T_ij", "Model daily weather as sunny, cloudy, or rainy with a three-by-three transition matrix.", "Matrix powers give future state probabilities and simulation produces possible weather sequences.", "https://en.wikipedia.org/wiki/Markov_chain", "What must each row of a finite transition matrix sum to?", "One, because it is a conditional probability distribution over the next state.", "A process can look non-Markovian when the state representation leaves out relevant memory."),
    topic("hidden-markov-models", "sequential", "Hidden Markov models", "A hidden Markov model has a Markov sequence of latent states that probabilistically emits observable data.", "Combine a transition probability between hidden states with an emission likelihood for each observation.", "HMM algorithms are efficient, but the discrete state and conditional-independence assumptions may be too restrictive.", "P(z_1:T,x_1:T)=P(z_1) product_t P(x_t|z_t) product_{t=2}^T P(z_t|z_(t-1))", "Infer whether a machine is healthy or failing from a sequence of noisy vibration categories.", "The posterior assigns a probability to each hidden condition at each time rather than trusting an observation directly.", "https://en.wikipedia.org/wiki/Hidden_Markov_model", "Which variables are observed in a standard HMM?", "The emissions are observed; the state sequence is latent and must be inferred.", "Label switching and weakly separated emissions can make learned hidden states hard to interpret."),
    topic("forward-backward-algorithm", "sequential", "Forward-backward algorithm", "The forward-backward algorithm computes every HMM state's smoothed probability using evidence before and after that time.", "Pass forward messages from the start, backward messages from the end, multiply them at each time, and normalize.", "It gives exact HMM marginals in linear sequence length, while requiring the complete observation sequence for smoothing.", "P(z_t|x_1:T) proportional alpha_t(z_t) beta_t(z_t)", "Re-estimate a machine's condition on day three after observing its full seven-day sensor record.", "Future observations correct the day-three belief that a forward-only filter produced.", "https://en.wikipedia.org/wiki/Forward%E2%80%93backward_algorithm", "How does smoothing differ from filtering?", "Filtering uses observations through time t; smoothing also uses observations after t.", "Scale or normalize messages at each step to prevent numeric underflow on long sequences."),
    topic("viterbi-decoding", "sequential", "Viterbi decoding", "Viterbi decoding finds the single most probable hidden-state sequence in an HMM.", "For each state and time retain the best predecessor score and backpointer, then trace backward from the best final state.", "Dynamic programming avoids enumerating all paths, but the MAP path is not the same as choosing each time's marginally most probable state.", "delta_t(j)=P(x_t|j) max_i [delta_(t-1)(i) T_ij]", "Decode the most likely part-of-speech tag sequence for a sentence.", "Backtracking returns one globally coherent tag path that respects transition and emission probabilities.", "https://en.wikipedia.org/wiki/Viterbi_algorithm", "Why are backpointers required?", "The maximum score alone gives the final probability; backpointers reconstruct which predecessor choices formed the optimal path.", "Use log probabilities so long products become stable sums."),
    topic("kalman-filter", "sequential", "Kalman filter", "The Kalman filter maintains the exact Gaussian belief for a linear dynamical system with Gaussian noise.", "Predict mean and covariance through the dynamics, compute the innovation, then correct them with the Kalman gain.", "It is fast and optimal under its assumptions, but nonlinear dynamics or non-Gaussian uncertainty require other methods.", "K_t=P^-_t H^T(H P^-_t H^T+R)^(-1); m_t=m^-_t+K_t(y_t-Hm^-_t)", "Track a vehicle's position and velocity from noisy GPS measurements.", "Each update balances the predicted trajectory against measurement uncertainty to produce a posterior state and covariance.", "https://en.wikipedia.org/wiki/Kalman_filter", "What determines whether the filter trusts the prediction or measurement more?", "The relative predicted and measurement covariances determine the Kalman gain.", "A covariance update bug can make the filter appear confident while diverging from reality."),
    topic("extended-kalman-filter", "sequential", "Extended Kalman filter", "The extended Kalman filter adapts Kalman updates to nonlinear models by linearizing them near the current estimate.", "Evaluate Jacobians of the transition and observation functions, then use them in the covariance prediction and correction.", "It is efficient for mild nonlinearity, but a poor local linearization can produce bias, inconsistency, or divergence.", "F_t = partial f/partial x at m_(t-1); H_t = partial h/partial x at m^-_t", "Track a robot whose sensor reports nonlinear range and bearing to a landmark.", "Jacobian-based updates approximate the posterior with a Gaussian around the current trajectory estimate.", "https://en.wikipedia.org/wiki/Extended_Kalman_filter", "Why can a bad initial estimate harm an EKF?", "The Jacobian is local, so linearizing far from the true state can misrepresent both the mean update and uncertainty.", "Verify analytic Jacobians numerically and keep angle residuals properly wrapped."),
    topic("unscented-kalman-filter", "sequential", "Unscented Kalman filter", "The unscented Kalman filter propagates carefully selected sigma points through nonlinear functions instead of linearizing with derivatives.", "Construct weighted sigma points matching the current Gaussian moments, transform them, then recombine their weighted mean and covariance.", "It often captures nonlinear moment changes better than an EKF without Jacobians, but still represents the posterior as Gaussian.", "chi_0=m; chi_i=m +/- [sqrt((n+lambda)P)]_i", "Estimate a target's location from a nonlinear distance sensor without deriving measurement Jacobians.", "Transformed sigma points approximate the posterior mean and covariance after the observation.", "https://en.wikipedia.org/wiki/Kalman_filter#Unscented_Kalman_filter", "Are sigma points Monte Carlo samples?", "No. They are deterministically chosen and weighted to reproduce selected moments of the Gaussian belief.", "Scaling parameters can generate unstable covariance weights when chosen carelessly."),
    topic("particle-filter", "sequential", "Particle filter", "A particle filter is a Sequential Monte Carlo method specialized to online hidden-state filtering.", "Propagate each particle through the state transition, weight it by the newest observation likelihood, normalize, and resample when needed.", "It represents multimodal and non-Gaussian beliefs, but finite particles can lose important modes or collapse in high dimensions.", "p(x_t|y_1:t) approximately sum_i w_t^i delta(x_t-x_t^i)", "Localize a robot that might be in either of two similar corridors.", "The particle cloud retains both location hypotheses until later observations shift weight toward one corridor.", "https://en.wikipedia.org/wiki/Particle_filter", "What does a weighted particle cloud approximate?", "It approximates the filtering distribution over the current hidden state given observations so far.", "Injecting noise is not a substitute for a principled proposal and resampling strategy."),
    topic("dynamic-bayesian-networks", "sequential", "Dynamic Bayesian networks", "A dynamic Bayesian network repeats a directed graphical-model template across time slices.", "Specify within-slice and between-slice dependencies, unroll the template for the sequence, and apply filtering, smoothing, or learning.", "DBNs express richer temporal structure than a basic HMM, but inference cost grows with the slice graph's coupled state width.", "P(X_1:T)=P(X_1) product_{t=2}^T product_i P(X_t^i | parents(X_t^i))", "Model a patient's latent disease stage, medication, symptoms, and lab measurements across visits.", "The unrolled network supports posterior beliefs over several interacting hidden and observed processes through time.", "https://en.wikipedia.org/wiki/Dynamic_Bayesian_network", "How is an HMM related to a dynamic Bayesian network?", "An HMM is a simple DBN with one discrete hidden state and one observation variable per time slice.", "Make stationarity assumptions explicit when reusing the same transition template at every time step."),
  ];

  const topics = rawTopics.map((item, index) => ({
    ...item,
    previousId: rawTopics[index - 1]?.id || "",
    nextId: rawTopics[index + 1]?.id || "",
  }));

  window.probabilisticAiGroups = groups;
  window.probabilisticAiTopics = topics;
})();
