import { math, source, reviewed } from "./lesson-helpers.mjs";

export const computationLessons={
  [math("p-np-np-hard-and-np-complete")]:reviewed({
    title:"P, NP, NP-hard, and NP-complete",labTitle:"Check a witness; do not confuse it with finding one",
    summary:"P and NP classify decision problems by polynomial-time solving and verification. NP-hardness describes reduction-based difficulty, while NP-completeness combines hardness with membership in NP. These are properties of problem families and encodings, not labels inferred from one slow instance or a small interactive example.",
    hook:"A failed assignment rejects that witness, not the existence of every witness.",
    model:"sat-certificate",control:["Assignment mask (a=4, b=2, c=1)",0,7,1,2],
    equation:"φ=(a∨b)∧(¬a∨c)∧(¬b∨¬c); x∈L ⇔ ∃w, |w|≤p(|x|): V(x,w)=1",
    assumptions:"The three bits represent a,b,c in that order. The fixed formula has three clauses and six literal occurrences. The lab always evaluates every literal, without short-circuiting, and displays all eight assignments. Stripes mark satisfying assignments; a thick border marks the selected certificate. This formula is 2-CNF, a tractable SAT subclass. The finite gallery illustrates certificate verification, not a proof that the illustrated subclass is NP-complete or that exhaustive search is necessary.",
    takeaway:"Efficiently checking a proposed yes-certificate does not supply one. NP-complete means both in NP and NP-hard; it does not mean proven exponential time.",
    prerequisites:[math("boolean-algebra"),math("time-and-space-complexity"),math("reductions")],
    sources:[source("Cornell CS 2800: P, NP and NP-completeness","https://www.cs.cornell.edu/courses/cs2800/2015fa/lectures/lec36-np.html"),source("Clay Mathematics Institute: P versus NP","https://www.claymath.org/millennium/p-vs-np/"),source("Stephen Cook: official P versus NP problem description","https://www.claymath.org/wp-content/uploads/2022/06/pvsnp.pdf"),source("RPI: why 2-SAT is in P","https://www.cs.rpi.edu/~goldberg/14-CC/08-2sat.pdf")],
    ideas:[
      ["P concerns a complete decision procedure", "A language is in P when a deterministic algorithm returns the correct yes/no answer on every input within a polynomial in input length. The bound applies to the entire algorithm, including parsing and constructing any intermediate representation, not just the final check."],
      ["NP concerns bounded certificates", "A language is in NP when yes-instances have witnesses of polynomial length that a deterministic polynomial-time verifier accepts, and no-instances have no accepted witness. P is contained in NP: the verifier can ignore its witness and run the P algorithm. NP means nondeterministic polynomial time, not non-polynomial."],
      ["Read the certificate in the lab", "At 010, a is false, b true and c false. The three clauses evaluate to true, true, true. Six literal reads establish this assignment's validity. At 000, the first clause fails: that particular assignment is invalid, but 010 and 101 still establish satisfiability. Rejecting one witness is not a certificate that none exist."],
      ["Hard and complete are different obligations", "Under polynomial-time many-one reductions, B is NP-hard if every language in NP reduces to B. B is NP-complete when it is also in NP. NP-hard targets need not themselves be in NP or even be decidable. An optimization problem is usually called NP-hard; use its appropriately encoded decision version when asserting NP-completeness."],
      ["What the open question does—and does not—say", "Whether P=NP remains unresolved in the cited Clay problem listing. General SAT is NP-complete, but an exponential enumeration is only one available algorithm, not an exponential lower bound. The lab's 2-CNF formula admits special-purpose polynomial algorithms. Easy examples and useful practical solvers do not settle worst-case complexity for unrestricted SAT."]
    ],
    process:["Define the family of decision instances and count their encoded input length.","For NP membership, specify a polynomial-size witness and a sound polynomial-time verifier.","For NP-hardness, reduce a known NP-hard problem to the target and prove the mapping. Keep this separate from verification."],
    example:["Two valid witnesses among eight possibilities","Inspect the default assignment 010, then change the control to 000.",["For 010, a∨b=1, ¬a∨c=1, and ¬b∨¬c=1. This is a valid yes-certificate.","For 000, the first clause is false while the other two are true. Only the selected certificate fails.","The complete table finds exactly two witnesses. Eight full checks require 8×6=48 literal reads in this deliberately simple enumeration, versus six for a supplied witness."],"The measured difference belongs to these specified procedures on this example. It is not evidence that every solver must enumerate eight assignments."],
    pitfalls:["A plot that draws P strictly inside NP would assume an unproved separation. State the known inclusion without presenting the open boundary as settled.","Do not omit the polynomial bound on witness length. Efficient verification of an arbitrarily huge object does not give NP membership relative to the original input.","A failed timeout, failed heuristic or failed certificate is not a mathematical no-answer. The verification definition primarily provides evidence for yes-instances."],
    implementation:["The visual, truth table and readout share the same clause evaluator. The display labels its 2-CNF restriction so it cannot be mistaken for a hardness demonstration.","When turning a solver task into a complexity claim, document encoding, numeric precision and decision threshold. A practical benchmark and a worst-case theorem answer different questions."],
    outcomes:["Distinguish P, NP, NP-hard and NP-complete without assuming P≠NP.","Separate witness verification, instance solving and a hardness proof."]
  }),
  [math("automata-and-formal-languages")]:reviewed({
    title:"Automata and formal languages",labTitle:"Remember parity, forget the rest of the prefix",
    summary:"A formal language is a set of finite strings over an alphabet. An automaton recognizes a language by consuming a string according to transition rules. A deterministic finite automaton has a finite state set and exactly one next state for each state-symbol pair; its final state decides membership.",
    hook:"To remember whether the number of ones is even, you do not need to remember how many there were.",
    model:"parity-automaton",control:["Symbols consumed from 101101",0,6,1,3],
    equation:"Q={E,O}; Σ={0,1}; δ(q,0)=q; δ(E,1)=O; δ(O,1)=E; F={E}",
    assumptions:"The start state is E. E means an even number of ones has been read and is accepting; O means odd and is non-accepting. Reading zero stays in the current state, reading one switches states. The fixed word is 101101. The slider consumes prefixes, including the empty prefix ε. A double circle denotes an accepting state, while the thick highlighted outline and text identify the current state. Acceptance of the complete word is checked only after all its symbols are consumed.",
    takeaway:"A useful state summarizes exactly the history needed for future decisions. An accepting state does not mean execution stops before the input ends.",
    prerequisites:[math("sets-relations-and-functions"),math("mathematical-induction")],
    sources:[source("MIT 6.045J: deterministic and nondeterministic finite automata","https://ocw.mit.edu/courses/6-045j-automata-computability-and-complexity-spring-2011/a8b9bb8d5d9c1f7a6b4a85056b8dcbde_MIT6_045JS11_lec03.pdf"),source("Stanford CS103: finite memory and nonregular languages","https://web.stanford.edu/class/archive/cs/cs103/cs103.1262/lectures/18/Condensed%20Lecture%20Slides.pdf")],
    ideas:[
      ["Specify the language before the machine", "Here L consists of all binary strings with an even number of ones. The empty string belongs to L because it has zero ones. Membership depends on the whole string, not on whether some intermediate prefix once visited an accepting state. The alphabet is {0,1}; other characters are outside this input specification."],
      ["The five components form a contract", "A DFA is (Q,Σ,δ,q₀,F): states, alphabet, transition function, start state and accepting states. δ is total on Q×Σ. The two states in this lab have a transition on both symbols, including the self-loop on zero. A missing transition requires a convention or an explicit rejecting sink, not a guessed next state."],
      ["The parity invariant proves correctness", "After the empty prefix, the machine is in E and the count is even. Assume the state correctly describes a prefix. Appending zero leaves both the count's parity and state unchanged; appending one flips both. Induction on prefix length establishes that the final state accepts exactly the intended language, for every finite binary string—not only the displayed six symbols."],
      ["Two states are necessary here", "Prefixes ε and 1 cannot lead to the same state in any correct deterministic machine for this language: ending the input immediately must accept the first and reject the second. Two states suffice by the displayed construction, so this machine is minimal. It compresses infinitely many possible prefixes into two future-relevant classes."],
      ["Finite memory has an expressive boundary", "Languages recognized by finite automata are regular. Nondeterministic finite automata allow multiple possible paths but recognize the same class, not arbitrary computations. A fixed finite state set cannot remember an unbounded exact count; the parity machine succeeds because it remembers only a remainder modulo two. Do not treat every sequence model as a finite automaton with this guarantee."]
    ],
    process:["Define the accepted strings, alphabet and treatment of the empty string.","Choose state meanings and specify a total transition for every state-symbol pair.","Prove the state invariant and relate accepting states to the language after the input ends."],
    example:["A zero changes the position, not the parity","Start at the empty prefix and consume 101101 one symbol at a time.",["State trace: E → O → O → E → O → O → E.","After prefix 10, two symbols have been read but only one is a one; the state remains O.","After all six symbols, four ones have been read. The final E state accepts the word."],"The machine stores parity, not the entire prefix, its length, or its exact count of ones."],
    pitfalls:["Being in E halfway through the word only says that prefix would be accepted if input ended there. A later one can change the answer.","ε is a string of length zero, not a third input symbol in this DFA. It requires no transition.","A finite test set can find mistakes but cannot alone prove recognition of an infinite language. The invariant supplies the general argument."],
    implementation:["The lab recomputes the prefix state from the transition rule; the trace table independently exposes each prefix and its count. No timer or motion is needed to step through the run.","Use state-machine designs for lexical constraints, protocol phases and small streaming summaries. If the requirement needs richer memory, change the model instead of silently overloading a state's meaning."],
    outcomes:["Define and trace a deterministic finite automaton, including ε.","Prove that a state invariant recognizes the intended language."]
  }),
  [math("computability")]:reviewed({
    title:"Computability",labTitle:"Not finished is not the same as never finishes",
    summary:"Computability asks whether an algorithm can solve every instance of a specified problem at all, not whether it can do so quickly. A decider must halt with a correct yes/no answer on every input. A recognizer must accept every yes-instance but may run forever on a no-instance. The distinction matters whenever a simulation has not yet returned.",
    hook:"A stopwatch can witness a halt. Reaching its limit cannot witness eternity.",
    model:"bounded-execution",control:["Observation budget per program",0,12,1,5," transitions"],
    equation:"HALT={⟨M,x⟩ : M(x) halts}; not halted by B ⇏ never halts",
    assumptions:"These are three explicitly specified discrete toy programs, not arbitrary source code. A and B start with counters 3 and 9; each transition decrements a positive counter by one, and reaching zero halts. C starts at bit zero and repeatedly replaces its bit with 1−bit, with no halting branch. Budget B bounds the number of observed transitions for each run. Squares mark observed halts; open circles mark observation cutoffs. The dashed vertical marker is the budget, not a predicted halting time. C's nontermination follows separately from its known rule, not its timeout.",
    takeaway:"A bounded run answers a bounded question. Proving that no general halting decider exists does not prevent proving termination or nontermination for particular programs.",
    prerequisites:[math("proof-by-contradiction"),math("reductions"),math("automata-and-formal-languages")],
    sources:[source("Cornell CS 4820: limits of computability","https://www.cs.cornell.edu/courses/cs4820/2019sp/handouts/computability.pdf"),source("Cornell CS 2112: undecidability and the halting argument","https://www.cs.cornell.edu/courses/cs2112/2014fa/lectures/lec_undecidability/")],
    ideas:[
      ["Slow is different from impossible", "A finite exhaustive search may be prohibitively expensive yet still decide its problem. For a finite Boolean formula, enumerating every assignment eventually returns yes or no. Undecidability is stronger: no algorithm meets the specified correctness-and-termination requirement on every allowed input."],
      ["A recognizer can keep waiting", "To recognize HALT, simulate the supplied program on its input and accept when it stops. If it never stops, this recognizer never returns. Running it for a finite budget adds a third observational outcome: not yet determined. Replacing that outcome with a definitive no-answer would not make a correct general decider."],
      ["The two countdowns expose a timeout mistake", "At budget five, A has halted after three transitions while B is still running with counter four. A timeout rule that calls B nonterminating is wrong: increasing the budget to nine observes its halt. The budget limits the observer, not the underlying program's possible future."],
      ["A particular loop can still be proved infinite", "Program C has exactly two complete states, zero and one, and its only rule toggles between them. Neither is halting; every transition has a successor. Its invariant and repeated full configuration prove nontermination. Seeing only a repeated output would not suffice for an arbitrary program whose hidden memory could differ."],
      ["Why a universal halting predictor contradicts itself", "Suppose a total correct predictor H(p,x) existed. Define D(p) to loop if H(p,p) says halt, and otherwise halt. On D's own encoding d, either prediction for H(d,d) disagrees with D(d)'s constructed behavior. Thus the assumed universal predictor cannot exist. The proof quantifies over every program/input pair; the three traces merely illustrate why a timeout is weaker evidence."]
    ],
    process:["Specify the allowed program model, inputs and required answers.","Separate observed execution, an instance-specific proof, and a claim about all possible programs.","For an impossibility claim, supply a valid general argument or a reduction from a known undecidable problem; a long unsuccessful run is insufficient."],
    example:["The same timeout, different futures","Use budget five, then budget nine.",["At five, A has halted and B's counter is four. C's bit is one. The bounded observer has only one witnessed halt.","At nine, B reaches zero and halts. The earlier open endpoint becomes a square at transition nine.","C continues toggling. Its nontermination is established from its transition rule, not by extending the plotted line farther."],"Two unfinished runs need not have the same future. A finite observation can miss a later halt."],
    pitfalls:["A general impossibility theorem does not say every individual program is hard to analyze. The countdowns and two-state loop have straightforward proofs.","Distinguish repeated full machine configurations from repeated screen output, repeated instruction locations or a loop counter alone.","A real machine may crash or exhaust memory; that is not the same model as an ideal unbounded computation. State the semantics before applying a theorem."],
    implementation:["The page evaluates only bounded counters and toggles. It never executes a literal infinite loop in the browser. The chart labels observations rather than fabricating a universal classifier.","Static analyzers can use restrictions, sufficient conditions or an unknown result. State which guarantee is sacrificed when a practical tool cannot provide both universal termination and exact answers."],
    outcomes:["Distinguish decidability, recognizability and practical running time.","Explain why timeout evidence cannot decide arbitrary nontermination."]
  })
};
for(const lesson of Object.values(computationLessons))lesson.updatedAt="2026-09-30";
