import { math, reviewed, source } from "./lesson-helpers.mjs";

export const dataQualityLessons = {
  [math("experimental-design")]: reviewed({
    title: "Experimental design", labTitle: "Randomization changes what you can conclude",
    summary: "Experimental design specifies the units, interventions, allocation rule, measurements and analysis needed to answer a question. Random treatment assignment supports causal comparisons under explicit assumptions; random sampling concerns generalization to a population. Replication, blocking and measurement safeguards address different sources of uncertainty and bias.",
    hook: "Randomization balances in expectation, not by making every possible result identical.",
    model: "randomized-design", control: ["Inspect a treatment assignment", 1, 6, 1, 1],
    equation: "τ=N⁻¹Σi[Yi(1)−Yi(0)]; τ̂=Ȳtreated−Ȳcontrol; Erandomization[τ̂]=τ",
    assumptions: "Four fixed experimental units have control potential outcomes Y(0)=(2,4,8,10) and treatment potential outcomes Y(1)=(6,8,8,10), in score units. Treatment has one well-defined version, no interference, full compliance and no missing outcomes. Complete randomization assigns exactly two units to treatment, giving six equally likely assignments. A second design defines two baseline blocks {1,2} and {3,4} before assignment and randomly treats one unit per block, giving four equally likely assignments. The slider inspects an assignment; it does not implement a real random allocation. Both potential outcomes are exposed only because this is a known toy world.",
    takeaway: "The assignment design determines the comparison's reference distribution. A valid causal design, precise estimation and generalization to other units are separate achievements.",
    prerequisites: [math("populations-and-samples"), math("expectation"), math("variance-and-covariance")],
    sources: [source("Penn State STAT 502: experimental units and randomization", "https://online.stat.psu.edu/stat502/Lesson07"), source("Penn State STAT 503: blocking", "https://online.stat.psu.edu/stat503/Lesson04"), source("Miratrix, Sekhon & Yu: randomization, blocking and post-stratification", "https://www.stat.berkeley.edu/users/binyu/ps/papers2013/post-stratification13.pdf")],
    ideas: [
      ["Only one potential outcome is revealed", "For each unit, the observed value is Y=T Y(1)+(1−T)Y(0). The unit-level effect requires both potential outcomes, which an ordinary parallel experiment does not jointly reveal. Here the oracle table deliberately exposes them so the actual average effect can be compared with every assignment's observed contrast."],
      ["Chance imbalance can reverse a realized comparison", "Treating units 1 and 2 yields observed treatment mean 7 and control mean 9, a contrast of −2. Yet their effects are +4 each and the four-unit average effect is +2. Baseline imbalance explains the apparent reversal. Random assignment makes this allocation one possible chance outcome, not proof of a negative true effect."],
      ["Blocking changes the allowed assignments", "A known pre-treatment characteristic separates low-baseline units {1,2} from high-baseline units {3,4}. Treating one per block rules out putting both low or both high units into treatment. In this toy, the contrast variance drops from 20/3 to 2. The gain depends on the population and block choice; it is not a universal numerical reduction."],
      ["Replication follows the assignment unit", "If a whole machine receives a treatment, taking many repeated readings from it does not create many independently randomized machines. Blinding, stable measurement, predeclared outcomes and suitable handling of interference address problems that randomization alone does not solve. Generalizing beyond these four units requires a further sampling or transport argument."]
    ],
    process: ["Specify the causal contrast, experimental unit, treatment versions and measurement window; identify potential interference and noncompliance.", "Choose replication and a randomization scheme, using only pre-treatment information for planned blocks. Record the allocation process and analyze according to that design.", "Predeclare outcomes and analysis choices, preserve assignment and follow-up records, and report uncertainty without conflating study-sample effects with effects in a wider population."],
    example: ["Enumerate every allocation before trusting one result", "The four individual effects are (4,4,0,0), so the finite-population average is 2.", ["Treat pairs {1,2},{1,3},{1,4},{2,3},{2,4},{3,4}. Their observed mean contrasts are −2,0,2,2,4,6.", "The average of these six contrasts is 2. Their design variance around 2 is (16+4+0+0+4+16)/6=20/3.", "With one treated unit in each baseline block, only contrasts 0,2,2,4 remain. Their mean is still 2 and their variance is (4+0+0+4)/4=2."], "The design removes two extreme imbalance patterns; it does not change the units' potential outcomes or make the true effect observable in an actual single assignment."],
    pitfalls: ["Selecting the assignment that gives the most attractive result is not randomization. Nor is dropping inconvenient units after assignment a neutral change to the original design.", "Blocking on a post-treatment variable can change or bias the causal question. Planned blocking uses information available before treatment allocation.", "Randomization cannot guarantee perfect realized balance, eliminate measurement bias, prevent interference or automatically establish external validity. Four units are enough to illustrate enumeration, not a recommendation for study size."],
    implementation: ["Keep the randomization unit and analysis unit aligned. Preserve the seed or allocation record, block identifiers, treatment received and outcome availability; report departures from the intended design.", "Use an uncertainty analysis that respects blocking, clustering or repeated measurements. The displayed variances enumerate a known potential-outcome table; in a real experiment the unobserved potential outcomes prevent simply computing that oracle variance."],
    outcomes: ["Separate random assignment, random sampling and experimental replication.", "Calculate how blocking changes an assignment distribution without changing the target causal effect."]
  }),
  [math("populations-and-samples")]: reviewed({
    title: "Populations and samples", labTitle: "Six possible samples, one target population",
    summary: "A population is the set of units or generating distribution about which a claim is intended. A sample is the subset actually observed. A statistic summarizes the sample; a parameter describes the target. Inference requires a link between them, supplied by a sampling design or explicit modeling assumptions—not just by having many rows.",
    hook: "More samples from the wrong frame still describe the wrong frame.",
    model: "finite-sampling", control: ["Inspect a possible sample", 1, 6, 1, 1],
    equation: "μ=N⁻¹Σi yi; ȳ=n⁻¹Σi∈s yi; ESRS[ȳ]=μ; VarSRS(ȳ)=(1−n/N)S²/n",
    assumptions: "The finite target population has four distinct units with values (2,4,8,10) score units. Simple random sampling without replacement selects two units: all six unordered pairs are equally likely. The control selects a pair for inspection, not a random draw or an ordered collection process. A comparison design samples two units uniformly from an incomplete frame containing only (2,4,8). Both plotted distributions are exhaustive calculations. S² uses denominator N−1 for the finite population.",
    takeaway: "Sampling variation and coverage error are different. An unbiased procedure can miss in one sample; a systematically incomplete frame can miss even when measured perfectly.",
    prerequisites: [math("expectation"), math("variance-and-covariance")],
    sources: [source("Penn State STAT 506: population mean and sampling designs", "https://online.stat.psu.edu/stat506/Lesson01"), source("Penn State STAT 506: nonsampling error and nonresponse", "https://online.stat.psu.edu/stat506/Lesson11")],
    ideas: [
      ["Define the unit before counting rows", "A unit might be a person, device, document or session. Repeated events from one unit do not automatically provide independent population members. Define the time window and eligibility rule too: the population is the subject of the claim, not whichever records are easiest to retrieve."],
      ["The frame determines who can appear", "A sampling frame is the list or access mechanism used to select units. Here leaving out the unit with value 10 makes that unit impossible to sample. Random selection within the remaining three units is still random, but it is no longer simple random sampling from the four-unit target."],
      ["A statistic has a sampling distribution", "The six complete-frame sample means are 3,5,6,6,7,9. Mean 6 has probability 2/6 because two different pairs produce it. The control highlights one possible realization; the bars describe all realizations under the specified design. Those are different views of the same estimator."],
      ["Unbiasedness is a repeated-design statement", "Averaging the six means yields the population mean 6, yet four of the six samples give a different answer. The standard deviation of this sampling distribution is √(10/3), not the spread of the four population values. Bias, variability and one realized error must not be interchanged."]
    ],
    process: ["Write the target population, observational unit and quantity to estimate, then compare the available frame with that target.", "Specify the selection design and inclusion opportunities; account for clustering, unequal probabilities and nonresponse where relevant.", "Compute the sample statistic and uncertainty under that design or a defensible model, while reporting coverage and measurement limitations separately."],
    example: ["Enumerate instead of imagining repeated samples", "Choose two units from (2,4,8,10) without replacement.", ["The population mean is 24/4=6. The six pair means (3,5,6,6,7,9) average to 6.", "The sampling variance is ((3−6)²+(5−6)²+0+0+(7−6)²+(9−6)²)/6=10/3. Equivalently, (1−2/4)×(40/3)/2=10/3.", "If the frame omits 10, only pair means 3,5,6 are possible. Their average is 14/3, biased downward by 4/3 relative to the intended population."], "A census of the incomplete frame still gives 14/3. Eliminating sampling variability inside that frame does not eliminate its coverage error."],
    pitfalls: ["A convenience sample is not converted into a probability sample by increasing its size or randomly splitting it into training and test partitions.", "Random sampling and random treatment assignment answer different questions: population representation versus causal comparability. One does not automatically supply the other.", "A tiny finite example supports exact enumeration, not a claim that six samples are enough for a real study. Finite-population corrections also require the appropriate without-replacement design."],
    implementation: ["Keep unit identifiers, inclusion rules, sampling probabilities where known, and the frame's coverage period. Prevent duplicated units from becoming unintended extra sampling weight.", "Separate uncertainty due to the design from systematic exclusions, nonresponse and measurement errors. Weighting requires information and assumptions; it cannot recover an entirely unobserved group from nothing."],
    outcomes: ["Distinguish population, sampling frame, sample, parameter and statistic.", "Read an exact sampling distribution and separate sampling variation from coverage bias."]
  }),
  [math("missing-data-mechanisms")]: reviewed({
    title: "Missing-data mechanisms", labTitle: "The same 40% missing, three different biases",
    summary: "A missing-data mechanism describes how observation indicators depend on observed and unobserved values. MCAR removes dependence on data values; MAR allows dependence on observed information but not on the missing values after conditioning on that information. MNAR retains dependence on unobserved values. These are assumptions about the observation process, not labels determined by the percentage missing.",
    hook: "A blank cell has a selection story; its absence is not automatically neutral.",
    model: "missingness-mechanisms", control: ["Missingness scenario · 0 MCAR / 1 MAR / 2 MNAR", 0, 2, 1, 1],
    equation: "MAR: R ⟂ Y | X; μcc=E[Y|R=1]; μadj=Σx P(X=x)E[Y|X=x,R=1]",
    assumptions: "Binary X is observed for every unit and has equal 0/1 shares. P(Y=1|X=0)=0.2 and P(Y=1|X=1)=0.8, so E[Y]=0.5. R=1 means Y is observed. Scenario 0 observes each Y with probability 0.6; scenario 1 uses probabilities 0.9 for X=0 and 0.3 for X=1; scenario 2 uses 0.9 for Y=0 and 0.3 for Y=1. All have 60% observed. Tables expose the known generating mechanism, including values normally hidden in a real dataset. Counts per 1,000 are expectations, not a simulated sample.",
    takeaway: "Adjustment works because of a justified missingness model, not because a table has been filled. Observed data alone generally cannot distinguish MAR from MNAR without additional assumptions.",
    prerequisites: [math("conditional-probability"), "probabilistic-ai/topics/conditional-independence", math("expectation")],
    sources: [source("van Buuren: MCAR, MAR and MNAR", "https://stefvanbuuren.name/fimd/sec-MCAR.html"), source("van Buuren: incomplete-data notation and identification", "https://stefvanbuuren.name/fimd/sec-idconcepts.html")],
    ideas: [
      ["Missing at random does not mean unconditional randomness", "In the MAR scenario, X=1 records are less likely to reveal Y. Since X predicts Y, the observed records have a distorted overall positive rate. MAR means that within an observed X group, response no longer depends on Y; it does not justify discarding X and averaging all complete cases."],
      ["Standardization puts the groups back in their target proportions", "Compute the positive rate among observed records separately for X=0 and X=1, then average those two rates using the known full-data 50/50 mix. Under this MAR model and positive response probabilities, the observed conditional means equal the full conditional means. The adjustment therefore returns 0.5 at the population level."],
      ["Within-group selection breaks that recovery", "In the MNAR scenario, positive Y values are less likely to be observed even after X is fixed. The observed positive rates become 1/13 and 4/7 rather than 0.2 and 0.8. Reweighting only the X groups still leaves a downward bias, because each group's remaining records are themselves selective."],
      ["Mechanism assumptions need domain evidence", "The lab knows how every blank was generated; a real analyst does not. Reasons for missingness, follow-up measurement, auxiliary variables and sensitivity analyses can support a strategy. A test that rejects MCAR does not establish MAR, and failing to reject MCAR is not proof that missingness is harmless."]
    ],
    process: ["Record an explicit observation indicator and distinguish a missing value from zero, a structural not-applicable value and a censored measurement.", "Identify information observed for everyone that could explain response, and state the conditional assumptions and positivity required by the proposed analysis.", "Compare complete-case and adjusted results, quantify estimation uncertainty, and vary unidentifiable assumptions in sensitivity analyses instead of claiming MAR has been verified from the observed values alone."],
    example: ["Correct the mix, but only when that is enough", "Select the MAR scenario with 1,000 expected full-data units.", ["Full counts in cells (X,Y)=(0,0),(0,1),(1,0),(1,1) are 400,100,100,400. Applying X-based response rates gives observed counts 360,90,30,120.", "Only 210 of the 600 observed records are positive, so the complete-case mean is 0.35. Within groups, however, the rates are 90/450=0.2 and 120/150=0.8.", "Restoring the 50/50 group mix gives 0.5×0.2+0.5×0.8=0.5. In the MNAR scenario the same operation instead gives (1/13+4/7)/2=59/182≈0.324176."], "Every scenario loses 40% of Y values. Missingness percentage alone cannot tell you whether complete-case analysis or this X-based adjustment recovers the target."],
    pitfalls: ["MCAR and MAR depend on the variables and missingness pattern under discussion. Adding genuinely informative observed variables can change which assumptions are plausible.", "MAR is not sufficient by itself for every implementation to work: the outcome or response model, overlap, estimand and uncertainty procedure still matter.", "Single mean imputation hides missing-value uncertainty and distorts distributions. Multiple imputation is not an automatic cure for MNAR; it still requires assumptions about unseen values and an appropriate analysis model."],
    implementation: ["Preserve missingness indicators and collection reasons instead of overwriting them. Fit imputation and response models without leakage across evaluation splits, and retain the design information needed by the estimand.", "Use domain-supported auxiliary predictors and inspect response probabilities. Report sensitivity to plausible departures from MAR. This lab computes known population quantities and does not supply finite-sample confidence intervals or a fitted imputation system."],
    outcomes: ["State MCAR, MAR and MNAR relative to explicitly observed variables.", "Explain why equal missingness rates can give different biases and why adjustment can fail within observed groups."]
  }),
  [math("effect-size")]: reviewed({
    title: "Effect size", labTitle: "Five points apart—relative to how much variation?",
    summary: "An effect size quantifies a difference or association on a chosen scale. A raw mean difference retains outcome units; a standardized mean difference divides by a stated measure of variation. Neither is a p-value, a sample-size calculation, or a causal conclusion by itself. Interpretation depends on the estimand, design, standardizer and practical context.",
    hook: "The numerator says how far apart; the denominator says what counts as a unit of separation.",
    model: "standardized-effect", control: ["Common population standard deviation σ", 2, 20, 1, 10, " score units"],
    equation: "Δ=μB−μA=5; δ=Δ/σ; overlap=2Φ(−|δ|/2); P(B>A)=Φ(δ/√2)",
    assumptions: "Two populations are normal with means 50 and 55 score units and the same standard deviation σ. The slider changes their population spread while holding the raw difference fixed. δ is a known population parameter in this toy, not an estimated Cohen's d. The overlap formula assumes equal-variance normal densities; P(B>A) compares independent draws, not paired outcomes for one unit. Shading is the pointwise minimum of the two densities. The axes rescale with σ, and normal probabilities are computed numerically.",
    takeaway: "Report the raw contrast and define the standardizer. Practical importance, uncertainty, statistical significance and causality require separate arguments.",
    prerequisites: [math("gaussian"), math("variance-and-covariance")],
    sources: [source("Lakens: effect sizes and their interpretation", "https://lakens.github.io/statistical_inferences/06-effectsize.html"), source("NIST: standardized mean differences and bias correction", "https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/hedgeg.htm")],
    ideas: [
      ["Start with the contrast in useful units", "A five-point difference can be compared with a domain-specific threshold for practical relevance. Dividing by a standard deviation is useful for expressing relative separation, but removes the original units and makes the answer depend on the population's variability. A smaller δ need not mean the raw difference became less useful."],
      ["Population δ and sample d are not the same object", "For independent groups with an appropriate common-variance interpretation, a common estimator is d=(ȳB−ȳA)/sp, where sp²=((nA−1)sA²+(nB−1)sB²)/(nA+nB−2). The random denominator gives small-sample bias; the usual bias-corrected Hedges' g applies a degrees-of-freedom correction. Paired designs and unequal-variance targets require an explicitly chosen alternative standardizer."],
      ["Separation is not absence of overlap", "At δ=0.5 the normal densities still have about 80% common area. A randomly selected B value exceeds an independent A value with probability about 0.638. Neither statement says that 63.8% of individuals would benefit from changing their condition: that would require a causal, usually paired counterfactual question."],
      ["Precision can change without changing the target effect", "Collecting more independent observations can reduce uncertainty about a fixed mean difference without changing the population δ. A very small effect can be estimated precisely. Conversely, a large point estimate may have wide uncertainty. Avoid replacing a confidence interval and substantive judgment with universal small/medium/large labels."]
    ],
    process: ["Specify the contrast, direction, population and units, distinguishing a descriptive association from a causal estimand.", "Choose a raw or standardized measure suited to the design and state its denominator; use the appropriate estimator and any bias correction.", "Report uncertainty and a practical relevance threshold alongside the effect, rather than inferring importance from a p-value or a conventional magnitude label."],
    example: ["Keep the five points, double the variation", "Compare means 50 and 55 with shared σ=10.", ["The raw contrast is 5 score units and standardized contrast is δ=5/10=0.5.", "For these normal populations, overlap is 2Φ(−0.25)≈0.802587 and P(B>A)=Φ(0.5/√2)≈0.638163.", "Increase σ to 20: the raw difference remains 5, but δ becomes 0.25. No sample size, hypothesis test or intervention was changed by this operation."], "Standardization expresses a difference relative to variation. It does not replace the original scale or establish practical or causal importance."],
    pitfalls: ["Risk differences, risk ratios, odds ratios, correlations and standardized mean differences are different effect measures; do not compare their numeric magnitudes as though they shared one scale.", "The normal overlap and independent-draw formulas in this lab do not apply unchanged to skewed distributions, unequal variances or paired observations.", "A nonsignificant difference does not establish equivalence. A significant difference does not establish a practically important or causal effect."],
    implementation: ["Store group definitions, sample sizes, spread estimates, sign convention and the exact standardizer with reported effects. State whether a correction such as Hedges' g was applied; software terminology is not always uniform.", "Use design-appropriate uncertainty intervals and inspect the outcome distributions. For paired or clustered data, preserve their dependence structure. The plotted populations are a teaching model, not evidence from a real comparative study."],
    outcomes: ["Distinguish raw and standardized effect sizes from uncertainty and significance.", "Interpret overlap and independent-draw comparisons under their explicit distributional assumptions."]
  })
};
for (const lesson of Object.values(dataQualityLessons)) lesson.updatedAt = "2026-09-30";
