import { math, source, reviewed } from "./lesson-helpers.mjs";
const book = source("Pishro-Nik: Introduction to Probability", "https://www.probabilitycourse.com/");
const scipy = (name) => source(`SciPy: ${name}`, `https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.${name}.html`);
const normal = math("gaussian"), density = math("probability-mass-and-density-functions");

export const distributionLessons = {
  [density]: reviewed({
    title:"Probability mass and density functions", labTitle:"Height is not probability", model:"dist-density", control:["Support width b",0.25,2,0.05,0.5],
    summary:"A PMF assigns probability to individual discrete outcomes. A PDF assigns density to a continuous variable: interval probability is an integral, while any individual point has probability zero for an absolutely continuous distribution.",
    hook:"For a density, measure the area—not the height.", equation:"P(X=k)=p(k); P(a≤X≤b)=∫ₐᵇf(x)dx for an absolutely continuous X",
    assumptions:"The graph is Uniform(0,b), not a PMF. The shaded interval is the left half of its support. Density has inverse-length units; probability is dimensionless.",
    takeaway:"A density may exceed one. Its integral, not its height, must equal one; mixed distributions need both atomic masses and a continuous part.", sources:[book,scipy("uniform")],
    ideas:[["Different normalization rules","Discrete masses sum to one over their support. An absolutely continuous density integrates to one; changing units changes its height."],["Not every law has a PDF","A variable can have an atom at zero plus a continuous positive part. A single ordinary PDF cannot represent that atom, although a CDF represents the full law."]],
    process:["Identify whether outcomes are discrete, continuous, or mixed.","For a density, specify an interval before asking for probability.","Check the appropriate sum or integral and keep the units explicit."],
    example:["A density taller than one","Take X uniform on [0,0.5].",["The density is 2 per length unit.","The interval [0,0.25] has probability 0.25×2=0.5; P(X=0.25)=0."],"A height of 2 is valid because the full rectangle has area 1."],
    pitfalls:["Treating a PDF value as a point probability can produce impossible probability statements.","Histogram density heights depend on bin width; bin area carries probability."],
    implementation:["Use PMF routines for discrete counts and PDF/CDF routines for continuous quantities.","Use CDF differences or survival functions for interval/tail probabilities instead of treating sampled density values as masses."],
    outcomes:["Distinguish PMF sums from PDF areas.","Explain why density can exceed one without violating probability axioms."],
  }),
  [math("cumulative-distributions")]: reviewed({
    title:"Cumulative distributions",labTitle:"Accumulate the probability",model:"dist-cdf",control:["Threshold t",-0.5,1.5,0.05,0.5],
    summary:"The cumulative distribution function F(t)=P(X≤t) describes any real-valued random variable. It is nondecreasing and right-continuous, with limits zero and one at negative and positive infinity.",
    hook:"Move a threshold rightward and collect everything to its left.",equation:"F(t)=P(X≤t); P(a<X≤b)=F(b)−F(a)",
    assumptions:"The live example is Uniform(0,1), so F is zero below 0, equals t on [0,1], and equals one above 1. This continuous example has no point masses.",takeaway:"CDF height is already probability. For a discrete law, the size of a jump gives the probability at that point.",sources:[book,scipy("uniform")],prerequisites:[density],
    ideas:[["Endpoint conventions","F(b)−F(a) excludes a and includes b. Including an atom at a instead requires the left limit F(a−). For continuous laws the distinction disappears."],["Recovering density","Where an absolutely continuous CDF is differentiable, its derivative gives the PDF almost everywhere. Jumps cannot be recovered as ordinary finite density values."]],
    process:["State whether the requested inequality includes its boundary.","Evaluate the CDF at both ends of an interval.","Account for atoms before swapping strict and non-strict inequalities."],
    example:["Probability between two thresholds","For Uniform(0,1), find P(0.2<X≤0.7).",["F(0.7)=0.7 and F(0.2)=0.2.","Subtract to obtain 0.5."],"For this continuous distribution, including or excluding the endpoints changes nothing."],
    pitfalls:["A CDF need not be smooth or even continuous.","The derivative of a CDF at one point is not the probability of that point."],implementation:["Prefer survival-function routines for very small upper tails to avoid subtracting two nearly equal numbers.","Test CDF monotonicity, support boundaries, and discrete jump sizes."],outcomes:["Compute interval probabilities with correct endpoints.","Read a CDF's jumps and flat regions."],
  }),
  [math("categorical")]: reviewed({
    title:"Categorical",labTitle:"One draw, three possible labels",model:"dist-categorical",control:["Probability of A",0,1,0.05,0.5],
    summary:"A categorical distribution selects exactly one of K labels using nonnegative probabilities that sum to one. Labels need not have a meaningful numerical order, even when represented by integer codes.",hook:"One slot is chosen; probability mass is shared across the slots.",equation:"P(X=i)=pᵢ; pᵢ≥0; Σᵢpᵢ=1",
    assumptions:"Three mutually exclusive labels A,B,C. The slider sets pA; the remainder is split 40:60 between B and C. Codes 0,1,2 are identifiers, not measured magnitudes.",takeaway:"Categorical models describe one label; independent Bernoulli models describe separate yes/no events that may occur together.",sources:[book,scipy("multinomial")],prerequisites:[density],
    ideas:[["One-hot representation","The indicator vector has one entry equal to one. Its expectation is the probability vector, and indicators for different categories have covariance −pᵢpⱼ."],["Prediction versus a draw","Argmax returns the most probable label deterministically. Sampling selects a random label and may choose a less probable outcome."]],
    process:["Choose mutually exclusive, collectively exhaustive labels.","Validate nonnegative probabilities and their total.","Distinguish sampling from selecting the most likely class."],example:["A three-way routing choice","At pA=0.5, distribute the remaining 0.5 in ratio 40:60.",["pB=0.2 and pC=0.3.","Across 100 independent draws, expected counts are 50,20,30, not guaranteed counts."],"A single draw produces only one label."],pitfalls:["Numerical category codes do not justify averaging labels.","A categorical law is not a model for several simultaneously true labels."],implementation:["Validate that every logit/probability entry corresponds to the intended class.","Use stable normalization for logits and test deterministic endpoint distributions."],outcomes:["Specify a valid categorical probability vector.","Separate single-label sampling from multilabel Bernoulli modelling."],
  }),
  [math("multinomial")]: reviewed({
    title:"Multinomial",labTitle:"Counts share a fixed total",model:"dist-multinomial",control:["Number of trials n",1,12,1,10],
    summary:"The multinomial distribution models category counts from n independent categorical trials with a shared probability vector. The counts sum to n and are dependent even though the trials are independent.",hook:"A count gained by one category leaves fewer trials for the others.",equation:"P(N=k)=n!∏ᵢ(pᵢᵏⁱ/kᵢ!); Σᵢkᵢ=n; Cov(Nᵢ,Nⱼ)=−npᵢpⱼ for i≠j",
    assumptions:"The probability vector is (0.2,0.3,0.5). The graph is the marginal distribution of NA only; the covariance table covers all three counts. It is not a plot of the joint PMF.",takeaway:"Each individual count is binomial, but multiplying those binomial marginals does not give the joint count distribution.",sources:[book,scipy("multinomial")],prerequisites:[math("categorical"),math("binomial")],
    ideas:[["The combinatorial factor","The factorial coefficient counts distinct trial sequences that yield the same counts. The count vector discards ordering, so all those sequences contribute probability."],["A constrained covariance","Var(Nᵢ)=npᵢ(1−pᵢ). Negative off-diagonal covariance reflects the fixed total, and the covariance matrix is singular because its row sums are zero."]],
    process:["Fix the trial count and shared category probabilities.","Check the proposed nonnegative integer counts sum to n.","Include the sequence-count factor when calculating the joint probability."],example:["One of each label","For n=3 and counts (1,1,1):",["There are 3!=6 possible orderings.","Each has probability 0.2×0.3×0.5=0.03."],"The count vector has probability 6×0.03=0.18."],pitfalls:["Independent trials do not imply independent counts.","Changing probabilities across trials breaks the ordinary multinomial model."],implementation:["Evaluate large factorial products with log-gamma functions.","Check both the fixed-total constraint and covariance row sums in simulations."],outcomes:["Compute a multinomial joint probability.","Explain binomial marginals and dependent category counts."],
  }),
  [math("uniform")]: reviewed({
    title:"Uniform",labTitle:"Spread the same mass over a wider interval",model:"dist-uniform",control:["Upper endpoint b",0.5,4,0.1,2],
    summary:"A continuous uniform distribution assigns constant density across a finite interval. Equal-length subintervals have equal probability; individual points still have probability zero. Discrete uniform distributions instead assign equal masses to a finite set.",hook:"Double the width and halve the height.",equation:"X~U(a,b): f(x)=1/(b−a); E[X]=(a+b)/2; Var(X)=(b−a)²/12",
    assumptions:"Here a=0 and b>0. Shading covers [0,min(1,b)] and measures P(X≤1). Endpoint values of the density do not affect probabilities.",takeaway:"Uniformity depends on the coordinate system: a nonlinear transformation of a uniform variable is generally not uniform.",sources:[book,scipy("uniform")],prerequisites:[density],
    ideas:[["Finite support","Constant positive density over the whole real line cannot normalize. A continuous uniform model needs a finite interval with positive width."],["Choosing a measure","Uniform over angle, area, or radius are different sampling prescriptions. Equal parameter increments need not represent equal geometric area."]],process:["Specify the interval and units.","Divide overlap length by total interval length.","Check whether a later transformation changes the density."],example:["A random delay","Let X be uniform on [0,4] seconds.",["The density is 0.25 per second.","P(X≤1)=1/4, E[X]=2 seconds, and Var(X)=16/12 seconds²."],"Every one-second subinterval inside the support has probability 0.25."],pitfalls:["An absence of prior knowledge does not uniquely justify a uniform law.","Uniform radius does not produce a uniform point in a disk."],implementation:["State whether an API takes an upper endpoint or a scale equal to interval width.","Test transforms with their change-of-variables factor rather than assuming uniformity persists."],outcomes:["Calculate uniform interval probabilities and moments.","Recognize the coordinate dependence of uniform sampling."],
  }),
  [normal]: reviewed({
    title:"Gaussian",labTitle:"Wider bell, lower peak",model:"dist-normal",control:["Standard deviation σ",0.5,2,0.05,1],
    summary:"A Gaussian or normal distribution is determined by mean μ and variance σ²>0. Its symmetric bell-shaped density has unbounded support. The standard deviation controls spread; it is not the same parameter as variance.",hook:"The bell gets wider without gaining probability mass.",equation:"f(x)=exp(−(x−μ)²/(2σ²))/(σ√(2π)); Z=(X−μ)/σ",
    assumptions:"The live example fixes μ=0 and varies σ. Shading marks [−σ,σ], with approximate probability 0.682689. The plot clips continuing tails outside [−6,6].",takeaway:"The 68–95–99.7 rule is specific to Gaussian standard-deviation intervals, not a universal rule for bell-like data.",sources:[book,scipy("norm")],prerequisites:[density],
    ideas:[["Standardization","Subtracting μ and dividing by σ produces a standard normal when the original law is normal. Standardizing arbitrary data does not make it normally distributed."],["A modelling assumption","Sums and averages can approach normal limits under suitable assumptions. This does not prove a particular small-sample dataset or its tails are Gaussian."]],process:["Specify μ and whether a scale parameter is σ or σ².","Standardize interval endpoints.","Use a normal CDF or survival function for probabilities."],example:["A measurement interval","For X~Normal(10,4), the variance is 4 and σ=2.",["The interval [8,12] becomes [−1,1] after standardization.","Its probability is approximately 0.682689."],"Using 4 as the standard deviation would describe a different distribution."],pitfalls:["Gaussian support includes negative values even when μ is positive.","Rare-event estimates can be highly sensitive to unverified Gaussian tail assumptions."],implementation:["Use a log-density for products of many likelihood terms.","Check residual and tail behaviour rather than relying only on mean and variance."],outcomes:["Distinguish variance from standard deviation.","Translate an interval into standardized Gaussian coordinates."],
  }),
  [math("multivariate-gaussian")]: reviewed({
    title:"Multivariate Gaussian",labTitle:"Correlation tilts the contours",model:"dist-mvn",control:["Correlation ρ",-0.9,0.9,0.05,0.5],
    summary:"A multivariate Gaussian models a vector using a mean and covariance matrix. For positive-definite covariance, equal-density contours are ellipsoids determined by Mahalanobis distance, not by independent coordinatewise error bars.",hook:"Marginal widths can stay fixed while the joint cloud rotates and narrows.",equation:"f(x)=exp(−½(x−μ)ᵀΣ⁻¹(x−μ))/((2π)ᵈᐟ²√detΣ)",
    assumptions:"A bivariate example has μ=(0,0), unit marginal variances, and off-diagonal correlation ρ. |ρ|<1 guarantees positive definiteness. Curves mark Mahalanobis radii 1 and 2, not samples.",takeaway:"A radius-one ellipse contains about 39.35% of a two-dimensional Gaussian, not the one-dimensional 68.27% interval probability.",sources:[book,scipy("multivariate_normal")],prerequisites:[normal,math("positive-semidefinite-matrices")],
    ideas:[["Joint Gaussian independence","For jointly Gaussian variables, zero covariance implies independence. This equivalence fails for general non-Gaussian joint distributions."],["Singular covariance","A singular PSD covariance can define a Gaussian supported on a lower-dimensional subspace. It then has no ordinary full-dimensional density of the displayed formula."]],process:["Validate covariance symmetry and definiteness.","Whiten a centred vector using a factorization.","Use the dimension-appropriate chi-square radius to specify coverage."],example:["Correlated standardized coordinates","Take ρ=0.5, so Σ=[[1,0.5],[0.5,1]].",["The determinant is 0.75 and eigenvalues are 1.5 and 0.5.","Squared Mahalanobis radius has a χ² distribution with 2 degrees of freedom."],"Coverage inside radius 1 is 1−e^(−1/2)≈0.39347."],pitfalls:["Combining marginal one-sigma intervals does not create a joint one-sigma coverage guarantee.","A covariance matrix with a negative eigenvalue is invalid."],implementation:["Use Cholesky solves and log determinants rather than explicitly inverting covariance.","State whether singular covariance is supported and how its rank is determined."],outcomes:["Interpret Gaussian covariance contours.","Separate marginal spread from joint probability coverage."],
  }),
  [math("poisson")]: reviewed({
    title:"Poisson",labTitle:"Count arrivals in a fixed window",model:"dist-poisson",control:["Expected count λ",0,10,0.25,3],
    summary:"A Poisson distribution assigns probabilities to nonnegative integer counts with mean and variance λ. Counts from a homogeneous Poisson process over duration t have λ=rate×t; rarity alone does not establish this model.",hook:"Fix the observation window; let the count vary.",equation:"P(K=k)=e^(−λ)λᵏ/k!; E[K]=Var(K)=λ",
    assumptions:"λ is the expected count in one fixed interval, not a probability. The graph shows k=0…30 and reports omitted upper-tail mass without rescaling the bars. At λ=0, all mass is at zero.",takeaway:"A count's mean and variance being equal is a Poisson property, not a rule for all event-count data.",sources:[book,scipy("poisson")],prerequisites:[density],
    ideas:[["Process assumptions","A homogeneous Poisson process has independent counts in disjoint intervals and a constant rate, with suitable small-interval behaviour. Clustering or changing rates can violate these assumptions."],["Overdispersion","Count variation larger than the mean may signal heterogeneity, dependence, or a different count model. It should not be hidden by reporting only a fitted mean."]],process:["Specify the exposure interval and count definition.","Convert rate and exposure to expected count λ.","Compare zero counts, tails, and dispersion with the proposed model."],example:["Three expected requests","Let λ=3 requests per observation window.",["P(K=0)=e^(−3)≈0.049787.","P(K=2)=e^(−3)×9/2≈0.224042."],"The count can exceed three; λ is an average, not a maximum."],pitfalls:["Events being individually rare does not guarantee Poisson counts.","Counts across overlapping windows are not independent even in a Poisson process."],implementation:["Use log-PMFs for large counts and expose omitted plot tail mass.","Include exposure or duration when comparing counts from different windows."],outcomes:["Convert rate and exposure into a Poisson parameter.","Check the model's mean–variance and process assumptions."],
  }),
  [math("geometric-distribution")]: reviewed({
    title:"Geometric distribution",labTitle:"Wait for the first success",model:"dist-geometric",control:["Success probability p",0.1,1,0.05,0.25],
    summary:"The geometric distribution models the trial number of the first success in independent Bernoulli trials with a fixed success probability. It supplies the discrete waiting-time counterpart to the exponential distribution.",hook:"Keep trying: count the trial that finally succeeds.",equation:"P(K=k)=(1−p)^(k−1)p, k≥1; E[K]=1/p; Var(K)=(1−p)/p²",
    assumptions:"K counts trials including the successful trial, not failures before it. The plotted range is 1…40; omitted tail mass is (1−p)^40. Trials are independent with the same p.",takeaway:"Two common conventions differ by one: trials-to-success starts at 1, failures-before-success starts at 0.",sources:[book,scipy("geom")],prerequisites:[math("bernoulli")],
    ideas:[["Memoryless survival","P(K>m+n | K>m)=(1−p)^n for nonnegative integers m,n whenever the conditioning event has positive probability. Failed attempts do not improve the next attempt's success chance."],["Not a binomial count","A binomial experiment fixes the number of trials and counts successes. A geometric experiment stops at the first success and counts how many trials were needed."]],process:["Choose the trials or failures convention explicitly.","Verify constant success probability and independent attempts.","Multiply the preceding failure probabilities by the final success probability."],example:["The first success on trial three","Use p=0.25.",["The required sequence is failure, failure, success.","Its probability is 0.75²×0.25=0.140625; the expected first-success trial is 4."],"After two failures, the next trial still succeeds with probability 0.25."],pitfalls:["Increasing skill, changing conditions, or dependence breaks the fixed-p model.","Mixing the two support conventions shifts means and probabilities by one trial."],implementation:["Check a library's support before matching formulas to outputs.","Calculate long survival tails in log space with log1p(−p)."],outcomes:["Distinguish geometric waiting time from binomial counts.","Apply the correct support convention and memoryless property."],
  }),
  [math("exponential")]: reviewed({
    title:"Exponential",labTitle:"Faster arrivals, shorter waits",model:"dist-exponential",control:["Arrival rate λ",0.25,3,0.05,1,"/s"],
    summary:"An exponential distribution models a nonnegative waiting time with constant hazard. In a homogeneous Poisson process it describes interarrival times. Its rate λ has inverse-time units and its mean is 1/λ.",hook:"Turn up the rate; compress the waiting time.",equation:"f(t)=λe^(−λt), t≥0; P(T>t)=e^(−λt); E[T]=1/λ",
    assumptions:"λ is measured per second. Shading is P(T≤1 second). The graph ends at 12 seconds and reports the survival probability beyond that boundary.",takeaway:"Rate and scale are reciprocals. A larger rate means a shorter mean wait, not a longer one.",sources:[book,scipy("expon")],prerequisites:[math("poisson"),density],
    ideas:[["Memorylessness","P(T>s+t | T>s)=P(T>t). The remaining wait has the same distribution after elapsed time when the rate truly stays constant."],["Hazard versus density","The density decreases with time, but the hazard f(t)/P(T>t)=λ is constant. These quantities answer different conditional questions."]],process:["Choose time units and state rate or scale.","Use survival probability for a wait longer than a threshold.","Check whether elapsed time or changing conditions alter the hazard."],example:["Two arrivals per second","Set λ=2/s.",["Mean wait is 0.5 seconds.","P(T>1s)=e^(−2)≈0.135335, so P(T≤1s)≈0.864665."],"A mean wait of 0.5 seconds does not bound possible waits."],pitfalls:["A process with ageing or a time-varying hazard is not exponential with one fixed rate.","Passing a rate into an API's scale argument reverses the intended effect."],implementation:["Use scale=1/rate where a library expects scale.","Use expm1 or a direct CDF routine to avoid cancellation for very short waits."],outcomes:["Compute exponential waiting probabilities with units.","Distinguish density, hazard, rate, and scale."],
  }),
  [math("gamma")]: reviewed({
    title:"Gamma",labTitle:"Wait for several arrivals",model:"dist-gamma",control:["Arrival number k",1,6,1,3],
    summary:"A gamma distribution models positive values with shape α and either rate β or scale θ=1/β. Integer shape gives an Erlang waiting time: a sum of independent exponential waits with the same rate.",hook:"Stack independent waits to reach the kth arrival.",equation:"f(t)=β^α t^(α−1)e^(−βt)/Γ(α); E[T]=α/β; Var(T)=α/β²",
    assumptions:"The lab uses integer shape k=1…6 and fixed rate 1/s. The density continues beyond the displayed 18-second window. General gamma shapes may be any positive real number.",takeaway:"Shape controls how many rate-matched exponential waits are summed only in the integer-shape interpretation.",sources:[book,scipy("gamma")],prerequisites:[math("exponential")],
    ideas:[["Exponential special case","At shape 1, gamma reduces to exponential. Shapes below 1 have a density singularity at zero; they cannot be interpreted as a fractional count of arrivals."],["Adding compatible gammas","Independent gamma variables with a common rate sum to a gamma with summed shapes. Different rates do not generally retain the same gamma family."]],process:["Declare whether the second parameter is rate or scale.","Check whether an arrival-count interpretation requires integer shape.","Compute mean and variance before interpreting a plotted peak."],example:["Third arrival at rate two","Let T be the wait for arrival 3 of a rate-2/s Poisson process.",["T has shape 3 and rate 2, so mean=1.5 seconds.","Variance=3/4 seconds² and mode=(3−1)/2=1 second."],"The most likely time is not the mean time."],pitfalls:["Gamma rate and gamma scale conventions are incompatible unless converted.","The integer-arrival story does not cover every gamma shape."],implementation:["Evaluate gamma densities in log space using log-gamma.","Handle the x=0 boundary separately, especially for shape below one."],outcomes:["Use gamma shape/rate moments correctly.","Connect and distinguish gamma, Erlang, and exponential laws."],
  }),
  [math("beta")]: reviewed({
    title:"Beta",labTitle:"A distribution over a probability",model:"dist-beta",control:["Shape α",1,8,0.25,2],
    summary:"A beta distribution models a continuous value between zero and one using two positive shape parameters. It is often used for an uncertain Bernoulli probability, but a beta draw is a probability-like value rather than a binary outcome.",hook:"Uncertainty about the coin is different from uncertainty about its next flip.",equation:"f(p)=p^(α−1)(1−p)^(β−1)/B(α,β); E[p]=α/(α+β)",
    assumptions:"The lab varies α≥1 while β=2. It shows a density over p on [0,1], not a probability mass at p. Shapes below one, with possible boundary singularities, are discussed but not plotted.",takeaway:"The mean is α/(α+β); concentration α+β controls spread when the mean ratio is held fixed.",sources:[book,scipy("beta")],prerequisites:[density,math("bernoulli")],
    ideas:[["Conjugate updating","With a Beta(α,β) prior and independent Bernoulli observations at one fixed unknown probability, s successes and f failures produce Beta(α+s,β+f)."],["Shape versus evidence","Positive α and β define a prior; interpreting them as literal observed counts requires care. Prior strength and prior mean are separate modelling choices."]],process:["Choose positive shape parameters and inspect their implied mean.","State the observation model before applying an update.","Report interval uncertainty, not only the posterior mean."],example:["Updating a uniform prior","Start with Beta(1,1) and observe 3 successes, 1 failure.",["The posterior is Beta(4,2).", "Its mean is 4/6=2/3 and variance is 8/(36×7)=2/63."],"The posterior mean differs from the empirical success rate 3/4 because of the prior."],pitfalls:["A beta density's height is not the probability of an exact p.","The conjugate update assumes a shared Bernoulli probability and an appropriate likelihood."],implementation:["Validate shapes strictly above zero.","Use beta quantiles or interval calculations when communicating uncertainty."],outcomes:["Read beta mean and concentration.","Perform and qualify a beta–Bernoulli update."],
  }),
  [math("dirichlet")]: reviewed({
    title:"Dirichlet",labTitle:"Same mean, different concentration",model:"dist-dirichlet",control:["Shared concentration c",1,8,0.25,1],
    summary:"A Dirichlet distribution models an entire probability vector on the simplex. Positive parameters αᵢ set mean proportions αᵢ/α₀, where α₀ is their sum; components are coupled by the requirement that they sum to one.",hook:"All shares fit in one pie, even as uncertainty changes.",equation:"E[pᵢ]=αᵢ/α₀; Var(pᵢ)=αᵢ(α₀−αᵢ)/(α₀²(α₀+1))",
    assumptions:"The three-component model is Dirichlet(c,c,c). The graph shows only p₁'s Beta(c,2c) marginal—not the full simplex density. c ranges from 1 to 8; every mean stays 1/3.",takeaway:"Uniform over a simplex does not make every component uniform on [0,1]; Dirichlet(1,1,1) has Beta(1,2) marginals.",sources:[book,scipy("dirichlet")],prerequisites:[math("beta"),math("categorical")],
    ideas:[["Negative component covariance","For i≠j, Cov(pᵢ,pⱼ)=−αᵢαⱼ/(α₀²(α₀+1)). Increasing one share necessarily reduces the room available to the others."],["Updating category probabilities","With independent categorical observations, adding each observed category count to its corresponding α parameter gives the conjugate posterior."]],process:["Specify all positive concentration parameters.","Separate the mean vector from total concentration.","Label marginal plots explicitly so they are not mistaken for the joint simplex geometry."],example:["Uniform simplex, nonuniform marginal","Take α=(1,1,1).",["Each mean is 1/3 and each variance is 1/18.","The first component has density 2(1−p₁) on [0,1]."],"There is more simplex area at small p₁ than near p₁=1."],pitfalls:["Independent beta draws do not generally sum to one and are not a Dirichlet draw.","Higher total concentration narrows uncertainty only when mean proportions are held fixed."],implementation:["Check sampled vectors sum to one within numerical tolerance.","Keep category order consistent between counts, parameters, and labels."],outcomes:["Separate Dirichlet means from concentration.","Interpret beta marginals without losing the simplex constraint."],
  }),
  [math("log-normal")]: reviewed({
    title:"Log-normal",labTitle:"A symmetric log becomes a skewed value",model:"dist-lognormal",control:["Log-space standard deviation σ",0.25,1.25,0.05,0.5],
    summary:"A positive random variable is log-normal when its natural logarithm is Gaussian. Parameters μ and σ describe the logarithm, not the mean and standard deviation of the original variable.",hook:"Multiplication in ordinary space becomes addition in log space.",equation:"X=e^Z, Z~N(μ,σ²); median(X)=e^μ; E[X]=e^(μ+σ²/2)",
    assumptions:"μ=0 while σ changes. X is a dimensionless multiplicative factor. The displayed density ends at 12, but the right tail continues indefinitely.",takeaway:"Exponentiating the log mean gives the median, not the arithmetic mean; the latter grows with log-space variance.",sources:[book,scipy("lognorm")],prerequisites:[normal,density],
    ideas:[["The Jacobian matters","The density of X includes a factor 1/x from transforming z=log x. Evaluating a normal PDF at log x without that factor does not produce a normalized log-normal PDF."],["Multiplicative effects","Products of independent log-normal variables are log-normal because their logs sum as independent Gaussians. Sums of log-normal variables generally are not log-normal."]],process:["Check positivity and inspect log-space behaviour.","State parameters on the log scale.","Convert moments with the nonlinear formulas rather than exponentiating every statistic."],example:["Median one, mean above one","Let Z~N(0,1) and X=e^Z.",["The median is 1 and mode is e^(−1)≈0.367879.","The mean is e^(1/2)≈1.648721."],"Right-tail values lift the arithmetic mean above the median."],pitfalls:["Taking logs of zero or negative observations is not valid without a justified model change.","Positive data need not be log-normal; the right tail must still be checked."],implementation:["For SciPy's lognormal convention, shape is σ and scale is exp(μ), with location zero for this model.","Use log-domain calculations for products and very large values."],outcomes:["Interpret log-normal parameters on the right scale.","Distinguish mean, median, and mode after exponentiation."],
  }),
  [math("student-s-t")]: reviewed({
    title:"Student's t",labTitle:"Heavy tails approach a Gaussian",model:"dist-student",control:["Degrees of freedom ν",1,30,1,5],
    summary:"Student's t is a symmetric family with degrees of freedom ν>0 and heavier tails than a Gaussian. Standard t has mean zero only for ν>1 and finite variance ν/(ν−2) only for ν>2.",hook:"The central bell can look familiar while the tails behave differently.",equation:"T=Z/√(V/ν), Z~N(0,1), V~χ²ν independently; Var(T)=ν/(ν−2) for ν>2",
    assumptions:"The lab uses integer ν and unit scale. It compares t with a standard normal on [−6,6]; tails continue outside that window. Scale one does not mean variance one.",takeaway:"At ν=1 this is the Cauchy law: symmetry does not rescue an undefined mean. As ν grows, standard t converges to standard normal.",sources:[book,scipy("t")],prerequisites:[normal],
    ideas:[["Estimated standard error","For independent normal observations, (sample mean−μ)/(s/√n) has t distribution with n−1 degrees of freedom. Normality and the variance estimate matter to the exact statement."],["Moment existence","A t distribution has finite absolute moments of order r only when r<ν. Small degrees of freedom can therefore invalidate familiar mean/variance summaries."]],process:["State degrees of freedom and whether scale or standard deviation is specified.","Check moment existence before reporting moments.","Use the appropriate t quantile for inference under its stated assumptions."],example:["A standard t with five degrees","Set ν=5 and scale=1.",["The mean is 0 and variance is 5/3≈1.666667.","Its standard deviation is √(5/3)≈1.291, not 1."],"Comparing equal-scale t and normal curves is not an equal-variance comparison."],pitfalls:["Symmetry alone does not imply a finite expectation.","Using t quantiles does not automatically make an analysis robust to arbitrary dependence or sampling bias."],implementation:["Treat undefined moments explicitly rather than silently displaying zero.","Use log-PDF and tail-probability routines when rare extremes matter."],outcomes:["Check which t moments exist.","Distinguish degrees of freedom, scale, and variance."],
  }),
  [math("gumbel")]: reviewed({
    title:"Gumbel",labTitle:"Location is not the mean",model:"dist-gumbel",control:["Scale β",0.5,2,0.05,1],
    summary:"The right-skewed Gumbel family is one possible limiting law for normalized maxima under suitable tail assumptions. It has location μ, positive scale β, and support across the real line; not every maximum follows a Gumbel law.",hook:"The peak stays at the location while the right tail pulls the mean away.",equation:"F(x)=exp(−exp(−(x−μ)/β)); E[X]=μ+γβ; Var(X)=π²β²/6",
    assumptions:"This is the maxima/right-skewed convention with μ=0. γ≈0.577216 is Euler's constant. The plot clips both tails outside [−6,12].",takeaway:"Location μ equals the mode, not the mean. Maxima and minima conventions have different skew directions.",sources:[book,scipy("gumbel_r"),source("Jang, Gu & Poole: Gumbel-Max and Gumbel-Softmax", "https://arxiv.org/abs/1611.01144")],prerequisites:[math("cumulative-distributions")],
    ideas:[["An extreme-value domain","Appropriately normalized maxima of many light-tailed parent laws can approach a Gumbel limit. Other parent tails lead to different extreme-value families."],["A sampling connection","For independent standard Gumbel noises Gᵢ, argmax(log pᵢ+Gᵢ) samples a categorical label for positive probabilities pᵢ. This statement concerns the argmax, not a differentiable soft approximation."]],process:["Choose the maxima or minima convention.","Keep location and scale distinct from mean and variance.","Justify an extreme-value approximation using the sampling and tail setting."],example:["Standard right Gumbel","Use μ=0 and β=1.",["The mode is 0, median is −log(log 2)≈0.366513, and mean is γ≈0.577216.","F(0)=e^(−1)≈0.367879."],"The location is neither the median nor the mean."],pitfalls:["Applying a Gumbel distribution to any observed maximum without checking the domain of attraction is unjustified.","Confusing right- and left-skewed conventions reverses tail behaviour."],implementation:["Use a dedicated Gumbel routine and name the convention explicitly.","For inverse-CDF sampling, avoid uniform inputs exactly at zero or one."],outcomes:["Separate Gumbel location, mean, median, and mode.","State limitations of the extreme-value interpretation."],
  }),
};
