import { math, source, reviewed } from "./lesson-helpers.mjs";
const prob = name => `probabilistic-ai/topics/${name}`;
const harvard = source("Harvard: estimation, Kalman filtering and nonlinear filters", "https://hankyang.seas.harvard.edu/OptimalControlEstimation/output-feedback.html");
const algorithms = source("MathWorks: extended and unscented filter algorithms", "https://www.mathworks.com/help/control/ug/extended-and-unscented-kalman-filter-algorithms-for-online-state-estimation.html");
const overview = source("MathWorks: prediction and correction in estimation filters", "https://www.mathworks.com/help/fusion/ug/introduction-to-estimation-filters.html");

export const kalmanLessons = {
  [prob("kalman-filter")]: reviewed({
    title: "Kalman filter", labTitle: "Let uncertainty decide how much to trust a reading",
    summary: "The Kalman filter recursively predicts a state distribution and conditions it on a new measurement. With a Gaussian initial state, linear dynamics and observations, and the specified independent Gaussian noises, the filtering distribution remains Gaussian and its mean and covariance are exact. Incorrect noise or dynamics assumptions can still make the estimate unreliable.",
    hook: "Trust is a ratio of uncertainties, not a fixed preference for the sensor.", model: "filter-linear", control: ["Measurement noise variance R", 0.25, 9, 0.25, 1, " m²"],
    equation: "μ⁻=Fμ+b; P⁻=FPFᵀ+Q; K=P⁻Hᵀ(HP⁻Hᵀ+R)⁻¹; μ⁺=μ⁻+K(z−Hμ⁻)",
    assumptions: "One scalar predict–correct cycle. Previous position is N(1,1), with mean in metres and variance in m². Motion adds 1 m plus independent N(0,3) process noise, giving predicted N(2,4). The sensor observes z=x+v with independent v∼N(0,R), and reports z=5 m. Curves show the predicted prior, measurement likelihood as a function of x, and posterior; N(μ,P) uses variance as its second argument.",
    takeaway: "Prediction adds process uncertainty; correction combines prior and measurement precision. A smaller posterior covariance is meaningful only relative to a credible model.",
    prerequisites: [math("gaussian"), math("bayes-theorem"), math("variance-and-covariance")], sources: [harvard, overview],
    ideas: [["Prediction moves both mean and uncertainty", "In this scalar model F=1 and b=1. The previous mean 1 becomes 2, while independent process noise adds variance Q=3 to the previous variance 1. A deterministic motion offset changes the mean but does not itself add variance."], ["The residual is weighted by relative precision", "Here H=1, so the innovation is z−μ⁻=3 and K=4/(4+R). Small R moves the estimate close to the reading; large R gives more weight to the predicted position. Posterior variance is 4R/(4+R), equivalently the inverse of total precision 1/4+1/R."], ["A likelihood curve is not another posterior", "The likelihood p(z=5|x) evaluates how compatible each possible x is with the fixed reading. In this particular identity-sensor model it happens to integrate to one over x; that is not a general property of likelihoods. The posterior comes from multiplying likelihood and prior, then normalizing."]],
    process: ["Propagate the previous estimate through the motion model and add process noise covariance.", "Compute the predicted observation, innovation covariance and Kalman gain.", "Correct the mean and covariance, then carry the posterior into the next prediction."],
    example: ["A precise sensor corrects a broad prediction", "Use R=1 m² after predicting N(2,4).", ["Innovation variance is 4+1=5 m²; gain is 4/5=0.8.", "The corrected mean is 2+0.8·(5−2)=4.4 m.", "The corrected variance is (1−0.8)·4=0.8 m², with standard deviation √0.8≈0.894427 m."], "The estimate is closer to the reading than the prediction because the sensor is more precise."],
    pitfalls: ["Putting a standard deviation where the equations require variance changes the gain and uncertainty calibration.", "Reusing correlated measurements as if their noise were independent double-counts information. Bias is not repaired merely by shrinking covariance."],
    implementation: ["Use linear solves rather than explicit matrix inverses. The Joseph covariance update (I−KH)P⁻(I−KH)ᵀ+KRKᵀ helps preserve symmetry and positive semidefiniteness in finite precision.", "Monitor innovations and their covariance for model mismatch. Exact linear-Gaussian filtering does not imply correct parameters, accurate timestamps or unbiased sensors."],
    outcomes: ["Compute a scalar prediction, innovation, gain and correction with units.", "Separate exact conditional inference from the credibility of its modelling assumptions."],
  }),
  [prob("extended-kalman-filter")]: reviewed({
    title: "Extended Kalman filter", labTitle: "A flat tangent can hide an informative measurement",
    summary: "The extended Kalman filter uses local Jacobians to propagate covariance and form approximate corrections in nonlinear state-space models. It evaluates nonlinear functions at the current estimate but replaces their uncertainty propagation with a first-order approximation. The resulting Gaussian summary is generally not the exact nonlinear posterior.",
    hook: "A tangent sees local slope; it can miss curvature across the uncertainty cloud.", model: "filter-extended", control: ["Prior mean μ", 0, 2, 0.05, 0],
    equation: "h(x)=x²; H=h′(μ)=2μ; K=H/(H²+1); μ⁺=μ+K(4−μ²); P⁺=1−KH",
    assumptions: "One measurement correction, not a full time-series simulation. The normalized prior is X∼N(μ,1), the sensor is Y=X²+V with independent V∼N(0,1), and the observed value is z=4. The control moves the linearization point μ. Curves show the actual sensor function, its tangent and the observation level; they are functions, not densities. The readout labels EKF updates as approximations.",
    takeaway: "A correct derivative is not enough when a first-order model discards important curvature. Check the uncertainty region, not only the linearization point.",
    prerequisites: [prob("kalman-filter"), math("jacobians"), math("taylor-approximation")], sources: [harvard, algorithms],
    ideas: [["The local sensor model is affine", "Around μ, x²≈μ²+2μ(x−μ). With prior variance one, this predicts measurement mean μ² and sensor-induced variance 4μ². Adding measurement noise gives innovation variance 4μ²+1. In contrast, Gaussian moments give exact predicted mean μ²+1 and measurement variance 4μ²+3."], ["At zero, slope misses magnitude information", "When μ=0, H=0, so K=0 and the EKF keeps mean 0 and variance 1 regardless of z. But z=4 favours magnitudes near two over magnitudes near zero. The true posterior density is proportional to exp(−x²/2−(4−x²)²/2), which has two modes at ±√3.5. Its symmetry keeps the exact posterior mean zero, yet its distribution is not unchanged."], ["The approximation can become overconfident", "At μ=1, H=2 and K=2/5, producing updated mean 2.2 and variance 0.2. These numbers follow the tangent model, not exact conditioning through x². A small approximate covariance does not certify that the nonlinear posterior is narrow or unimodal."]],
    process: ["Evaluate the nonlinear predicted state or observation at the current mean.", "Calculate the appropriate Jacobian there and use it for covariance propagation and gain calculation.", "Inspect whether the local linear model is credible over the current uncertainty region, especially near stationary points or ambiguities."],
    example: ["One omitted curvature term changes two moments", "Use μ=1, prior variance one and measurement-noise variance one.", ["EKF predicts E[Y]≈h(1)=1, but the exact predicted E[Y]=E[X²]=1²+1=2.", "The EKF innovation variance is 2²·1+1=5; the exact predicted measurement variance is 4·1²+2+1=7.", "For z=4, the EKF uses innovation 3, gain 0.4 and updated mean 2.2."], "Linearization errors enter both the innovation and the confidence assigned to it."],
    pitfalls: ["An unchanged mean at a symmetric operating point need not be wrong; an unchanged distribution or covariance can still be wrong.", "Iterating an EKF update is not a universal cure for multiple modes or a poor initial linearization."],
    implementation: ["Check analytic or automatic Jacobians against local changes of the actual model, and evaluate them at the correct predicted or corrected state for each step.", "Distinguish additive from non-additive noise: nonlinear noise injection may require its own Jacobian and covariance treatment."],
    outcomes: ["Derive a nonlinear sensor's EKF correction from its tangent.", "Identify curvature and symmetry failures without mistaking approximate covariance for exact uncertainty."],
  }),
  [prob("unscented-kalman-filter")]: reviewed({
    title: "Unscented Kalman filter", labTitle: "Move a few weighted points through the curve",
    summary: "The unscented Kalman filter approximates nonlinear moment propagation using deterministically selected sigma points and weights, then applies a mean/covariance correction. It does not require a Jacobian for this propagation. Sigma points are a numerical integration rule, not random posterior samples, and improved moment accuracy does not make a nonlinear posterior exactly Gaussian.",
    hook: "Move the points through the curve before averaging their outputs.", model: "filter-unscented", control: ["Prior standard deviation σ", 0.1, 2, 0.05, 1],
    equation: "χ=(1,1+σ,1−σ); wᵐ=(0,½,½); wᶜ=(2,½,½); E[X²]=1+P; Var(X²)=4P+2P², P=σ²",
    assumptions: "One scalar measurement transform and correction. Prior X∼N(1,σ²); h(x)=x²; independent additive measurement-noise variance R=1; reading z=4. Scaled unscented-transform settings are dimension 1, α=1, κ=0 and β=2, giving λ=0. The three sigma points are deterministic. Mean and covariance weights differ. Exact moment agreement shown here is specific to this quadratic/Gaussian example and these weights.",
    takeaway: "Sigma-point propagation can retain curvature terms missed by a tangent. Matching transformed moments still leaves a Gaussian conditioning approximation.",
    prerequisites: [prob("kalman-filter"), prob("extended-kalman-filter"), math("gaussian")], sources: [harvard, algorithms],
    ideas: [["Three evaluations retain curvature", "The outer points 1±σ have equal mean weights 1/2. Averaging their squares gives ((1+σ)²+(1−σ)²)/2=1+σ², exactly E[X²] for this prior. The centre has zero mean weight but is still evaluated, because its covariance weight is two."], ["Covariance weights are not probabilities", "Using the displayed covariance weights around transformed mean 1+P gives transformed variance 4P+2P². The central residual is −P; its weighted square contributes 2P². Covariance weights here sum to three, not one. Renormalizing them as probabilities would change the integration rule and destroy this result."], ["An exact transform does not imply an exact update", "For this prior, Cov(X,X²)=2P. Including R gives gain K=2P/(4P+2P²+1), mean update 1+K(4−(1+P)) and approximate variance P−K²(4P+2P²+1). These use exact predicted moments in this special example, yet the posterior through a squared sensor is not generally Gaussian. The covariance formula is a Gaussian-filter approximation, not the conditional variance guaranteed by Bayes' rule."]],
    process: ["Construct sigma points from the predicted mean and covariance using explicitly chosen transform parameters.", "Evaluate each point through the nonlinear measurement and combine outputs with the correct mean and covariance weights.", "Add the noise covariance, compute cross covariance and apply the approximate correction; assess remaining non-Gaussian structure."],
    example: ["Zero, one and two pass through a square", "Set σ=1, hence P=1. The ordered points are (1,2,0).", ["Their squared outputs are (1,4,0). Mean weights (0,0.5,0.5) produce measurement mean 2.", "Covariance weights (2,0.5,0.5) give 2·(1−2)²+0.5·(4−2)²+0.5·(0−2)²=6. Adding R gives 7.", "Cross covariance is 2, so K=2/7; the updated mean is 1+4/7=11/7 and approximate variance is 1−4/7=3/7."], "Curvature changes both predicted mean and variance compared with the first-order EKF."],
    pitfalls: ["UKF is not guaranteed to outperform EKF for every model, parameter choice or numerical regime.", "Exact low-order moments cannot represent multiple posterior modes; a single Gaussian summary can conceal sign ambiguity or other distinct explanations."],
    implementation: ["Keep mean and covariance weight arrays separate. Report α, β and κ instead of silently treating a particular sigma-point rule as universal.", "Use a stable covariance factorization and account for whether noise is additive or must be augmented into the sigma points. Square-root implementations can improve numerical robustness."],
    outcomes: ["Compute transformed moments from a specified sigma-point rule.", "Distinguish exact moment agreement in a special example from exact nonlinear filtering."],
  }),
};
for (const lesson of Object.values(kalmanLessons)) lesson.updatedAt = "2026-09-29";
