import { math, source, reviewed } from "./lesson-helpers.mjs";
const mit = source("MIT 18.06: Linear Algebra lectures", "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/video_galleries/video-lectures/");
const np = (name) => source(`NumPy: ${name}`, `https://numpy.org/doc/stable/reference/generated/numpy.${name}.html`);
const mml = source("Deisenroth, Faisal, and Ong: Mathematics for Machine Learning", "https://mml-book.github.io/");
const labTitles = {
  "la-shape": "Count the tensor slices", "la-span": "Build a vector from two directions",
  "la-independence": "Collapse a dimension", "la-dot": "Measure the alignment",
  "la-product": "Multiply, then reverse the order", "la-norms": "Three rulers for one vector",
  "la-similarity": "Same direction, different distance", "la-orthogonal": "Rotate the coordinate rulers",
  "la-projection": "Projection and residual", "la-rank": "Which directions disappear?",
  "la-trace-det": "Stretch, flip, collapse", "la-psd": "Sweep the quadratic form",
  "la-svd": "From circle to ellipse", "la-low-rank": "Keep the strongest directions",
  "la-sparse": "When does sparse storage win?", "la-gradient": "One weight, four sensitivities",
  "la-jacobian": "Sensitivity versus curvature", "la-kronecker": "A matrix of scaled blocks",
  "la-einsum": "Follow the contracted index", "la-conditioning": "Amplify a tiny error",
};

export const linearAlgebraLessons = {
  [math("scalars-vectors-matrices-and-tensors")]: reviewed({
    title: "Scalars, vectors, matrices, and tensors",
    summary: "Scalars, vectors, and matrices have zero, one, and two indexed axes in array notation. Machine-learning libraries use tensor for a numerical array with any number of axes; axis meaning and shape determine valid operations.",
    hook: "Name each axis before you multiply its sizes.", model: "la-shape", control: ["Batch size", 1, 8, 1, 2],
    equation: "entries=∏ᵢ shapeᵢ; payload bytes=entries × bytes per entry",
    assumptions: "A contiguous float32 array has shape (batch,2,3). Each table is one 2×3 slice. Memory counts include only numerical payload, not object metadata, gradients, or copies.",
    takeaway: "Array order counts axes; matrix rank counts independent columns. They are different meanings of rank, and neither is the number of entries.",
    sources: [np("ndarray"), mml],
    ideas: [["Coordinates and meaning", "An axis can represent examples, time, channels, or features. Two arrays with the same shape can still have incompatible meanings if their axes are ordered differently."], ["Mathematical versus library tensors", "In multilinear algebra, a tensor is a coordinate-independent object with a specified transformation law. Calling every array a tensor in code is a useful convention, not that entire mathematical definition."]],
    process: ["Write the shape and semantic name of every axis.", "Check whether the next operation preserves, sums, or reorders each axis.", "Multiply dimensions for the element count, then apply the dtype's storage size."],
    example: ["A small batched feature array", "Two examples each have two rows and three features, stored as float32.", ["The shape is (2,2,3), so the array has three axes.", "It contains 2×2×3=12 scalars.", "At four bytes per scalar, the contiguous data payload is 48 bytes."], "Changing the batch size changes payload linearly; it does not change the number of axes."],
    pitfalls: ["A reshape can preserve element count while mixing semantic axes incorrectly; a transpose reorders axes instead.", "Broadcasting can silently expand an operation and produce an unintended result even when no shape error is raised."],
    implementation: ["Annotate boundaries with named shape contracts, such as (batch,time,features).", "Check dtype and strides when estimating memory; views may share storage while materialized copies do not."],
    outcomes: ["Distinguish shape, order, element count, and matrix rank.", "Estimate payload memory while keeping axis semantics explicit."],
  }),
  [math("vector-spaces-subspaces-span-basis-and-dimension")]: reviewed({
    title: "Vector spaces, subspaces, span, basis, and dimension",
    summary: "A vector space is closed under vector addition and scalar multiplication over a chosen field. A span contains every linear combination of given vectors; a basis spans a space without redundant vectors, and its size is the dimension.",
    hook: "Spanning gives reach; independence gives unique coordinates.", model: "la-span", control: ["Coefficient a of u", -2, 2, 0.1, 1],
    equation: "span(u,v)={au+bv : a,b∈R}; u=(1,0), v=(1,1)",
    assumptions: "Real vectors in R². The displayed slice fixes b=1 and varies a; varying both coefficients would fill the plane. The two columns have determinant 1.",
    takeaway: "A basis allows one coordinate tuple for every vector in its space. The slider shows only one slice of a two-dimensional span, not the entire span.",
    prerequisites: [math("scalars-vectors-matrices-and-tensors")], sources: [mit, mml],
    ideas: [["Subspace test", "A subspace contains zero and is closed under addition and scalar multiplication. A line through the origin qualifies; a parallel line not through the origin generally does not."], ["Coordinates depend on the basis", "The physical vector can stay fixed while its coordinate tuple changes with the basis. Dimension describes the space, not a particular redundant list of spanning vectors."]],
    process: ["Specify the scalar field and ambient space.", "Form all allowed linear combinations to describe the span.", "Check independence before treating coefficients as unique coordinates."],
    example: ["Two coordinates for one location", "Use u=(1,0) and v=(1,1) to represent x=(3,2).", ["The second coordinate of au+bv=(a+b,b) gives b=2.", "The first coordinate then gives a+2=3, so a=1."], "The coordinates in the (u,v) basis are (1,2), while standard coordinates are (3,2)."],
    pitfalls: ["A spanning set can contain more vectors than the space's dimension.", "Affine combinations or translations are not automatically linear combinations in a subspace."],
    implementation: ["Store a basis as columns and solve Bc=x for coordinates.", "Use numerical rank tests when columns are nearly dependent instead of assuming the coordinate solve is stable."],
    outcomes: ["Test a subspace and distinguish a span from a basis.", "Recover coordinates in a specified basis and identify the space's dimension."],
  }),
  [math("linear-independence")]: reviewed({
    title: "Linear independence", summary: "Vectors are linearly independent when their zero linear combination requires every coefficient to be zero. Equivalently, no vector in the set is a linear combination of the others.",
    hook: "If a direction adds no new reach, its coefficient is redundant.", model: "la-independence", control: ["Column separation ε", -1, 1, 0.05, 0.5],
    equation: "Ac=0 ⇒ c=0; A=[[1,1],[1,1+ε]], det(A)=ε",
    assumptions: "Two real columns u=(1,1) and v=(1,1+ε). Independence is evaluated in exact arithmetic; near-zero ε can be numerically difficult even when nonzero.",
    takeaway: "At ε=0 the parallelogram collapses to a line. At small nonzero ε the columns are independent but nearly redundant numerically.",
    prerequisites: [math("vector-spaces-subspaces-span-basis-and-dimension")], sources: [mit, np("linalg.matrix_rank")],
    ideas: [["The homogeneous system", "Put the vectors in a matrix A as columns. A nonzero solution of Ac=0 is an explicit dependency among them."], ["Exact and numerical questions", "Exact independence is binary. A tolerance-based numerical rank estimates which directions can be reliably resolved at the data's precision and noise level."]],
    process: ["Arrange the proposed vectors as columns.", "Solve the homogeneous system or inspect the singular values.", "For numerical data, state the rank threshold and compare it with measurement uncertainty."],
    example: ["A collapsing pair", "Take u=(1,1) and v=(1,1+ε).", ["At ε=0, u−v=0 uses nonzero coefficients (1,−1), proving dependence.", "At ε=0.5 the determinant is 0.5, so only the zero coefficients map to zero."], "One changed entry creates a second independent direction, but tiny changes may be unreliable to recover."],
    pitfalls: ["Testing a floating-point determinant for exact equality with zero is not a robust general rank test.", "More than n vectors in Rⁿ cannot be independent, regardless of how different they look."],
    implementation: ["Use singular values or a rank-revealing factorization for numerical rank.", "Inspect feature scaling before applying one absolute tolerance across very different column magnitudes."],
    outcomes: ["Exhibit a nontrivial zero combination to prove dependence.", "Separate exact independence from numerical resolvability."],
  }),
  [math("dot-products-and-inner-product-spaces")]: reviewed({
    title: "Dot products and inner-product spaces", summary: "The Euclidean dot product sums coordinatewise products. It defines lengths, angles, and projections; a general inner product provides the same geometric structure with an explicitly chosen positive-definite rule.",
    hook: "Multiply the lengths, then keep the aligned fraction.", model: "la-dot", control: ["Angle θ", 0, 180, 1, 60, "°"],
    equation: "uᵀv=Σᵢuᵢvᵢ=‖u‖₂‖v‖₂cosθ",
    assumptions: "Real Euclidean vectors u=(2,0) and v=(cosθ,sinθ). The second vector is unit length, so the dot product is 2cosθ. Coordinates are dimensionless.",
    takeaway: "Dot product combines direction and magnitude. Dividing by both nonzero lengths removes magnitude and gives cosine similarity.",
    prerequisites: [math("scalars-vectors-matrices-and-tensors")], sources: [np("dot"), mml],
    ideas: [["Inner-product axioms", "For real vectors, an inner product is bilinear, symmetric, and positive definite. With a symmetric positive-definite M, uᵀMv gives a different geometry from the ordinary dot product."], ["Complex coordinates", "Complex inner products conjugate one argument. Which argument is conjugate-linear is a convention that must match the implementation."]],
    process: ["Choose the geometry: ordinary Euclidean or a specified weighted inner product.", "Multiply matched coordinates and sum for the Euclidean case.", "Normalize by lengths only when a direction-only comparison is intended."],
    example: ["A sixty-degree alignment", "Let u=(2,0) and v=(1/2,√3/2).", ["uᵀv=2×(1/2)+0×(√3/2)=1.", "The lengths are 2 and 1, so cosθ=1/(2×1)=1/2."], "The angle is 60° even though the raw dot product is 1 rather than 1/2."],
    pitfalls: ["A large dot product can come from a large vector norm rather than strong directional agreement.", "A zero vector has zero dot product with everything, but its angle and cosine similarity are undefined."],
    implementation: ["Specify which axes are reduced in batched dot products.", "Use a conjugating inner-product routine for complex data when required by the chosen convention."],
    outcomes: ["Compute alignment from coordinates and from an angle.", "Distinguish a dot product from normalized similarity and from a weighted inner product."],
  }),
  [math("matrix-multiplication-and-tensor-contraction")]: reviewed({
    title: "Matrix multiplication and tensor contraction", summary: "Matrix multiplication sums products over a shared inner axis. Tensor contraction extends this idea to specified axes of higher-order arrays while preserving the remaining axes.",
    hook: "Match the shared index, multiply, sum it away.", model: "la-product", control: ["Entry B₀₀", -2, 3, 0.25, 1],
    equation: "Cᵢⱼ=Σₖ AᵢₖBₖⱼ; (m×k)(k×n)→m×n",
    assumptions: "Real 2×2 examples A=[[1,2],[0,1]] and B=[[t,0],[1,2]]. The live tables show ordinary matrix products, not elementwise multiplication.",
    takeaway: "The contracted index disappears from the output. Changing multiplication order generally changes both the transformation and the result.",
    prerequisites: [math("dot-products-and-inner-product-spaces")], sources: [np("matmul"), np("tensordot")],
    ideas: [["Composition", "With column vectors, ABx applies B first and A second. The columns of AB are A applied to the columns of B."], ["Batch axes are not contraction axes", "Batched multiplication keeps batch indices and contracts feature indices. Broadcasting compatible batches does not justify summing across different examples."]],
    process: ["Label the input and output axes before writing a product.", "Match the inner dimensions and calculate one output entry as a row-column dot product.", "Check output shape and operation order against the intended composition."],
    example: ["Order changes the answer", "Set t=1, so B=[[1,0],[1,2]].", ["AB=[[1×1+2×1,1×0+2×2],[0×1+1×1,0×0+1×2]]=[[3,4],[1,2]].", "BA=[[1,2],[1,4]]."], "AB and BA are both defined here, but they are different matrices."],
    pitfalls: ["Elementwise multiplication does not compose linear maps.", "A one-dimensional array may be treated differently from an explicit row or column matrix; inspect shapes at API boundaries."],
    implementation: ["Use matrix-product operators and explicit axis notation for contractions.", "Check one small entry by hand before optimizing a large batched contraction."],
    outcomes: ["Derive output shape and one matrix-product entry.", "Distinguish contraction, broadcasting, and elementwise multiplication."],
  }),
  [math("norms")]: reviewed({
    title: "Norms", summary: "A norm measures size while satisfying positivity, absolute homogeneity, and the triangle inequality. Vector norms and matrix norms answer different questions about coordinates and linear operators.",
    hook: "Choose the ruler before comparing the sizes.", model: "la-norms", control: ["First coordinate x", -4, 4, 0.1, 4],
    equation: "‖v‖₁=Σ|vᵢ|; ‖v‖₂=√Σvᵢ²; ‖v‖∞=max|vᵢ|",
    assumptions: "The example vector is v=(x,3). The plot compares three vector norms over the same coordinates and units. It does not treat a flattened matrix norm as an operator norm.",
    takeaway: "For (4,3), L₁=7, L₂=5, and L∞=4. A reported norm needs its definition and reduction axes to be interpretable.",
    prerequisites: [math("dot-products-and-inner-product-spaces")], sources: [np("linalg.norm"), mml],
    ideas: [["Matrix Frobenius norm", "The Frobenius norm is the square root of the sum of squared entry magnitudes. It measures all-entry error and equals the Euclidean norm of a flattened matrix."], ["Spectral norm", "The induced matrix 2-norm is the largest singular value: the largest output length produced from a unit Euclidean input. It need not equal the Frobenius norm."]],
    process: ["Specify whether the object is a vector, matrix, or batch.", "Choose the norm corresponding to the desired notion of error or amplification.", "Reduce only the intended axes and retain the measurement units."],
    example: ["Two different matrix sizes", "Take A=diag(3,4).", ["Its Frobenius norm is √(3²+4²)=5.", "Its spectral norm is max(3,4)=4."], "The largest stretch is four, although the total squared-entry size has square root five."],
    pitfalls: ["The so-called L₀ norm counts nonzero entries but fails absolute homogeneity, so it is not a norm.", "A small unscaled residual may hide a large relative error when the reference quantity is itself tiny."],
    implementation: ["Pass explicit norm order and axes when library defaults could be ambiguous.", "Scale inputs or use stable norm routines to avoid overflowing squares of very large coordinates."],
    outcomes: ["Compute L₁, L₂, and L∞ sizes of a vector.", "Separate Frobenius error from worst-direction operator amplification."],
  }),
  [math("distance-and-similarity-metrics")]: reviewed({
    title: "Distance and similarity metrics", summary: "A distance metric obeys nonnegativity, identity of indiscernibles, symmetry, and the triangle inequality. Similarity scores need not satisfy those axioms; cosine similarity and Euclidean distance encode different comparisons.",
    hook: "Same direction can still be far away.", model: "la-similarity", control: ["Positive scale c", 0.1, 3, 0.1, 2],
    equation: "d₂(u,v)=‖u−v‖₂; cos(u,v)=uᵀv/(‖u‖₂‖v‖₂)",
    assumptions: "u=(1,1) and v=c·u with c>0. Both vectors are nonzero. The live example changes magnitude while preserving direction.",
    takeaway: "Cosine similarity is one for positive multiples, even when Euclidean distance is large. The choice depends on whether magnitude should carry meaning.",
    prerequisites: [math("norms")], sources: [source("SciPy: cosine distance", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html"), mml],
    ideas: [["Normalized embeddings", "For unit vectors, squared Euclidean distance equals 2(1−cosθ). This identity explains equivalent rankings under normalization, not equivalence for arbitrary unnormalized data."], ["Cosine distance is not generally a metric", "1−cosθ can violate the triangle inequality. For directions at 0°, 60°, and 120°, the long pair has value 1.5 while the two adjacent values sum to 1."]],
    process: ["Decide whether vector scale should affect the comparison.", "Normalize only if the task calls for directional information.", "Check zero-vector behavior and any assumptions made by the retrieval or indexing algorithm."],
    example: ["A rescaled embedding", "Use u=(1,1) and v=(2,2).", ["Their dot product is 4 and their norm product is √2×√8=4, giving cosine 1.", "Their difference is (1,1), giving Euclidean distance √2."], "The vectors coincide in direction but are not identical points."],
    pitfalls: ["Cosine similarity is undefined at zero norm without an implementation-specific convention.", "Squared Euclidean distance also fails the triangle inequality; it should not be assumed to be a metric."],
    implementation: ["Apply the same normalization at indexing and query time.", "Check whether larger or smaller scores mean better matches before sorting results."],
    outcomes: ["Choose a comparison based on whether magnitude matters.", "Recognize that a score called distance may not satisfy metric axioms."],
  }),
  [math("orthogonality-and-orthonormal-bases")]: reviewed({
    title: "Orthogonality and orthonormal bases", summary: "Orthogonal vectors have zero inner product. An orthonormal basis combines orthogonality with unit lengths, making coordinates obtainable by inner products and preserving Euclidean lengths under a square basis change.",
    hook: "Independent unit rulers let you read each coordinate directly.", model: "la-orthogonal", control: ["Basis rotation θ", 0, 180, 1, 45, "°"],
    equation: "QᵀQ=I; c=Qᵀx; ‖c‖₂=‖x‖₂ for square orthogonal Q",
    assumptions: "Q is a real 2×2 rotation matrix with columns (cosθ,sinθ) and (−sinθ,cosθ). The fixed vector is x=(2,1). Both coordinate axes use the same scale.",
    takeaway: "The basis rotates and the coordinate values change, while x's squared length stays five. Orthogonal columns alone need normalization before Qᵀ gives inverse coordinates.",
    prerequisites: [math("dot-products-and-inner-product-spaces"), math("vector-spaces-subspaces-span-basis-and-dimension")], sources: [mit, np("linalg.qr")],
    ideas: [["Square versus rectangular Q", "Orthonormal columns give QᵀQ=I. For rectangular Q, QQᵀ is a projector onto its column space rather than the identity on the larger ambient space."], ["Finding the basis", "Gram-Schmidt removes components in earlier directions, then normalizes. Stable QR implementations often use Householder transformations."]],
    process: ["Check each basis vector's length and pairwise inner products.", "Calculate the coordinates by applying Qᵀ.", "Reconstruct Qc and check the residual against x, allowing a projection residual for a proper subspace."],
    example: ["A 45° basis", "Let q₁=(1,1)/√2 and q₂=(−1,1)/√2, with x=(2,1).", ["c₁=q₁ᵀx=3/√2 and c₂=q₂ᵀx=−1/√2.", "The squared coordinate length is 9/2+1/2=5, equal to 2²+1²."], "Orthonormal coordinates preserve length even when their individual values change."],
    pitfalls: ["Linear independence alone does not make vectors orthogonal.", "A tall matrix with orthonormal columns cannot reconstruct every vector in its output space without projection error."],
    implementation: ["Use a QR factorization instead of unstable hand-written classical Gram-Schmidt for difficult data.", "Measure both orthogonality error ‖QᵀQ−I‖ and reconstruction error."],
    outcomes: ["Read coordinates in an orthonormal basis using inner products.", "Distinguish an orthogonal change of basis from a subspace projection."],
  }),
  [math("projections")]: reviewed({
    title: "Projections", summary: "An orthogonal projection maps a vector to the closest point in a linear subspace under Euclidean distance. Its residual lies perpendicular to every direction in that subspace.",
    hook: "Keep the component along the subspace; leave a perpendicular residual.", model: "la-projection", control: ["Subspace angle θ", 0, 180, 1, 45, "°"],
    equation: "p=uuᵀx for ‖u‖₂=1; uᵀ(x−p)=0; P²=P=Pᵀ",
    assumptions: "Project x=(2,1) onto the line spanned by the real unit vector u=(cosθ,sinθ). The displayed residual joins the projected endpoint to x.",
    takeaway: "Projection length and residual length trade off, but their squared lengths add to ‖x‖²=5 because the components are orthogonal.",
    prerequisites: [math("orthogonality-and-orthonormal-bases")], sources: [mit, np("linalg.lstsq")],
    ideas: [["More than one direction", "If Q has orthonormal columns, QQᵀ projects onto their span. For a full-column-rank basis B, the equivalent expression is B(BᵀB)⁻¹Bᵀ."], ["Idempotence is not enough", "Any projection satisfies P²=P. An orthogonal projection additionally has Pᵀ=P; oblique projections need not minimize Euclidean distance."]],
    process: ["Represent the target subspace using an orthonormal basis.", "Calculate inner-product coordinates and reconstruct the projected vector.", "Verify that the residual is orthogonal to the subspace and projecting again changes nothing."],
    example: ["Projection onto the diagonal", "For u=(1,1)/√2 and x=(2,1):", ["The coefficient uᵀx=3/√2 gives p=(1.5,1.5).", "The residual is (0.5,−0.5), whose dot product with u is zero.", "‖p‖²=4.5 and ‖x−p‖²=0.5."], "The two squared lengths sum to five, and p is the closest point on the diagonal line."],
    pitfalls: ["An affine plane not through the origin requires subtracting and restoring an offset.", "Forming BᵀB can square the condition number; the explicit inverse formula is a mathematical identity, not the preferred implementation."],
    implementation: ["Use QR or SVD-based least squares and obtain the fitted vector from the solution.", "Test orthogonality of the residual as well as its norm."],
    outcomes: ["Compute a projection and its orthogonal residual.", "Connect projection geometry with least-squares fitting and numerical stability."],
  }),
  [math("rank-and-null-space")]: reviewed({
    title: "Rank and null space", summary: "The rank of A:Rⁿ→Rᵐ is the dimension of its image. Its null space contains inputs mapped to zero. Rank plus nullity equals n, the dimension of the domain.",
    hook: "Count the directions that survive and the directions that disappear.", model: "la-rank", control: ["Second diagonal value t", -1, 1, 0.05, 1],
    equation: "rank(A)+dim ker(A)=n; A=[[1,0,0],[0,t,0]]",
    assumptions: "A maps R³ into R². The third input coordinate always disappears. At t=0 the second coordinate disappears as well. Rank is evaluated in exact arithmetic.",
    takeaway: "A nontrivial null space means different inputs can produce the same output. In this example the domain dimension is three, not the number of matrix rows.",
    prerequisites: [math("linear-independence"), math("matrix-multiplication-and-tensor-contraction")], sources: [mit, np("linalg.matrix_rank")],
    ideas: [["Solutions with freedom", "If Ax=b has one solution x₀, all solutions are x₀+z with z in ker(A). Null directions describe ambiguity that output measurements cannot resolve."], ["Four related spaces", "Column space and left null space lie in Rᵐ; row space and null space lie in Rⁿ. The row space is orthogonal to the null space."]],
    process: ["State the domain and codomain dimensions.", "Find independent columns or count nonzero singular values.", "Solve Ax=0 and check its number of free dimensions against rank-nullity."],
    example: ["A discarded input coordinate", "Set t=1, giving A=[[1,0,0],[0,1,0]].", ["A(x₁,x₂,x₃)=(x₁,x₂), so the image is all R² and rank is 2.", "The null space consists of (0,0,s); its dimension is 1."], "Rank plus nullity is 2+1=3. Turning t to zero changes the split to 1+2=3."],
    pitfalls: ["Rank is not the number of nonzero matrix entries.", "A tiny singular value may indicate an unresolved direction rather than an exactly missing one."],
    implementation: ["Report the singular-value tolerance used for numerical rank.", "For underdetermined systems, state the rule used to select one solution, such as minimum norm or regularization."],
    outcomes: ["Use rank-nullity with the correct domain dimension.", "Describe nonunique solutions using a null-space basis."],
  }),
  [math("trace-and-determinant")]: reviewed({
    title: "Trace and determinant", summary: "Trace is the sum of a square matrix's diagonal entries. Determinant is its signed volume-scaling factor. Both are invariant under a change of basis, but they summarize different properties of a transformation.",
    hook: "Add the stretches for trace; multiply them for signed volume.", model: "la-trace-det", control: ["Second-axis scale t", -2, 2, 0.1, 1],
    equation: "tr(A)=ΣᵢAᵢᵢ; det(diag(2,t))=2t",
    assumptions: "The real 2×2 matrix A=diag(2,t) maps a unit square to a rectangle. Determinant carries orientation; geometric area is its absolute value.",
    takeaway: "Zero determinant collapses volume and means a square map is singular. Zero trace does not imply singularity.", prerequisites: [math("matrix-multiplication-and-tensor-contraction")], sources: [mit, np("linalg.det")],
    ideas: [["Basis-invariant summaries", "Trace equals the sum and determinant the product of eigenvalues, counted with algebraic multiplicity. This remains true even when the matrix is not diagonalizable."], ["Composition", "det(AB)=det(A)det(B). Trace instead satisfies tr(AB)=tr(BA) for compatible shapes; it is not generally the product of traces."]],
    process: ["Check that the matrix is square.", "Separate signed determinant from absolute volume change.", "Use an explicit image of a square or cube to check the interpretation."],
    example: ["Reflection with expansion", "Take A=diag(2,−1).", ["The trace is 2−1=1 and determinant is −2.", "The square becomes a rectangle with area 2 and reversed orientation."], "At t=−2 the trace is zero, but determinant −4 still makes A invertible."],
    pitfalls: ["A determinant's magnitude alone is not a reliable conditioning test: scaling changes it dramatically.", "Trace does not determine the full spectrum or the shape of a transformed region."],
    implementation: ["Use a log-determinant routine for products liable to overflow or underflow.", "Use singular values, not a determinant threshold alone, to assess numerical rank."],
    outcomes: ["Distinguish trace, signed volume, and invertibility.", "Explain why a zero trace need not indicate lost dimensions."],
  }),
  [math("positive-semidefinite-matrices")]: reviewed({
    title: "Positive-semidefinite matrices", summary: "A real symmetric matrix is positive semidefinite when its quadratic form is nonnegative in every direction. Equivalently, all its eigenvalues are nonnegative. Covariance and Gram matrices have this structure.",
    hook: "Sweep every direction: a PSD matrix never dips below zero.", model: "la-psd", control: ["Second eigenvalue t", -2, 2, 0.1, 1],
    equation: "A⪰0 ⇔ xᵀAx≥0 for all x ⇔ λmin(A)≥0, for symmetric A",
    assumptions: "A=diag(1,t). The graph evaluates the quadratic form on unit vectors (cosθ,sinθ); opposite directions give the same value.",
    takeaway: "Positive entries are neither necessary nor sufficient for positive semidefiniteness. The condition concerns all directions, not individual cells.", prerequisites: [math("eigenvalues-and-eigenvectors"), math("dot-products-and-inner-product-spaces")], sources: [mit, np("linalg.eigvalsh")],
    ideas: [["Gram structure", "For any real B, xᵀBᵀBx=‖Bx‖²≥0. Thus BᵀB is PSD, and is positive definite precisely when B has independent columns."], ["Curvature and covariance", "Covariance is PSD because aᵀCov(X)a is a variance. A twice continuously differentiable convex function has a PSD Hessian on an open convex domain."]],
    process: ["Verify symmetry before applying the eigenvalue characterization.", "Inspect the smallest eigenvalue with a scale-aware tolerance.", "Distinguish strictly positive curvature from flat zero-eigenvalue directions."],
    example: ["A flat direction becomes a descent direction", "Set t=0 in diag(1,t).", ["The form x₁² is nonnegative but vanishes along the second axis.", "Changing t to −1 gives x₁²−x₂², which is −1 at (0,1)."], "The first matrix is singular PSD; the second is indefinite, not negative definite."],
    pitfalls: ["Checking a few sampled vectors cannot certify PSD for a general matrix.", "Standard Cholesky routines typically require positive definiteness, not merely semidefiniteness."],
    implementation: ["For a symmetric problem, use symmetric eigensolvers and inspect asymmetry separately.", "Report any diagonal jitter added for factorization: it changes the model's covariance or curvature."],
    outcomes: ["Relate quadratic forms, eigenvalues, and Gram matrices.", "Distinguish PSD, positive definite, and indefinite matrices."],
  }),
  [math("singular-value-decomposition")]: reviewed({
    title: "Singular value decomposition", summary: "Every real m×n matrix has an SVD A=UΣVᵀ. Orthogonal input and output directions reveal its nonnegative stretches, including for rectangular matrices that have no ordinary eigendecomposition.",
    hook: "Follow a unit circle through a rectangular map and read its elliptical stretches.", model: "la-svd", control: ["Input direction θ", 0, 360, 1, 30, "°"],
    equation: "A=UΣVᵀ; Avᵢ=σᵢuᵢ; σᵢ²=λᵢ(AᵀA)",
    assumptions: "The 3×2 example maps into the plane z=0. Reduced U has two orthonormal columns, Σ=diag(3,2), and Vᵀ=I. The plot shows only the first two output coordinates.",
    takeaway: "Singular values describe stretch magnitudes; input and output directions live in different spaces. Reduced U need not be square.", prerequisites: [math("orthogonality-and-orthonormal-bases"), math("rank-and-null-space")], sources: [mit, np("linalg.svd")],
    ideas: [["Rectangular geometry", "A unit sphere maps to an ellipsoid, possibly with collapsed axes. Its nonzero semiaxis lengths are the singular values; their count is the rank."], ["Signs are not unique", "Flipping both uᵢ and vᵢ leaves their contribution unchanged. Repeated singular values also permit different bases within the corresponding subspaces."]],
    process: ["Write the dimensions of every factor before multiplying.", "Check orthonormal columns and reconstruct A.", "Interpret small singular values as weakly transmitted directions rather than negative eigenvalues."],
    example: ["A 3-by-2 map", "Take columns (3/√2,3/√2,0) and (−2/√2,2/√2,0).", ["Their squared lengths are 9 and 4, and their dot product is zero.", "Therefore AᵀA=diag(9,4), giving singular values 3 and 2.", "At θ=90°, the output is (−√2,√2,0), with length 2."], "The input circle becomes an ellipse rotated 45° inside a two-dimensional output plane."],
    pitfalls: ["SVD is not restricted to symmetric or square matrices.", "Forming AᵀA explicitly can worsen numerical accuracy by squaring its condition number."],
    implementation: ["Request reduced factors when full null-space bases are unnecessary.", "Check reconstruction residuals and subspaces rather than expecting identical factor signs across implementations."],
    outcomes: ["Interpret singular vectors and values for a rectangular map.", "Check reduced-factor dimensions and reconstruction."],
  }),
  [math("low-rank-approximation")]: reviewed({
    title: "Low-rank approximation", summary: "Truncating an SVD to its k largest singular values gives a best rank-at-most-k approximation in spectral and Frobenius norms. The discarded singular values quantify the approximation error.",
    hook: "Discard directions, then measure exactly what was lost.", model: "la-low-rank", control: ["Retained directions k", 0, 3, 1, 1],
    equation: "Aₖ=Σᵢ₌₁ᵏσᵢuᵢvᵢᵀ; ‖A−Aₖ‖F²=Σᵢ>ₖσᵢ²",
    assumptions: "A=diag(4,2,1) has distinct singular values. The retained squared norm is measured against 4²+2²+1²=21. This is approximation energy, not task accuracy.",
    takeaway: "The biggest discarded singular value sets spectral error; all discarded squared singular values contribute to Frobenius error.", prerequisites: [math("singular-value-decomposition"), math("norms")], sources: [mit, mml],
    ideas: [["Two error questions", "Spectral norm measures the largest error over unit input directions. Frobenius norm sums squared entrywise errors and can penalize many small residual directions."], ["Compression is contextual", "A dense m×n matrix costs mn entries; factor storage for rank k costs about k(m+n+1). Very small matrices or large k may offer no storage saving."]],
    process: ["Choose a norm and an error budget tied to the application.", "Inspect the decay of singular values and select k.", "Measure downstream performance separately from matrix reconstruction."],
    example: ["Keep one of three directions", "For diag(4,2,1), keep only the first singular direction.", ["The approximation is diag(4,0,0); residual is diag(0,2,1).", "Frobenius error is √5, spectral error is 2, and retained squared norm is 16/21≈76.19%."], "Keeping two directions reduces both residual norms to 1."],
    pitfalls: ["A small reconstruction error need not preserve rare but important predictive directions.", "Low-rank approximation is optimal only relative to its stated norm and rank constraint; it is not automatically the best denoiser."],
    implementation: ["For large matrices, compare truncated or randomized methods against a residual estimate.", "Center the data when interpreting SVD as conventional PCA of sample variation."],
    outcomes: ["Compute spectral and Frobenius truncation errors.", "Separate retained matrix energy from application quality."],
  }),
  [math("sparse-matrices")]: reviewed({
    title: "Sparse matrices", summary: "Sparse formats store selected entries and their locations rather than allocating every cell. They save memory and computation only when the sparsity pattern, index overhead, and supported operations make that worthwhile.",
    hook: "Zeros are free only after you pay for the address book.", model: "la-sparse", control: ["Stored nonzeros", 0, 25, 1, 5],
    equation: "CSR bytes = nnz·(value bytes + index bytes) + (rows+1)·pointer bytes",
    assumptions: "The toy matrix is 5×5. Values are float64 (8 bytes); column indices and row pointers are int32 (4 bytes). No object overhead, explicit zeros, or duplicate coordinates are included.",
    takeaway: "Sparse storage has a break-even density. Sparse computation also depends on access patterns, not just the percentage of zeros.", prerequisites: [math("scalars-vectors-matrices-and-tensors")], sources: [source("SciPy sparse arrays", "https://docs.scipy.org/doc/scipy/reference/sparse.html"), source("SciPy CSR representation", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_array.html")],
    ideas: [["CSR layout", "Compressed sparse row format stores values, their column indices, and a row-pointer array. Adjacent pointers delimit the entries belonging to one row."], ["Format follows access", "COO is useful for assembling coordinate contributions; CSR favors row-oriented operations; CSC favors column-oriented access. Conversion and fill-in have costs."]],
    process: ["Measure nnz, index width, and the operation you need.", "Estimate payload and factorization fill-in before selecting a format.", "Benchmark the complete computation, including conversions."],
    example: ["A payload crossover", "A dense 5×5 float64 matrix uses 25×8=200 bytes.", ["At 5 nonzeros, CSR uses 5×12+6×4=84 bytes.", "At 14 nonzeros it uses 192 bytes; at 15 it uses 204 bytes."], "CSR stops saving payload space between 14 and 15 stored entries under these assumptions."],
    pitfalls: ["Stored entries can include explicit zeros, so stored nnz need not equal the mathematical nonzero count.", "Sparse inputs can produce dense outputs or substantial factorization fill-in."],
    implementation: ["For SciPy sparse arrays, distinguish elementwise multiplication from matrix multiplication with @.", "Inspect data, indices, and indptr byte counts rather than inferring real memory from density alone."],
    outcomes: ["Calculate sparse-format storage overhead.", "Choose a representation based on operations and structure."],
  }),
  [math("matrix-calculus")]: reviewed({
    title: "Matrix calculus", summary: "Matrix calculus organizes derivatives with respect to array-valued parameters. For a scalar loss, the gradient has the parameter's shape and converts a small parameter perturbation into a first-order change in loss.",
    hook: "Every weight gets a sensitivity; collect them in a matrix of the same shape.", model: "la-gradient", control: ["Weight W₀₀", -1, 2, 0.05, 1],
    equation: "L=½‖Wx−y‖₂²; ∇WL=(Wx−y)xᵀ; dL=tr((∇WL)ᵀdW)",
    assumptions: "W=[[t,1],[0,1]], x=(1,2), y=(1,1). Only W₀₀ varies in the plot, but the table shows the full gradient at that W. All variables are real.",
    takeaway: "The plotted slope is one gradient entry, not the entire gradient. Shapes expose many transpose and broadcasting mistakes.", prerequisites: [math("matrix-multiplication-and-tensor-contraction"), math("dot-products-and-inner-product-spaces")], sources: [mml, source("MIT matrix calculus course", "https://github.com/mitmath/matrixcalc")],
    ideas: [["Differentials first", "Write r=Wx−y and dL=rᵀ(dW)x. Reordering this scalar as a trace identifies the gradient r xᵀ without differentiating each index separately."], ["Batches and reduction", "For columns of examples X and targets Y, a summed squared-error objective has gradient (WX−Y)Xᵀ. Averaging adds the corresponding normalization factor."]],
    process: ["Record parameter, input, output, and gradient dimensions.", "Differentiate the scalar loss using a differential or chain rule.", "Compare a directional derivative to a small finite-difference perturbation."],
    example: ["One weight slice", "Set t=1: W=[[1,1],[0,1]].", ["Wx=(3,2), so residual=(2,1) and loss=(4+1)/2=2.5.", "The outer product (2,1)(1,2) gives gradient [[2,4],[1,2]]."], "The slope when moving W₀₀ alone is 2; updating all weights follows all four entries."],
    pitfalls: ["A mean loss and a sum loss produce gradients with different scale.", "Broadcasting can yield a plausible array with the wrong intended derivative."],
    implementation: ["Check automatic derivatives against a directional finite difference on a small smooth example.", "Use double precision and several perturbation sizes for derivative checks; very small differences suffer cancellation."],
    outcomes: ["Derive the squared-error matrix gradient.", "Separate a one-parameter slice from the full gradient."],
  }),
  [math("jacobians-and-hessians")]: reviewed({
    title: "Jacobians and Hessians", summary: "A Jacobian describes the first-order response of a vector-valued function. A Hessian describes second-order curvature of a scalar-valued function. Their dimensions and derivative order come from different questions.",
    hook: "The Jacobian predicts output movement; the Hessian predicts how the slope changes.", model: "la-jacobian", control: ["Evaluation coordinate x=t", -2, 2, 0.1, 1],
    equation: "f(x+δ)≈f(x)+Jf(x)δ; g(x+δ)≈g(x)+∇gᵀδ+½δᵀHgδ",
    assumptions: "J belongs to f(x,y)=(x²+y,xy) at (t,1). H belongs to the different scalar function g(x,y)=x²+xy+2y². Both are smooth real functions.",
    takeaway: "A vector-valued function has one Hessian per scalar output, not generally one Hessian matrix for the whole vector.", prerequisites: [math("matrix-calculus")], sources: [mml, source("MIT matrix calculus course", "https://github.com/mitmath/matrixcalc")],
    ideas: [["Shape of sensitivity", "For f:Rⁿ→Rᵐ, J has m rows and n columns: Jᵢⱼ=∂fᵢ/∂xⱼ. Multiplying J by a direction produces a directional output derivative."], ["Symmetry needs regularity", "A scalar function with continuous second partial derivatives has a symmetric Hessian. Positive definite curvature at a stationary point certifies a strict local minimum."]],
    process: ["Identify whether the function is scalar- or vector-valued.", "Differentiate by input coordinate with an explicit row/column convention.", "Evaluate at the requested point and test the local prediction with a small perturbation."],
    example: ["Predict a small move", "For f at (1,1), J=[[2,1],[1,1]]. Move by δ=(0.01,0).", ["Jδ=(0.02,0.01).", "The actual change is (0.0201,0.01), leaving a first-coordinate error of 0.0001."], "The Jacobian captures first-order movement; the remaining error here is quadratic in the step."],
    pitfalls: ["A PSD Hessian at a stationary point is not sufficient by itself to prove a local minimum.", "At nondifferentiable points, a classical Jacobian or Hessian may not exist."],
    implementation: ["Use Jacobian-vector or vector-Jacobian products when a full matrix is too large.", "Use Hessian-vector products for curvature methods rather than allocating a parameter-count-squared matrix."],
    outcomes: ["Choose the derivative object and its correct dimensions.", "Validate a first-order prediction against a nonlinear example."],
  }),
  [math("kronecker-products")]: reviewed({
    title: "Kronecker products", summary: "The Kronecker product replaces each entry of A with that entry times a full copy of B. It constructs block structure rather than summing over a contracted index.",
    hook: "Each number in the small matrix becomes a scaled block.", model: "la-kronecker", control: ["Top-right entry of A", -2, 2, 0.1, 1],
    equation: "(A⊗B)ᵢp+k,jq+ℓ=AᵢⱼBₖℓ, for B with shape p×q",
    assumptions: "A=[[1,t],[0,2]] and B=[[1,2],[3,4]]. Both are 2×2, so A⊗B is 4×4. Indices in the formula start at zero.",
    takeaway: "Kronecker products multiply dimensions. Ordinary matrix multiplication contracts a shared dimension instead.", prerequisites: [math("matrix-multiplication-and-tensor-contraction")], sources: [np("kron"), mml],
    ideas: [["Separable structure", "When a linear operator separates across two axes, its combined representation can involve a Kronecker product. Keeping factors can avoid materializing a large dense matrix."], ["Vectorization convention", "With column-stacking vec, vec(AXB)=(Bᵀ⊗A)vec(X). Row-stacking uses a different ordering, so the convention is part of the identity."]],
    process: ["Multiply the input row counts and column counts to obtain the output shape.", "Place blocks in A's row/column order.", "Check one block and one global index before using the structure in a solver."],
    example: ["Four blocks from four scalars", "Set t=−1, so A=[[1,−1],[0,2]].", ["The block rows are [B,−B] and [0,2B].", "The first numeric row is [1,2,−1,−2]; the final row is [0,0,6,8]."], "No summation occurred: each output cell is one product of an A entry and a B entry."],
    pitfalls: ["A⊗B and B⊗A generally have different entry order.", "Implicit reshaping with the wrong memory order breaks vectorization identities."],
    implementation: ["Test structured operator application against an explicit tiny Kronecker product.", "Retain factors and apply reshape/multiply operations when materializing the full product would be expensive."],
    outcomes: ["Construct and index a Kronecker block matrix.", "Recognize the importance of vectorization order."],
  }),
  [math("einstein-summation")]: reviewed({
    title: "Einstein summation", summary: "Index notation makes tensor contractions explicit: name the axes, multiply matching entries, and sum the contracted indices. Array-library einsum notation extends this idea with explicit output axes and permutation rules.",
    hook: "Name the axes that survive; sum the ones that disappear.", model: "la-einsum", control: ["B₀₀", -2, 3, 0.1, 1],
    equation: "Cᵢⱼ=ΣₖAᵢₖBₖⱼ ↔ einsum('ik,kj->ij',A,B)",
    assumptions: "A=[[1,2],[0,1]], B=[[t,0],[1,2]]. The explicit output is ij; k is contracted. This example uses ordinary real scalar products.",
    takeaway: "Labels describe axis relationships, not just shapes. Two expressions can have the same output shape but different mathematical meaning.", prerequisites: [math("matrix-multiplication-and-tensor-contraction")], sources: [np("einsum"), np("einsum_path")],
    ideas: [["Output controls meaning", "An explicit arrow removes ambiguity about output axis order. For example, 'ij->ji' transposes while 'ii->' takes a trace and 'ii->i' extracts a diagonal."], ["Contraction order", "For three or more operands, equivalent contraction orders can require very different temporary memory and operation counts. Short notation does not guarantee a cheap algorithm."]],
    process: ["Assign a label and dimension to each operand axis.", "Write output labels explicitly and identify contracted labels.", "Verify a single output element by hand before optimizing the expression."],
    example: ["Trace one output cell", "Set B₀₀=1 in the displayed matrices.", ["For C₀₀, k=0 contributes 1×1=1 and k=1 contributes 2×1=2.", "Their sum is 3; the complete output is [[3,4],[1,2]]."], "The matrix product and 'ik,kj->ij' contraction agree entry by entry."],
    pitfalls: ["Implicit output ordering can transpose a result relative to your intent.", "Repeated labels inside a single operand select diagonals; they do not simply rename independent axes."],
    implementation: ["Use explicit output labels and document batch, sequence, and feature axes.", "Inspect a contraction path and peak temporary size for large multi-operand expressions."],
    outcomes: ["Translate a contraction between index and array notation.", "Check semantics and cost independently of compact syntax."],
  }),
  [math("numerical-conditioning")]: reviewed({
    title: "Numerical conditioning", summary: "Conditioning measures a problem's sensitivity to input perturbations. For an invertible matrix, κ₂(A)=σmax/σmin bounds worst-case relative amplification in a linear solve when only the right-hand side changes.",
    hook: "A weakly observed direction turns a tiny input error into a large solution change.", model: "la-conditioning", control: ["Exponent s in ε=10⁻ˢ", 0, 4, 0.1, 2],
    equation: "κ₂(A)=‖A‖₂‖A⁻¹‖₂=σmax/σmin; relative x error ≤ κ₂(A)·relative b error",
    assumptions: "A=diag(1,ε), b=(1,0), δb=(0,0.001), with A held fixed and Euclidean relative errors. Here 0<ε≤1, so κ₂=1/ε. The example attains the bound.",
    takeaway: "Conditioning belongs to the problem; numerical stability belongs to the algorithm. A stable algorithm cannot remove sensitivity already present in the data.", prerequisites: [math("singular-value-decomposition"), math("norms")], sources: [np("linalg.cond"), mml],
    ideas: [["Worst case, not every direction", "A large condition number means some perturbations can be strongly amplified. A particular right-hand side and perturbation can be much less sensitive."], ["Forward versus backward error", "Forward error measures distance from the desired solution. Backward error asks how much the input must change to make the computed answer exact. Small backward error can coexist with large forward error for an ill-conditioned problem."]],
    process: ["Choose a norm and state which inputs may be perturbed.", "Estimate singular-value ratios or use a suitable condition estimator.", "Compare solution sensitivity with realistic measurement and arithmetic errors."],
    example: ["A thousandfold amplification", "Set ε=0.001, so κ₂=1000 and the original solution is (1,0).", ["Changing b to (1,0.001) changes the solution to (1,1).", "Relative input error is 0.001; relative solution error is 1."], "The amplification is 1000, exactly the condition number for this carefully chosen direction."],
    pitfalls: ["A small residual alone does not establish a small solution error.", "Adding regularization may improve conditioning but changes the estimation problem and introduces bias."],
    implementation: ["Solve linear systems with factorization routines rather than explicitly forming an inverse.", "Monitor scaling and conditioning alongside residuals; higher precision cannot fix uncertain measurements."],
    outcomes: ["Compute and interpret a condition number.", "Distinguish input sensitivity, residuals, and algorithmic stability."],
  }),
};

for (const lesson of Object.values(linearAlgebraLessons)) lesson.labs[0].title = labTitles[lesson.labs[0].model];
