import { math, reviewed, source } from "./lesson-helpers.mjs";
const topic = name => `probabilistic-ai/topics/${name}`;
const filterSource = source("Doucet & Johansen: particle filtering and smoothing tutorial", "https://www.stats.ox.ac.uk/~doucet/doucet_johansen_tutorialPF2011.pdf");
const samplerSource = source("Del Moral, Doucet & Jasra: Sequential Monte Carlo samplers", "https://www.stats.ox.ac.uk/~doucet/delmoral_doucet_jasra_sequentialmontecarlosamplersJRSSB.pdf");
const essSource = source("Elvira, Martino & Robert: Rethinking the Effective Sample Size", "https://arxiv.org/abs/1809.04129");
export const particleLessons = {
  [topic("particle-filter")]: reviewed({
    title: "Particle filter", labTitle: "Twenty moving hypotheses versus an exact filter",
    summary: "A particle filter approximates the distribution of a hidden current state given observations so far. The bootstrap version proposes states from the transition model, weights them by the new observation likelihood and may resample. It is an online filtering application of Sequential Monte Carlo, not an exact inference guarantee.",
    hook: "Move the hypotheses, score the sensor reading, then decide whether to copy survivors.", model: "particle-filtering", control: ["Observation prefix length", 1, 6, 1, 3],
    equation: "Xₜⁱ∼f(·|Xₜ₋₁ⁱ); w̃ₜⁱ=wₜ₋₁ⁱg(Oₜ|Xₜⁱ); ŵₜⁱ=w̃ₜⁱ/Σj w̃ₜʲ; ESSw=1/Σi(ŵₜⁱ)²",
    assumptions: "Five sites form a ring (4 neighbors 0). Transition probabilities are 0.6 to stay and 0.2 to either neighbor. A sensor reports the true site with probability 0.6, either adjacent site with 0.15 each and either remaining site with 0.05 each. The prior is uniform. Twenty prior-CDF-stratified particles start with four per site at t=1: assimilate the first reading directly, then propagate before each later reading. Observations are (0,1,1,3,4,4). Fixed pseudorandom seed 20260930 makes the run repeatable. Systematic resampling runs only when weight ESS is strictly below 10, resetting weights to 1/20. Plots show estimates before that resampling step, alongside an exact five-state filter.",
    takeaway: "Separate sampling error, weight concentration and loss of ancestry. A particle count or ESS alone does not bound the error of a filtering query.",
    prerequisites: [topic("hidden-markov-models"), topic("sequential-monte-carlo"), math("importance-sampling")], sources: [filterSource, essSource],
    ideas: [["The transition is a proposal", "In this bootstrap filter the proposal equals the transition, so its transition-to-proposal ratio cancels and only the observation likelihood remains in the incremental weight. Other proposals require that correction. With adaptive resampling, retain the previous weight on steps where resampling was skipped."], ["An exact small reference makes error visible", "For this ring, the exact filter needs just five numbers. It first sums incoming transition mass at each site, multiplies by the latest sensor likelihood and normalizes. The paired bars compare that calculation with the finite weighted population on the same observation prefix."], ["Resampling copies, it does not move", "Systematic resampling chooses parent indices from the cumulative weights using equally spaced thresholds and one random offset. Copies inherit their parent's state and initial ancestor identity. Only the subsequent transition can move a copy to another site in this lab."], ["Current support and historical ancestry differ", "A population can recover a site through its transition model after it was temporarily empty, while an extinct initial-particle identity never returns. This matters when reusing filtering particle paths for long-horizon smoothing. The ancestry table tracks identities, not the number of occupied sites."]],
    process: ["Initialize states from the prior or a supported proposal, recording weights and any ancestry needed for the query.", "Propagate through the transition, multiply old weights by the new likelihood, normalize and compute the desired weighted estimate.", "Check the declared resampling criterion. If it fires, draw ancestors and reset child weights; otherwise carry the nonuniform weights into the next update."],
    example: ["The first reading is exact by construction, later ones are not", "Read O₁=0 with four equal-weight particles at each of five sites.", ["The exact posterior is (0.6,0.15,0.05,0.05,0.15), and the initial particle allocation produces the same weighted site masses.", "Each site's mass is split across four particles. Thus ESSw=4/(0.6²+2×0.15²+2×0.05²)=400/41≈9.756098, below 10.", "Systematic resampling gives site counts (12,3,1,1,3) and leaves 12 initial identities. At the default third reading, this seeded run instead has total variation error about 0.073836 and ESSw≈13.498403, so resampling is skipped."], "The exact first-step match comes from the balanced toy initialization, not a general guarantee for particle filters. The default run already shows nonzero error despite skipping resampling."],
    pitfalls: ["Zero total likelihood weight is an algorithm failure to handle, not permission to silently replace the posterior with a uniform distribution.", "A sharp likelihood can reject most proposed states. More particles, better proposals or analytic marginalization may help, but no universal particle count guarantees accuracy.", "Resampling does not itself create new states or prove that all important modes were found. In a continuous state space, useful mutation must respect the intended target or proposal correction."],
    implementation: ["Use log weights and log-sum-exp for long or sharp likelihood products. Keep the pre-resampling query estimate separate from the population copied for the next step.", "For a real assessment, compare independent seeds and increasing particle counts against tractable references. This single reproducible run illustrates mechanics; it is not an uncertainty interval or a performance benchmark."],
    outcomes: ["Trace a bootstrap particle filter with adaptive systematic resampling.", "Distinguish weighted filtering error, ESS and surviving particle ancestry."],
  }),
  [topic("sequential-monte-carlo")]: reviewed({
    title: "Sequential Monte Carlo", labTitle: "Equal weights do not mean four different hypotheses",
    summary: "Sequential Monte Carlo maintains weighted particles across a sequence of target distributions using importance weighting, resampling and suitable propagation or mutation. The sequence may follow real observations, as in particle filtering, or artificial intermediate targets for a static problem. This lab isolates one tempered weighting and resampling stage.",
    hook: "Four equal tickets can all point to only two places.", model: "particle-tempering", control: ["Tempering exponent β", 0, 1, .05, 1],
    equation: "πβ(θ)∝π₀(θ)L(θ)^β; wnewⁱ∝woldⁱL(θⁱ)^(βnew−βold); ESSw=1/Σi(wⁱ)²",
    assumptions: "Four static hypotheses A,B,C,D have uniform prior and relative likelihood scores (1,2,4,16). Start with one equal-weight particle at each hypothesis. Each slider setting independently restarts a bridge from β=0 to the chosen β; it does not evolve the previous slider state. The exhaustive four-point starting population makes the pre-resampling weights exact for this toy target. Systematic resampling uses fixed offset 1/8 and thresholds (1/8,3/8,5/8,7/8), with no mutation. A randomized implementation draws its offset uniformly in [0,1/4).",
    takeaway: "Weight ESS measures concentration among particle weights, not the count of distinct states or correctness of their empirical distribution. Resampling can raise ESS while removing hypotheses.",
    prerequisites: [math("importance-sampling"), math("monte-carlo-estimation")], sources: [samplerSource, filterSource, essSource],
    ideas: [["Sequential can mean an artificial bridge", "Here β increases from an easy uniform target toward a likelihood-weighted target on the same four hypotheses. In a full sampler, smaller temperature increments and target-preserving mutation can help the population adapt. The present control shows one isolated stage so every weight and copy can be inspected."], ["Weight correction depends on the construction", "The displayed likelihood-power ratio is valid for reweighting unchanged particles between these tempered targets. General SMC proposals, path extensions or backward kernels lead to different importance ratios; the simple expression is not a universal update for every mutation."], ["Copies get equal weights, not independent identities", "At β=1, the CDF thresholds select B,D,D,D. Each child receives weight 1/4, but three children share the same hypothesis. The grouped bars contrast mass represented before and after that specific resampling realization."], ["Mutation has a different job", "Resampling can only select states already present. A properly constructed mutation or proposal can explore elsewhere. A random jitter added without a valid invariant kernel or importance correction is not automatically a legitimate SMC move."]],
    process: ["Choose intermediate targets and an initial proposal with adequate support; derive the corresponding incremental importance ratio.", "Normalize weights and inspect concentration before optionally resampling. Keep the distinction between particle weights and empirical mass at each state.", "Apply valid propagation or mutation, retain required normalization bookkeeping, and diagnose repeated runs using the actual quantities of interest."],
    example: ["ESS rises while diversity falls", "Set β=1 for scores (1,2,4,16).", ["Normalized weights are (1,2,4,16)/23, so ESSw=23²/(1²+2²+4²+16²)=529/277≈1.909747.", "Cumulative weights are (1,3,7,23)/23. Threshold 1/8 selects B; the other three thresholds select D. The child population is B,D,D,D.", "All four child weights are 1/4 and ESSw becomes 4. Yet only two hypotheses survive, with empirical masses (0,1/4,0,3/4). Their total variation distance from the exact target is 5/23≈0.217391."], "The diagnostic improved by construction, not because the resampled empirical distribution became exact. At β=0 all four hypotheses survive and both bar series agree."],
    pitfalls: ["An ESS of N after resampling does not mean N independent draws from the target.", "Randomized systematic resampling preserves weighted empirical expectations conditionally on the input population; one fixed-offset realization need not preserve every estimate.", "Too large a target change can collapse weights before resampling can help. Tempering and mutation still need adequate support and a correctly derived target."],
    implementation: ["Record the temperature schedule, incremental log weights, resampling rule and mutation kernel. The normalizing-constant estimator needs additional bookkeeping beyond normalized weights.", "Monitor distinct ancestors, support and query stability alongside ESS. Do not use this four-hypothesis example's exact pre-resampling weights as a claim about general finite-particle SMC."],
    outcomes: ["Calculate a tempered importance update and systematic resampling choices.", "Explain why uniform particle weights can coexist with lost support and approximation error."],
  }),
  "probabilistic-ai": reviewed({
    title: "Probabilistic AI", labTitle: "The belief stays fixed; the best action changes",
    summary: "Probabilistic AI separates a model of uncertain quantities, a query about those quantities, an inference method and a decision rule. This section moves from graphical-model assumptions to exact and approximate inference, latent-variable learning and temporal state estimation. A numerical answer is meaningful only under its model and evidence assumptions.",
    hook: "Model → query → inference → decision: keep the four contracts separate.", model: "probabilistic-decision", control: ["Loss for missing a fault", 0, 10, .25, 3, " units"],
    equation: "p=P(H=1|+)=0.1×0.8/(0.1×0.8+0.9×0.2)=4/13; R(intervene)=1−p; R(wait)=Cp",
    assumptions: "Toy binary fault H has prior probability 0.1. P(+|fault)=0.8 and P(+|no fault)=0.2; one positive signal is observed. Intervening costs 1 only when there is no fault; waiting costs C only when there is a fault. Correct actions have zero loss. These abstract losses fully specify this simplified decision problem; there is no separate intervention cost or resource constraint. The slider changes C, never the probabilistic model or observation.",
    takeaway: "Probability describes belief under a model. A choice additionally depends on losses or utility. Changing those preferences should not silently change the posterior.",
    prerequisites: [math("conditional-probability"), math("bayes-theorem"), math("expectation")],
    sources: [source("Stanford CS228: graphical-model representation", "https://ermongroup.github.io/cs228-notes/representation/directed/"), source("Berkeley CS188: decisions and expected utility", "https://inst.eecs.berkeley.edu/~cs188/textbook/vpis/decision-networks.html"), filterSource],
    ideas: [["Model: say what is random and what is conditioned on", "A Bayesian network factorizes a joint distribution; an MRF uses nonnegative compatibility factors and a normalizer; a CRF conditions structured labels on inputs. Graph arrows alone do not identify causal effects. Start with conditional independence and graph semantics before selecting an algorithm."], ["Query: specify the answer you actually need", "A marginal probability, most likely joint assignment, observation likelihood and future predictive distribution differ. In time-series models, filtering uses evidence so far, smoothing uses later evidence too, and decoding seeks a best path. The required output determines which reduction or recursion is appropriate."], ["Inference: distinguish the model from its approximation", "Variable elimination and calibrated junction trees can be exact but costly. Variational methods, loopy messages and Monte Carlo introduce different approximation mechanisms. An optimizer converging or particle weights becoming uniform does not establish accurate posterior answers. EM estimates parameters; it does not by itself return a Bayesian posterior over them."], ["Decision: make the loss explicit", "The same posterior can favor different actions under different consequences. Here the fault is less likely than no fault, yet intervening is optimal once missing a fault costs more than 2.25 units. A universal threshold of one half is justified only for an appropriate symmetric loss, not for every application."]],
    process: ["Write the variables, support, factors and evidence, then state the query in probability or optimization notation.", "Choose an inference method that exploits the graph and distributional structure; compare approximations against tractable small references where possible.", "If an action is needed, combine the inferred distribution with an explicit loss model, then evaluate predictive quality and decision consequences separately."],
    example: ["A positive alert is not a decision", "The sensor is positive and the missed-fault loss is C=3.", ["Joint masses for a positive alert are 0.1×0.8=0.08 with a fault and 0.9×0.2=0.18 without one. Normalize by 0.26 to obtain posterior fault probability 4/13≈0.307692.", "Expected intervention loss is 9/13≈0.692308. Waiting has expected loss 3×4/13=12/13≈0.923077, so intervention has lower expected loss.", "Reduce C to 2: waiting loss becomes 8/13, below intervention's 9/13. At C=2.25 both actions tie. The posterior stays 4/13 in every case."], "The preference changes without new evidence. Keep probability estimation and decision costs as separate, inspectable components."],
    pitfalls: ["A precisely computed posterior can still come from a misspecified or poorly calibrated model.", "Do not conflate conditional dependence with causation or a graph representation with a specific inference algorithm.", "Do not relabel an approximate result as exact because a convergence or resampling diagnostic looks favorable."],
    implementation: ["Keep model parameters, observed evidence, query definitions, approximation settings and losses separately versioned so changes have interpretable effects.", "Use the learning paths above as an orientation, not as proof that every earlier topic is a prerequisite. Each lesson lists its own prerequisites and worked assumptions."],
    outcomes: ["Separate representation, inference, learning and decision-making tasks.", "Choose a relevant learning path and interpret a posterior without confusing it with an action."],
  }),
};
for (const lesson of Object.values(particleLessons)) lesson.updatedAt = "2026-09-30";
