import { source, reviewed } from "./lesson-helpers.mjs";
const topic = name => `classical-artificial-intelligence/topics/${name}`;
const semantics = source("Poole and Mackworth: predicate interpretations and variables", "https://artint.info/3e/html/ArtInt3e.Ch15.S3.html");
export const predicateLessons = {
  [topic("first-order-predicate-logic")]: reviewed({
    title: "First-order predicate logic", labTitle: "Check the rule against objects, not unnamed truth bits",
    summary: "First-order predicate logic describes objects, their properties and relations, and quantified statements about a domain. Constants name objects, variables range over them, predicates evaluate tuples, and function symbols denote domain-valued functions. Truth requires an interpretation; open formulas also require values for their free variables. Evaluating a sentence in one specified interpretation is different from showing it follows in every model of a knowledge base.",
    hook: "A predicate gains meaning only after its domain and extension are fixed.", model: "logic-predicate-model", control: ["Healthy subset mask: a=1, b=2, c=4", 0, 7, 1, 1],
    equation: "∀x(Active(x)⇒Healthy(x)); ∃x(Active(x)∧Healthy(x))",
    assumptions: "Domain D={a,b,c} contains three distinct objects and no others. Active={a,b} is fixed. The mask fully specifies Healthy: bit 1 selects a, bit 2 selects b, bit 4 selects c. Use classical two-valued truth, with no unknown entries. The grid checks both closed sentences in this finite interpretation, rather than running an inference procedure over unspecified models.",
    takeaway: "With only a healthy, the existential sentence is true but the universal rule is false because b is a counterexample. Inactive c does not falsify the implication merely by being unhealthy.",
    prerequisites: [topic("propositional-logic")], sources: [semantics, source("Berkeley CS188: terms, predicates and quantifiers", "https://inst.eecs.berkeley.edu/~cs188/textbook/logic/first-order-logic.html")],
    ideas: [["Distinguish a symbol from its interpretation", "In this model the constant a denotes one service and Healthy(a) is true precisely when a is in the supplied healthy subset. The spelling of a constant does not establish its properties. Distinct constants are assigned distinct objects here by assumption, not by a universal rule of first-order semantics."], ["A free variable requires an assignment", "Healthy(x) can change truth when x denotes a rather than b. ∀x Healthy(x) and ∃x Healthy(x) bind x and ask different domain-wide questions. Writing the bound scope with parentheses prevents accidental changes of meaning."], ["Use the appropriate guard", "Every active service is healthy uses Active(x)⇒Healthy(x). An inactive object makes that implication true. Some active service is healthy uses Active(x)∧Healthy(x), because an inactive object must not count as its witness."], ["One complete interpretation is not an open knowledge base", "The lab supplies both true and false predicate instances for all three objects. In a knowledge base that asserts only Healthy(a), absence of Healthy(b) need not entail ¬Healthy(b). Treating omitted facts as false requires an explicit additional convention."],
    ],
    process: ["Declare the domain, symbol meanings and any identity assumptions.", "Evaluate terms and ground predicates, then connectives under a variable assignment.", "For a quantifier, evaluate its scope over the declared domain; distinguish model evaluation from entailment."],
    example: ["An active-service requirement", "Active={a,b}, Healthy={a} in D={a,b,c}.", ["At a, Active and Healthy are both true, so a witnesses the existential statement.", "At b, Active is true and Healthy false, falsifying the universal implication.", "At c, Active is false, so the implication holds even though Healthy is false."], "The universal requirement fails with counterexample b; the existential requirement succeeds with witness a."],
    pitfalls: ["A finite model's successful check is not validity across every possible interpretation.", "Defaulting every unrecorded predicate instance to false silently adds a closed-world assumption."],
    implementation: ["Document domain restrictions, predicate arity and identity assumptions beside the encoding.", "Keep true, false and unknown information distinct when the data source is incomplete, and report what a finite-domain check actually establishes."],
    outcomes: ["Evaluate predicates and guarded quantifiers in a supplied interpretation.", "Distinguish a counterexample, a witness and logical entailment."],
  }),
  [topic("quantifiers")]: reviewed({
    title: "Quantifiers", labTitle: "Every job can have a worker without sharing one worker",
    summary: "Universal quantification requires a formula for every domain element; existential quantification requires at least one witness. Nested quantifier order controls which witnesses may depend on earlier choices. ∀x∃y R(x,y) permits a different y for each x, whereas ∃y∀x R(x,y) requires one y that works for all x. Reversing these mixed quantifiers generally changes the claim.",
    hook: "A one in every row is weaker than one column full of ones.", model: "logic-quantifier-order", control: ["Compatibility pattern", 0, 3, 1, 0],
    equation: "∃w∈Workers ∀j∈Jobs R(j,w) ⇒ ∀j∈Jobs ∃w∈Workers R(j,w); converse is not valid",
    assumptions: "Jobs={j1,j2} and Workers={w1,w2,w3} are fixed nonempty finite sets. R(j,w) means that worker can handle that job. Four completely specified compatibility tables are supplied; the control changes the table, not the quantifier definition. Bounded quantifiers are shorthand for the stated typed restrictions. No worker capacity, distinctness or simultaneous assignment condition is encoded.",
    takeaway: "Pattern 0 supports j1 only with w1 and j2 only with w2. Every job has a witness, but there is no common witness. Pattern 1 adds a shared w1 column, making both sentences true.",
    prerequisites: [topic("first-order-predicate-logic")], sources: [source("forall x: Calgary — multiple generality and quantifier order", "https://forallx.openlogicproject.org/html/Ch25.html"), source("Stanford Introduction to Logic: quantifier relationships and negation", "https://logical.stanford.edu/intrologic/sections/section_08.html?section=2")],
    ideas: [["The existential witness can depend on the earlier universal choice", "In pattern 0 choose w1 for j1 and w2 for j2. That choice implements a witness function of the job. Choosing one worker before considering either job cannot satisfy the stronger sentence in the same relation."], ["State the intended scope and domain", "The control checks a finite typed relation: jobs and workers are separate sets. In a single-sorted first-order encoding, use Job and Worker predicates to guard the quantifiers instead of silently ranging over every object."], ["Negation changes the quantifier and its scope", "Negating every job has some compatible worker yields some job has no compatible worker: ∃j∀w¬R(j,w) under the stated bounds. Pattern 2 supplies that counterexample with j2's all-zero row. It is not the weaker statement that some incompatible pair exists."], ["Compatibility is not a capacity-aware assignment", "A shared column says one worker is capable of each job separately. It does not say the worker can do both jobs at once. Distinct-worker requirements, durations and capacities would need additional formulas or a scheduling model."],
    ],
    process: ["Write the variable domains and the complete scope of every quantifier.", "For ∀j∃w, check each job's row for a witness; for ∃w∀j, check for a full worker column.", "When a sentence fails, produce the appropriately quantified counterexample rather than one arbitrary false entry."],
    example: ["Different witnesses, no universal worker", "Pattern 0 has rows j1=[1,0,0] and j2=[0,1,0].", ["Each row contains a one, so ∀j∃w R(j,w) holds.", "Every column has a zero, so ∃w∀j R(j,w) fails.", "Add R(j2,w1)=true: w1 now witnesses the stronger claim in pattern 1."], "The stronger claim implies the weaker one, but the original table is a countermodel to the converse."],
    pitfalls: ["Swapping ∀ and ∃ can replace many dependent witnesses with one impossible shared witness.", "Finding one false pair does not refute ∀j∃w; the job's entire row must lack a witness."],
    implementation: ["Preserve quantifier order and rename bound variables carefully when transforming formulas.", "For a fixed finite relation, compute row supports and common columns explicitly; do not generalize that check into a general first-order decision procedure."],
    outcomes: ["Compare dependent witnesses with one shared witness.", "Negate a quantified statement and identify the correct counterexample."],
  }),
};
for (const lesson of Object.values(predicateLessons)) lesson.updatedAt = "2026-10-01";
