import { source, reviewed } from "./lesson-helpers.mjs";
const topic = name => `classical-artificial-intelligence/topics/${name}`;
const survey = source("Browne et al.: A Survey of Monte Carlo Tree Search Methods, §3", "https://cs.gettysburg.edu/~tneller/cs371/mcts-survey.pdf");
const uct = source("Kocsis and Szepesvári: Bandit based Monte-Carlo Planning, §2", "https://sites.ualberta.ca/~szepesva/papers/ecml06.pdf");
export const sampledTreeLessons = {
  [topic("monte-carlo-tree-search")]: reviewed({
    title: "Monte Carlo tree search", labTitle: "A rollout can see a leaf before the tree contains it",
    summary: "Monte Carlo tree search allocates a finite lookahead budget using statistics collected from completed simulations. This lab separates selection through an existing tree, expansion of one new child, a rollout through the domain and backup to the selected tree nodes. Inspect the exact trace and its changing estimates rather than treating a larger visit count as a proof. The example is single-agent optimization; it does not model an adversary or a learned neural evaluator.",
    hook: "Search evidence grows one node at a time; a simulated state is not automatically a tree node.", model: "tree-mcts", control: ["Completed simulations", 0, 32, 1, 8],
    equation: "N←N+1; W←W+r; Q=W/N; select Q+c√(ln Nparent/Nchild)",
    assumptions: "R chooses terminal A (reward 0.6) or decision B, which chooses L (0) or H (1). One agent controls both decisions; all rewards use the same [0,1] scale. Expand untried children left to right. Fully expanded nodes use UCT with c=√2 and first-child ties. Rollouts choose uniformly using a seed-7 32-bit generator. Backup touches selected/expanded tree nodes only. Recommend the most visited root child, A first on ties. The slider recomputes from the same seed, with no animation or background search.",
    takeaway: "Simulation 2 expands B and rolls out to L with reward 0, but L remains outside the search tree. Seeing a terminal in a rollout and maintaining its own visit statistics are different operations.",
    prerequisites: [topic("state-space-representation"), "mathematical-foundations/topics/expectation"], sources: [survey, uct],
    ideas: [["Domain graph versus maintained evidence", "All five domain nodes are drawn for orientation. Initially the maintained tree contains only R. The outside annotation means a state has not been expanded, not that it is unreachable. The numeric table includes only visited nodes, so an unobserved mean is never displayed as zero."], ["Replay the first two simulations", "The first expansion chooses A and returns 0.6 immediately. The second expansion chooses B, then the seed-7 rollout chooses L and returns 0. B receives one backed-up sample, but L receives no stored statistics until a later expansion. At budget two the robust-child tie chooses A."], ["The continuation policy changes the observed average", "B is a decision owned by the same agent, not a chance node. Its early uniform rollout sees one of {0,1}; later tree selection favors H as evidence grows. Averaging these returns does not estimate a fixed fair coin's mean of 0.5. Neither the current sampled mean nor its exploration score is the exact max value 1."], ["A budget boundary is not a correctness certificate", "A terminal reward can be exact while the root recommendation remains sample-dependent. The reference best achievable reward 1 is supplied by inspecting this tiny domain, not certified by a large visit count. At zero budget the page deliberately returns no recommendation."], ["Player semantics would require a different contract", "Because every decision belongs to one agent, the same reward is backed up without sign changes. A two-player zero-sum implementation must compare values for the correct acting player; maximizing this root reward at an opponent node would make that opponent cooperative."],
    ],
    process: ["Follow the tree policy until a terminal or a node with an untried action is reached.", "Expand one untried child; simulate from it to a genuine terminal under the declared rollout policy.", "Update visit counts and reward totals along the tree path, then choose a root recommendation with a separately declared rule."],
    example: ["A leaf observed but not expanded", "Set the budget to two simulations.", ["Simulation 1 expands A: reward 0.6 backs up to A and R.", "Simulation 2 expands B: the uniform rollout B→L gives reward 0, backing up to B and R only.", "Root N=2,W=0.6; A and B each have one visit. The declared recommendation is A; L still has no tree estimate."], "The diagram distinguishes the simulation's terminal from the nodes that own recorded evidence."],
    pitfalls: ["Treating a sampled rollout average as an exact minimax value hides policy and budget dependence.", "Updating an outside state's statistics without actually adding it to the maintained structure silently changes the algorithm."],
    implementation: ["Store visit count, reward total, expansion state and payoff perspective separately; return no mean when the count is zero.", "Record the seed, action ordering, selection coefficient, rollout policy and final recommendation rule so a trace can be reproduced."],
    outcomes: ["Trace selection, expansion, rollout and backup without conflating them.", "Distinguish recorded estimates, simulation allocation and a final action recommendation."],
  }),
  [topic("uct")]: reviewed({
    title: "UCT", labTitle: "A lower mean can earn the next simulation",
    summary: "UCT applies a bandit-style selection score within a Monte Carlo search tree. An empirical reward term favors promising actions; a count-dependent bonus allocates more evidence to less visited alternatives. Its coefficient must be interpreted alongside the reward scale and formula convention. This lab isolates one fixed parent snapshot, making the allocation threshold visible without pretending that a single score comparison establishes an optimal policy or a confidence level.",
    hook: "Choose where to learn next, not merely which current average is largest.", model: "tree-uct", control: ["Exploration coefficient c", 0, 2, 0.05, 1],
    equation: "scorei=Wi/Ni+c√(ln Nparent/Ni); choose argmaxi scorei",
    assumptions: "Fixed parent visit count 100. A has 80 visits, reward total 56 and mean 0.70. B has 20 visits, total 12 and mean 0.60. Rewards are on [0,1], but selection scores need not be. Natural logarithm; this convention absorbs other authors' constants into c. The snapshot never changes with the slider, and both counts are positive. Exact ties choose A. For a hypothetical budget stop, the declared most-visited rule recommends A regardless of c. No additional simulation is performed.",
    takeaway: "B has one quarter of A's visits and twice its exploration bonus. Above c≈0.4168 it receives the next sample despite its lower observed mean; the most-visited final recommendation remains A.",
    prerequisites: [topic("monte-carlo-tree-search"), "mathematical-foundations/topics/expectation"], sources: [uct, survey],
    ideas: [["Compute the two scores in the same units", "The means are 56/80=0.70 and 12/20=0.60. Their bonus factors are √(ln100/80)≈0.2399 and √(ln100/20)≈0.4799. At c=1, B's score≈1.0799 exceeds A's≈0.9399. This is a sampling preference, not an estimated probability above one."], ["A threshold makes the allocation policy inspectable", "Equating 0.70+c×0.2399 with 0.60+c×0.4799 gives c≈0.4168. Below it, A gets the next sample; above it, B does. At c=0 the bonus vanishes and A wins by observed mean. The 0.05-step slider brackets, rather than exactly hits, the crossover."], ["Parent visits are local", "Use the count of the current parent, not an unrelated global search count. The snapshot's child counts sum to 100 because every parent visit here selected one of these two children. In an expanding tree, count relationships depend on initialization and which nodes receive backup."], ["An unvisited action needs an explicit rule", "The expression is undefined at Ni=0. The companion simulation expands each untried action before comparing finite UCT scores. Other implementations can give unvisited actions an effectively infinite priority; neither approach should perform a literal division by zero."], ["Reward scale and final choice are separate decisions", "Multiplying rewards without adjusting c changes the mean-to-bonus balance. A recommendation based on most visits differs from next-simulation allocation. Both are explicit policies here; the displayed coefficient is not a user-selected 95% interval or a universal default for every task."],
    ],
    process: ["Specify payoff perspective, reward scale, parent visits and each candidate's count and total.", "Handle unvisited actions separately, then calculate means and exploration bonuses for visited candidates.", "Allocate the next simulation by score; after the budget ends, apply the declared final recommendation rule."],
    example: ["Allocation changes; recorded evidence does not", "Use c=1 with the fixed snapshot.", ["A score=0.70+√(ln100/80)≈0.9399.", "B score=0.60+√(ln100/20)≈1.0799, so allocate the next sample to B.", "If stopping now under the most-visited rule, recommend A because 80>20; the displayed counts have not changed."], "Learning where evidence is thin is a different operation from committing the final action."],
    pitfalls: ["Reading a score above one as a probability misinterprets an exploration-adjusted index.", "Claiming finite-budget optimality from an asymptotic result ignores the specific assumptions and constants needed by that result."],
    implementation: ["Document natural logarithm, coefficient convention and payoff perspective; do not mix reward totals with empirical means.", "Expose mean, bonus, count and final recommendation separately; record actual returns when a subsequent simulation changes the snapshot."],
    outcomes: ["Compute the next sampling action from explicit local statistics.", "Explain why allocation scores and stopped-search recommendations can disagree."],
  }),
};
for (const lesson of Object.values(sampledTreeLessons)) lesson.updatedAt = "2026-10-01";
