import { reviewed, source } from "./lesson-helpers.mjs";
const topic = name => `probabilistic-ai/topics/${name}`;
const jt = source("Stanford CS228: junction trees and running intersection", "https://ermongroup.github.io/cs228-notes/inference/jt/");
const crf = source("Sutton & McCallum: conditional random fields", "https://people.cs.umass.edu/~mccallum/papers/crf-tutorial.pdf");
const dbn = source("Murphy: DBN representation, inference and learning", "https://www.cs.ubc.ca/~murphyk/Thesis/thesis_double.pdf");
export const structuredLessons = {
  [topic("junction-tree-algorithm")]: reviewed({
    title: "Junction-tree algorithm", labTitle: "Two clusters agree on what they share",
    summary: "A junction tree reorganizes a graphical model into overlapping variable clusters arranged as a tree. Exact sum-product messages calibrate the clusters so their marginals agree on shared variables. This permits exact inference in cyclic models when the cluster tables remain computationally manageable.",
    hook: "Make the computation a tree without pretending the original model was one.", model: "structured-junction", control: ["Unary weight a for A=1", .25, 4, .25, 3],
    equation: "mL→R(A,C)=ΣB φL(A,B,C); mR→L(A,C)=ΣD φR(A,C,D); bL∝φL mR→L",
    assumptions: "Binary cycle A—B—C—D—A. Each original edge has weight 3 for equal states and 1 for unequal states. A has unary weight (1,a); all other unaries are 1. Assign φL=uA·ψAB·ψBC to cluster ABC and φR=ψCD·ψDA to cluster ACD, once each. Their separator is {A,C}. The fill edge AC adds no new factor. Both messages and calibrated cluster tables are computed by finite sums.",
    takeaway: "Exactness needs factor coverage and running intersection. Efficiency depends on cluster sizes, not just whether the original graph has a cycle.",
    prerequisites: [topic("variable-elimination"), topic("belief-propagation")], sources: [jt, dbn],
    ideas: [["Overlap is necessary, duplication is not", "Clusters ABC and ACD both contain A and C. Each original factor is nevertheless assigned exactly once. Multiplying an extra AC compatibility factor would change this example's distribution, rather than merely triangulate its computation."], ["Running intersection keeps a variable connected", "Every cluster containing a given variable must form a connected subtree. Here A and C occur in both adjacent clusters, while B and D each occur in just one. This condition lets a cluster safely sum out variables absent from its neighbor."], ["Messages live on separators", "ABC sends a four-entry function of A and C after summing over B. The reverse message sums over D. Each cluster multiplies its own assigned factors by the incoming message, then normalizes. Summing the resulting clique beliefs onto AC gives the same table."], ["A tree of large tables can still be expensive", "For uniform cardinality K and maximum clique size w+1, a dense clique has K^(w+1) entries. Total work also depends on the number of cliques, degrees and the query. A poor elimination order can produce width larger than the graph's minimum treewidth. Calibration does not make arbitrary joint queries free."]],
    process: ["Cover every factor with a cluster, using moralization for a Bayesian network and an elimination-based triangulation when needed.", "Connect clusters into a tree satisfying running intersection; assign each factor and each evidence factor once.", "Pass separator messages inward and outward. Answer a clique-contained query by marginalizing a calibrated clique; recompute affected messages when evidence changes."],
    example: ["Calibrating a four-cycle", "Use a=3 and rows A=0,1 with columns C=0,1.", ["Summing the left cluster over B gives [[10,6],[18,30]]. Summing the right cluster over D gives [[10,6],[6,10]].", "The unnormalized separator table is their entrywise product: [[100,36],[108,300]], whose entries sum to 544.", "Divide by 544. Either calibrated clique gives P(A=1)=408/544=0.75 and P(C=1)=336/544≈0.617647."], "Two eight-entry clique tables agree on a four-entry separator. No independence between A and C was introduced."],
    pitfalls: ["A tree of arbitrary clusters is not enough: factor coverage and running intersection must both hold.", "Fill edges encode the computation's scope; inventing extra nonconstant factors on them changes the model.", "Calibration guarantees exact probabilities for the specified tractable model, not that the model accurately represents reality. New evidence generally requires new messages."],
    implementation: ["Track named factor scopes and factor ownership. Preserve message scales if you need the partition function, and handle zero-probability evidence explicitly.", "Inspect clique cardinalities before allocating dense tables. To answer a query spanning several cliques, combine the required subtree information rather than multiplying overlapping marginals as if independent."],
    outcomes: ["Compute separator messages and verify agreement between calibrated clusters.", "Separate exactness conditions from the exponential cost of large clusters."],
  }),
  [topic("conditional-random-fields")]: reviewed({
    title: "Conditional random fields", labTitle: "Local label preferences meet sequence compatibility",
    summary: "A conditional random field defines a distribution over structured labels y for a fixed observed input x. It combines input-dependent potentials and output compatibility, then normalizes over complete label structures. A linear chain supports efficient exact inference; a general output graph need not.",
    hook: "Choose a whole labeling, not three isolated winners.", model: "structured-crf", control: ["Weight multiplier r for matching neighbors", 1, 6, .25, 3],
    equation: "P(y|x)=u₁(y₁)u₂(y₂)u₃(y₃)r^[1{y₁=y₂}+1{y₂=y₃}]/Z(x)",
    assumptions: "Fixed input x gives binary-label unary weights (1,4), (3,1), (1,2). Each adjacent equal-label pair contributes multiplier r≥1. There are no boundary factors. The lab enumerates all eight sequences, sums their weights for Z(x), and obtains exact sequence probabilities and marginals. These are illustrative scores, not learned parameters or an accuracy benchmark.",
    takeaway: "Normalize over complete labelings for this input. A sequence MAP decision, an individual label marginal, and independent unary predictions answer different questions.",
    prerequisites: [topic("markov-random-fields"), topic("sum-product-algorithm"), topic("viterbi-decoding")], sources: [crf, source("Sutton & McCallum: expanded CRF tutorial", "https://arxiv.org/abs/1011.4088")],
    ideas: [["The input is conditioned on", "Unary scores may come from hand-designed features or a learned encoder. This lab fixes those scores while changing compatibility. The CRF specifies P(y|x); it does not by itself provide a distribution for generating x."], ["Normalization couples complete outputs", "For each fixed input, Z(x) sums the weights of all allowed label sequences. Dividing each transition row by its own sum would define a different, locally normalized model. The numbers in the unary table are weights, not calibrated class probabilities."], ["Agreement can reverse the unary decision", "Ignoring neighbors selects 101 because each position takes its strongest unary score. That sequence earns no agreement multiplier. The alternative 111 has weaker unary score but two agreements, so its total weight can overtake 101."], ["Inference and learning need different outputs", "For a chain of length T with K labels, forward-backward obtains the normalizer and marginals in O(TK²) for dense pair factors; max-sum with backpointers decodes a best sequence. Conditional log-likelihood training compares observed feature counts with model expectations. Neural parameterization need not preserve the convexity of a fixed-feature linear model."]],
    process: ["Declare the allowed labels, graph and score functions for a fixed input.", "Compute the conditional normalizer and marginals with sum-product; decode a whole sequence with max-sum and traceback.", "Evaluate sequence predictions and probability quality separately; tune compatibility on held-out data rather than assuming smoother labels are always better."],
    example: ["The second label flips in the winning sequence", "Set r=3.", ["Sequence 101 has unary weight 4×3×2=24 and no matches. Sequence 111 has unary weight 4×1×2=8 and two matches, giving 8×3²=72.", "In binary order 000 through 111, all weights are (27,18,1,6,36,24,12,72), summing to Z(x)=196.", "The joint winner is 111 with probability 72/196≈0.367347. Yet P(y₂=1|x)=(1+6+12+72)/196≈0.464286, below one half."], "The middle component of the most probable complete sequence need not be that component's marginally most probable label."],
    pitfalls: ["A larger compatibility weight need not improve accuracy; it can suppress real boundaries.", "A CRF probability is not automatically calibrated just because it is normalized.", "Efficient linear-chain inference does not imply tractable inference for arbitrary CRF graphs. Adding long-range label interactions can destroy the chain structure."],
    implementation: ["Use log-sum-exp for the forward normalizer and preserve forbidden transitions as −∞ log scores. Keep forward marginal inference separate from Viterbi traceback.", "For training, compute the normalizer for every input and use the same masks and transition constraints during training and decoding."],
    outcomes: ["Calculate globally normalized probabilities for a tiny structured-label model.", "Explain why unary decisions, marginal decisions and joint decoding can disagree."],
  }),
  [topic("dynamic-bayesian-networks")]: reviewed({
    title: "Dynamic Bayesian networks", labTitle: "Keep the joint state across time",
    summary: "A dynamic Bayesian network represents a stochastic process through an initial distribution and directed dependencies within and between time slices. Factoring a state into variables can compactly describe transitions, but the filtering posterior over those variables can still be dependent.",
    hook: "A compact transition diagram does not guarantee a factored posterior.", model: "structured-dbn", control: ["Number of alarm readings incorporated", 1, 6, 1, 2],
    equation: "P(Rₜ,Hₜ|O₁:ₜ) ∝ P(Oₜ|Hₜ) Σr,h P(Rₜ|r)P(Hₜ|h,Rₜ)P(r,h|O₁:ₜ₋₁)",
    assumptions: "Binary regime R and fault state H start independently with P(R₁=1)=0.5 and P(H₁=1)=0.2. For t≥2, R stays unchanged with probability 0.9. P(Hₜ=1|Hₜ₋₁,Rₜ) is [[0.05,0.6],[0.7,0.95]], rows previous H and columns current R. P(Oₜ=1|Hₜ=0)=0.1 and P(Oₜ=1|Hₜ=1)=0.9. Readings are (1,1,0,1,0,0). The first reading updates the initial distribution without an extra transition. Parameters are fixed across later slices.",
    takeaway: "Use the graph to factor the transition, then retain the dependencies required by inference. Four joint states are small here; a larger coupled interface can be expensive.",
    prerequisites: [topic("bayesian-networks"), topic("hidden-markov-models"), topic("conditional-independence")], sources: [dbn, source("Murphy: specifying and unrolling DBNs", "https://www.cs.ubc.ca/~murphyk/Bayes/usage_dbn.html")],
    ideas: [["Specify the initial slice separately", "The initial R and H distribution is part of the model, not an output of the recurring transition. Here it is (0.4,0.1,0.4,0.1) in state order 00,01,10,11. An accidental transition before reading O₁ would answer a different question."], ["Within-slice and temporal edges differ", "Rₜ₋₁→Rₜ carries regime persistence; Hₜ₋₁→Hₜ carries fault persistence. Rₜ→Hₜ is a current-slice dependency, and Hₜ→Oₜ emits an alarm. The unrolled directed graph must be acyclic even when the process exhibits feedback across time."], ["Conditional factorization is not posterior independence", "The transition factors into P(Rₜ|Rₜ₋₁)P(Hₜ|Hₜ₋₁,Rₜ). This is not a product of independent R and H transitions: H explicitly depends on the new R. After two readings the joint posterior differs from the product of its marginals, which the lab measures directly."], ["A representation, not one inference algorithm", "A DBN can describe an HMM, a linear-Gaussian state-space model, or several interacting processes. Filtering uses observations through the current time; smoothing also uses later observations. Exact discrete inference can require large joint interface tables; Gaussian or approximate methods exploit different assumptions."]],
    process: ["Write the initial distribution, each conditional probability table, and the within- and between-slice edges.", "Predict the next joint hidden-state distribution using the transition factors, then multiply by the current observation likelihood.", "Normalize and carry the joint posterior forward. Use only the selected observation prefix when reporting filtering results."],
    example: ["Two consecutive alarms", "Start with joint prior (0.4,0.1,0.4,0.1).", ["O₁=1 multiplies that prior by (0.1,0.9,0.1,0.9), giving (0.04,0.09,0.04,0.09). Divide by 0.26: P(H₁=1|O₁)=9/13≈0.692308 and R remains 0.5.", "Predict time 2 to obtain joint probabilities (0.25,0.25,0.078846,0.421154), rounded here only for display.", "O₂=1 gives evidence normalizer 0.636923 and posterior (0.039251,0.353261,0.012379,0.595109). Hence P(R₂=1|O₁:₂)=0.607488 and P(H₂=1|O₁:₂)=0.948370."], "The joint probability of R₂=H₂=1 exceeds the product of its marginals by about 0.018986. Keeping only independent marginal summaries would discard that dependence."],
    pitfalls: ["A time-invariant transition does not imply the state distribution is stationary; the initial distribution and observations matter.", "Dynamic describes a temporal process, not a requirement that graph structure changes at every time step.", "Do not interpret these dependency arrows as identified causal effects without additional causal assumptions. Do not use future alarms in a filtering result."],
    implementation: ["Name each conditional table's child and ordered parent axes. Check row normalization and distinguish the initial update from recurring predict-update steps.", "Monitor observation normalizers and handle impossible evidence. If approximating the joint state by factors or particles, report that approximation rather than inheriting exactness from the DBN notation."],
    outcomes: ["Unroll a two-slice template and compute joint-state filtering updates.", "Distinguish compact transition factorization from independence of posterior state variables."],
  }),
};
for (const lesson of Object.values(structuredLessons)) lesson.updatedAt = "2026-09-30";
